- theme/templates/accounts/profile.html
1. If you have geo feature resource types, you should see the corresponding resource type icon being displayed on profile page.
> Fix for geo feature resource type missing icon

- hs_core/views/__init__.py
- theme/templates/pages/group.html
> Fixes #1505

- hs_core/templates/pages/collaborate.html
- theme/static/js/collaborate.js
> [3362] display friendly message when no group found

- hs_app_netCDF/page_processors.py
- hs_app_timeseries/page_processors.py
- hs_collection_resource/page_processors.py
- hs_composite_resource/page_processors.py
- hs_core/page_processors.py
- hs_geo_raster_resource/page_processors.py
- hs_geographic_feature_resource/page_processors.py
- hs_model_program/page_processors.py
- hs_modelinstance/page_processors.py
- hs_modflow_modelinstance/page_processors.py
- hs_script_resource/page_processors.py
- hs_swat_modelinstance/page_processors.py
- hs_tools_resource/page_processors.py
1. Create a resource. Make sure the resource is not public. Copy the url for the resource landing page then logout. Paste the resource url for the resource that you created. It should take you to the login screen. Now when you login, it should take you to the resource landing page as per the resource url you used.
> Redirect to resource after login

- theme/static/js/dashboard.js
- theme/templates/pages/dashboard.html
#3388 
@Lizabrazil Requested changing text in Dashboard, i.e. home page.
> [3388] Change text and id of getting started toggle

- theme/views.py
See #3392 Detailed description 
Quick briefing: When a user not login, www.hydroshare.org should not redirect to www.hydroshare.org/landingPage. The url should not change. 
> no redirect before user login

- theme/templates/resource-landing-page/modals.html
> Fixes #3120

- hs_core/management/commands/set_bag_dirty.py
- hs_core/models.py
> Fix for xml namespace

- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- theme/static/js/composite-resource.js
- theme/static/js/coverageMap.js
- theme/static/js/generic-resource.js
- theme/static/js/hs-vue/subjet-keywords.js
- theme/static/js/hs_file_browser.js
- theme/static/js/modals.js
- theme/static/js/resourceLandingAjax.js
- theme/static/js/timeseries-resource.js
- theme/templates/resource-landing-page/subject.html
This PR implements the first steps of updates to the frontend logic in direction to https://github.com/hydroshare/hydroshare/issues/3186
In here, we rewrite functionality regarding keywords so that it uses a Vue instance. It simplifies the logic a lot and provides better mechanisms to manage the UI state.
This work also includes minor code refactoring and improvements.
2. Test all functionality regarding Keywords and make sure it all works as expected.
> [#3186] Keywords vue instance in Resource Landing page

- hs_core/views/__init__.py
- theme/static/css/hydroshare_core.css
- theme/static/js/group.js
- theme/templates/pages/group.html
https://github.com/hydroshare/hydroshare/issues/2821 This PR addresses a lot of issues created before last release and that seem to have made it to www due to lack of testing. In order to fix these I had to revert changes from previous conflicting PRs. I then fixed the things those PRs were addressing in a clean way.
See https://github.com/hydroshare/hydroshare/issues/2821#issuecomment-501079074 for the list of bugs this is addressing.
Here is a traceback for what seems to have caused these issues:
- Shared By filter broken with the removal of Author data the script needs here: https://github.com/hydroshare/hydroshare/commit/f5ade7c1f8dc54c0316a56a4948ba477dfe2415e#diff-f5ff8acfcb7057a2f158ab46e6b9f380R646
- Issue raised regarding Shared By filter being broken: …
> [HOTFIX][#2821] Fix for broken Group page functionality

- hs_core/tasks.py
Addressing issue #3442: Over quota warning emails should be sent every first Monday of each month with this PR.
> issue #3442: changed quota warning email frequency

- Dockerfile
> update to latest hs_docker_base image

- hs_core/management/commands/migrate_resources_from_userzone_to_datazone.py
1. Run the migration command on beta to migrate 1 remaining empty resource over successfully.
> fixed the empty resource migration issue

- theme/static/css/hydroshare_core.css
- theme/templates/includes/profile-card.html
Fixes a couple of layout issues identified in beta deployment of RC-1.24.
Identifier icons in profile badge:
- Fixed a bug where ResearcherID icon would be used erroneously instead of ResearchGate icon.
- Fixed icons misalignment
Before:
After:
Other minor changes:
- Fixed a bug that would cause tooltips to be wider than necessary.
- Removed unused commented out code.
> [RC-1.24][#3439] Fix alignment of identifier icons

- theme/management/commands/set_quota_holder.py
> 3351 fix missing quota holder

- theme/templatetags/comments_tags.py
#3500
1. Create a comment with a valid url.  Validate the url is not hyperlinked.
> [#3500] disable hyperlinks in comments

- django_irods/views.py
- hs_file_types/models/reftimeseries.py
This is a quick fix for Issue #3511. I just added the redirect_url property found in the GenericLogicalFile to the RefTimeseriesLogicalFile.
1. From the landing page of a resource with reference time series content, try downloading the refts file using the download button, and then using the file URL.
> Added redirect_url property to RefTimeseriesLogicalFile

- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- hs_core/urls.py
- hs_core/views/__init__.py
- hs_tools_resource/static/css/toolresource.css
- theme/static/js/hs-vue/relevant-tools.js
- theme/static/js/hs_file_browser.js
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/title-section.html
#3506 
1. The initial response of the resource landing page should take about 2 seconds with a copy of the production database.
2. Validate web app connectors show in the open with button as well as in the dropdown list for relevant aggregations and files.
> Async relevant tools

- theme/static/js/hs-vue/subject-keywords-app.js
- theme/templates/resource-landing-page/subject.html
As described in #3521, adds a conditional check to render this message only when the resource is in Edit mode.
> [#3521] Hide keywords edit message in view mode

- hs_core/management/commands/delete_hanging_logical_files.py
update the logic to delete hanging logical files that don't have a resource or files.
> delete hanging logical files that meet either criteria

- hs_composite_resource/models.py
- hs_core/tasks.py
- hs_file_types/tests/test_netcdf_metadata.py
- hs_file_types/tests/test_raster_metadata.py
- hs_file_types/tests/test_timeseries_metadata.py
> Optimize aggregation lookup

- setup.cfg
Per team discussion, increasing line length tolerance to 120 from 100
> Change flake8 line max to 120

- hs_core/hydroshare/resource.py
A fix for the chaos this morning due to mezzanine set_slug logic.
> set the slug directly on resource creation

- theme/static/js/custom.js
Fix oversight in new title with conditional
Test Case:
1. Create a resource without providing initial title and observe you get 'Untitled resource'
2. Create resource and provide title and see it propagate to the resource edit page
> Add conditional

- theme/static/js/hs-vue/relevant-tools.js
1. Create or find a web app that is added to your open with list, has a file or aggregation level url and no resource level url.  Navigate to a resource, verify the web app shows when right clicking on an appropriate aggregation or file AND NOT the resource level open with dropdown.
> [#3583] - fix bug in url parsing of tools

- hs_core/views/debug_resource_view.py
@alvacouch - This will fix the debug resource page for most resources and should be a quick review.
> use check_irods_files from hs_core management utils

- hs_core/management/commands/solr_update.py
This fixes reporting in the new management command `solr_update`. 
1. [Enter positive test case here] After the change, the complete number of SOLR resources after update are reported. Before the change, only the ones before the update are reported.
> 3600 fix dumb typo in management command

- theme/static/js/hs-vue/left-header-app.js
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/resource-header.html
- theme/templates/resource-landing-page/title-section.html
Fixes a bug preventing editing of author data. Described in https://github.com/hydroshare/hydroshare/issues/3602
Also improves error messages displayed to users in case of form errors when adding/editing Authors.
#3611
1. Go to a resource.
2. Add/edit Authors and verify that the operations are performed without errors.
> [#3602] Fix for bug preventing editing of Author data

- django_irods/views.py
- hs_core/models.py
- hs_core/views/resource_folder_hierarchy.py
This is cleanup work to address issue #3562.
> cleanup is_federated check in django_irods view function

- Dockerfile
- hydroshare/settings.py
1. Open the hydroshare home page with the networks panel open.  Refresh the page and take note the js and css files are retrieved through cache.  Update the FRESHLY_ASSETS_VERSION, restart hydroshare and refresh the home page.  Note the version has been updated in the request and the requests were not retrieved from cache.
> 3621 django freshly

- theme/templates/pages/group.html
Fixes https://github.com/hydroshare/hydroshare/issues/3636
1. Log in, browse to Group and observe Overview tab is gone and Resources are listed by default
> Remove Overview tab in Groups

- local-dev-first-start-only.sh
- local-dev.yml
updates configuration for celery concurrency with updated local configuration
> add celery concurrency to local dev first start

- Dockerfile
> bump hs_docker_base version

- hs_communities/templates/hs_communities/community.html
- hs_communities/views/communities.py
Fixes https://github.com/hydroshare/hydroshare/issues/3657
1. Log in as non CZO member observe Admin tab is not present on Community page
2. Log in as czo_national observe Admin tab is present
> Hide admin

- hydroshare/settings.py
> remove django-freshly until a patch is made

- hs_communities/templates/hs_communities/community.html
- hs_communities/views/communities.py
- theme/templates/pages/group.html
- Fixes https://github.com/hydroshare/hydroshare/issues/3636
- Fixes https://github.com/hydroshare/hydroshare/issues/3672
This has been deployed to http://dev-hs-7.cuahsi.org/ and due to the complexity of manual test cases, CUAHSI will coordinate the testing effort outside of this PR.
> 3672 request to join

- hs_core/testing.py
- hs_core/views/utils.py
- theme/static/js/profile.js
- theme/views.py
This PR makes iRODS user creation functionality a bit more robust to accommodate errors being raised from iRODS. It also fixed user notification for deleting iRODS user account to improve user experience.
> make irods user creation more robust

- irods_browser_app/static/js/irods_signin.js
- irods_browser_app/templates/irods_signin.html
> give default host and zone for irods signin

- Dockerfile
- hs_core/tests/api/rest/test_resource_science_meta.py
- hs_core/views/resource_metadata_rest_api.py
- hs_tools_resource/migrations/0021_url_rename.py
- hs_tools_resource/models.py
- hs_tools_resource/page_processors.py
- hs_tools_resource/serializers.py
- local-dev-first-start-only.sh
- local-dev.yml
1. GET/PUT Resource Type (e.g. ToolMetaData) specific metadata at `/hsapi/resource/{id}/scimeta/elements/`
> 3553 tool serializer

- Dockerfile
1. Download a resource bag with a non-ascii character in the abstract ((hold alt) 2019)
> use sed for utf-8 locale

- hs_core/management/commands/solr_update.py
- hs_core/search_indexes.py
When debugging building of dev-hs-4.cuahsi.org, I happened to notice that discovery was crashing. This was due to resources not containing `metadata` or specific `metadata` elements. 
This PR proofs both native harvesting and the `solr_update` management command against this kind of problem. (It also fixes one regular expression in `hs_core/search_indexes.py` according to python 3 standards)
1. Management command `python manage.py solr_update --force` works without crashing.
> Fix SOLR harvesting crashes due to incomplete and/or corrupt resources.

- theme/templates/resource-landing-page/title-section.html
The fix should fix the schema.org json-ld script error for some resources that fail google dataset search validation.
> fixed schema.org syntax issue

- hs_tracking/management/commands/stats.py
> Fix hs_tracking stats yesterdays-variables command

- django_irods/storage.py
- hs_core/tests/api/native/test_get_resource_file.py
- setup.cfg
> added get_modified_time() and test

- hs_access_control/management/commands/README.md
- hs_access_control/management/commands/access_community.py
- hs_access_control/management/commands/access_community_public.py
- hs_access_control/management/commands/access_public_groups.py
- hs_access_control/management/commands/groups_with_public_resources.py
This fixes a few user messages that I noticed were out of date when using management commands. It also corrects comments for changes in command names. It does not affect function. 
1. Using `python manage.py access_community` in error does not print erronious command name. Documentation at top of file for `hs_access_control/management/commands/access_community.py` is now correct. 
2. Did same thing for all other commands in hs_access_control/management/commands.
> Fix access control management command messages.

- hs_file_types/models/raster.py
- hs_file_types/tests/logan2.vrt
- hs_file_types/tests/test_raster_metadata.py
1. Place two different rasters into a composite resource and ensure both are aggregated successfully.
> 3716 raster folder

- hs_core/hydroshare/utils.py
- hs_core/views/utils.py
This fixes the regression issue #3776.
> fixed iRODS add file bug #3776

- django_irods/storage.py
> hotfix for timestamp issue with file listing on production

- hs_core/tests/api/rest/test_oauth_group.py
- hs_core/views/oauth2_view.py
- hydroshare/urls.py
1. Make an oauth authorization request to `/o/groupauthorize/{group_id}` to a group your user is in.  Verify authorization is completed and you are redirect to the provided redirect url.
2. Make an oauth authorization request to `/o/groupauthorize/{group_id}` to a group your user is NOT in.  Verify authorization fails and you are redirected the group's hydroshare page.
> Group oauth registration

- hs_tracking/management/commands/stats.py
> remove more string encoding cast back to strings

- django_irods/storage.py
> added collection constraint into checksum query

- hs_core/management/commands/migrate_raster_resources.py
> [#3249] - save resource after metadata is copied

- hs_core/models.py
Fixed the bug reported in https://github.com/hydroshare/hydroshare/issues/2984. That workflow should work now with this PR bug fix.
> 2984 unzip bag

- hs_access_control/models/user.py
- hs_access_control/tests/test_resource_flags.py
- hs_core/hydroshare/resource.py
- hs_core/models.py
- hs_core/page_processors.py
- hs_core/views/utils.py
- theme/static/js/generic-resource.js
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/top-right-buttons.html
1. Open a resource that you have no permissions for and is public, ensure the resource copy button is available.
2. Open a resource that is discoverable (not public) and you have no permissions for.  Validate the resource copy button does not show.
3. Open a resource that is discoverable and you have view permissions for.  Validate the resource copy button does show.
> 3803 copy discoverable

- theme/templates/includes/legend.html
1. Find the hydroshare legend on my-resources (or discover, groups, communities..) and verify it looks something like below.
> [#3807] - update legend with content types

- theme/static/css/hydroshare_core.css
1. Look at the metadata of an aggregation.  A long string, like the coordinate string should wrap and not overflow outside of the box.  Look at the method metadata, and ensure it doesn't overflow outside of the box but also not break between words.
> [#3803] - remove word-break

- hs_tracking/tests/test_tracking.py
- hs_tracking/utils.py
- hs_tracking/views.py
> [#3815] check redirect url in app launch exists in a web app

- hs_core/models.py
- hydroshare/urls.py
- theme/static/js/generic-resource.js
- theme/static/js/modals.js
- theme/templates/generic/includes/comment.html
- theme/templates/resource-landing-page/modals.html
- theme/views.py
#1369 
1. Login as an admin, find a comment and confirm you can delete the comment.
2. Login as a resource owner, find a comment on your resource not created by you and confirm you can delete the comment.
3. Login as a normal user, make a comment and confirm you can delete the comment.
4. Delete a comment with a comment thread.  Confirm the confirmation message includes messaging about the threaded comments.  When you delete the comment, the thread should not appear either.
> 1369 comment delete

- theme/management/commands/reset_quota.py
> added force quota reset management command

- django_irods/storage.py
This workaround will fix the resource without header issue as shown here: https://www.hydroshare.org/resource/e12778e5718b414ab530381e89bf24ed/. The fix has been deployed to beta manually to verify this fix so https://beta.hydroshare.org/resource/e12778e5718b414ab530381e89bf24ed/ works with resource header properly displayed.
> Resource without header fix

- hs_core/tasks.py
> not to send out quota warning emails on debug server

- theme/management/commands/dump_user_quota.py
> don't encode str before writing to file

- django_irods/icommands.py
> force quota reset management command bug fix

- theme/management/commands/dump_user_quota.py
> added used quota value into dumped quota file

- hs_core/hydroshare/resource.py
- theme/management/commands/report_quota_inconsistency.py
The management command can be run as ```./hsctl managepy report_quota_inconsistency quota_inconsistency.csv```
> added quota inconsistency report management command

- hs_collection_resource/page_processors.py
- hs_collection_resource/templates/pages/collectionresource.html
> Collection speedup

- theme/management/commands/report_quota_inconsistency.py
https://github.com/hydroshare/hydroshare/pull/3851
> Quota report

- theme/management/commands/report_quota_inconsistency.py
https://github.com/hydroshare/hydroshare/pull/3851
> remove colon from django key

- django_irods/views.py
- hs_core/tasks.py
> add better exception handling

- hs_core/management/commands/repair_resource.py
1. Run repair_resource on a resource with ResourceFiles in django but not on irods.  https://new-hs-ci.hydroshare.org/view/02%20-%20Deployment/job/Beta%20deployment/job/beta-hsctl-command/134/console
> fix repair_resource management command

- hs_core/tests/api/views/test_group.py
- hs_core/views/utils.py
- theme/backends.py
1. As a user, request access to a group that does not auto-approve membership.  As the group administrator, after the user has requested access, login to hydroshare and then log back out.  Then follow the authorization link sent to the administrator's email.  Confirm the user is added to the group with an appropriate method on the header bar.
> [#3889] - use token hash without login date for group membership

- Dockerfile
> Pull in latest hs_docker_base 1.13

- nginx/config-files/hydroshare-ssl-nginx-ingress.conf.template
Currently deployed and functioning on beta.
Currently functioning on beta.
Code comments. No end user involvement.
1. Functions on beta.
> [#3887] redirect subdomains other than www on port 443

- hs_core/models.py
1. Navigate to resource d7d98390ab884eeda89f4a10b072bbc3 and validate it loads
> handle validation error when file not on irods and lazily caclulate size

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/hydroshare/resource.py
> 3888 version published

- nginx/config-files/hydroshare-ssl-nginx-ingress.conf.template
Reverts hydroshare/hydroshare#3894
> Revert "[#3887] redirect subdomains other than www on port 443"

- hydroshare/settings.py
1. Navigate to hydrohsare.org/hsapi and verify it renders
> remove deprecated swagger settings

- django_irods/storage.py
- hs_core/models.py
- hs_core/tests/api/native/test_get_resource_file.py
- hs_core/tests/api/rest/test_resource_file.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
#3927
1. Hit the hsapi files/ endpoint and ensure each file includes a checksum
> include checksum on file listing

- theme/static/js/resourceLandingAjax.js
1. Create a new resource, scroll down to the spatial coverage and validate the box coverage radio is selected along with the four coordinate inputs for NESW.
> [#3902] fix point/box radio selectors

- theme/templates/resource-landing-page/manage-access.html
- theme/templates/resource-landing-page/top-right-buttons.html
1. Refer to issue #3938 to test.
> manage access tool tip fix

- theme/templates/resource-landing-page/manage-access.html
1. Refer to issue #3946 to test.
> Clarify shareable option (manage access)

- theme/templates/resource-landing-page/title-section.html
> Resource version display formatting

- hs_core/tasks.py
- hs_core/views/resource_folder_hierarchy.py
- hydroshare/settings.py
- theme/static/js/hs-vue/notifications-app.js
- theme/static/js/resourceLandingAjax.js
provides implementation of unzipping to the async framework.  It also includes a js vue update to check if a task can be aborted if the task provides an abort message.
> Async file unzip

- hydroshare/irods/ruleGenerateBagIt_HS.r
> 3935 bag manifest

- config/hydroshare-config.yaml
- hsctl
- hydroshare/urls.py
These steps are for the dev-hs-x instances:
1)  Log onto a dev-hs-x instance: ssh [user]@dev-hs-x
a. Change to hydro-service user: sudo -u hydro-service -s
b. cd ~/hydroshare
c. ./hsctl rebuild --db
Runs as normal ./hsctl rebuild --db run.
Code is part of hsctl.
> Streamlined hsctl nodejs deploy

- hs_core/management/commands/solr_facets.py
This fixes a debugging command that allows one to check on the health of SOLR facets from the command line. 
> Fix dumb typo in solr_facets management command.

- nginx/config-files/hydroshare-nginx.conf.template
- nginx/config-files/hydroshare-ssl-nginx.conf.template
> Add sendfile chunks and aio threads to global scope

- config/hydroshare-config.yaml
- hsctl
- hydroshare/urls.py
This PR reverts previous changes made in PR#3973 and re-commits only changes to hsctl for node deployment.
> Node revert

- hs_core/tests/api/rest/test_resource_list.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
1. head over to hsapi and execute a GET on /hsapi/resource/.  Update the page to 5, and the count to 2.  Execute the query.  Ensure the results contains a next and a previous entry.  The results should show only 2 resources, but the count should be somewhere around 4000.
> pushing serializing of resource to the serializer

- hs_core/hydroshare/users.py
- hs_core/tests/api/native/test_create_account.py
- theme/forms.py
- theme/static/js/profile.js
- theme/templates/accounts/profile.html
- theme/templates/accounts/sign_up_form.html
> Add more required fields when users signup for better user tracking and reporting

- hs_discover/public/index.html
- hs_discover/src/components/Resources.vue
- hs_discover/views.py
This addendum to Discover addresses a number of problems found by stakeholders, prior to QA phase:
Fixes https://github.com/hydroshare/hydroshare/issues/4000
Fixes https://github.com/hydroshare/hydroshare/issues/3998
Fixes https://github.com/hydroshare/hydroshare/issues/3997
Fixes https://github.com/hydroshare/hydroshare/issues/3995
Deployment for verification of this PR is at https://dev-hs-6.cuahsi.org/search/
> New Discover

- hsctl
> Updating hsctl to read hydroshare home directory from config

- theme/management/commands/reset_quota.py
Quota reset command run should take user zone into account now.
> make reset quota command to take user zone into account

- hs_core/views/user_rest_api.py
- theme/static/js/custom.js
- theme/static/js/profile.js
- theme/templates/accounts/sign_up_form.html
> corrected legacy unspecified user profile fields

- hs_core/hydroshare/resource.py
- hs_core/signals.py
- hs_core/task_utils.py
- hs_core/tasks.py
- hs_core/tests/api/views/test_delete_resource.py
- hs_core/views/__init__.py
- hs_core/views/resource_rest_api.py
- hs_tracking/signals.py
- hydroshare/settings.py
- theme/static/js/generic-resource.js
- theme/static/js/hs-vue/notifications-app.js
- theme/static/js/hs_resource_table.js
- theme/templates/resource-landing-page/modals.html
> pulled resource deletion out from async

- theme/templates/accounts/profile.html
…date for empty user type users
> Enable an empty user type user to select the first entry in the user type list

- hsctl
> Node fix - for Jenkins errors

- local-dev-first-start-only.sh
The changes are not highlighted but are found after line 342 in the following section:
echo " Reindexing SOLR"
> Fix for local development solr schema

- theme/static/js/profile.js
call change() for user_type when opening edit profile for selection event trigger.
> Fix disappearing user_type bug

- hs_discover/public/index.html
- hs_discover/src/components/Resources.vue
- hs_discover/src/components/Search.vue
- hs_discover/views.py
- theme/templates/newbase.html
Some styling and bugfixes for Discover. Functionality review can be performed at https://dev-hs-6.cuahsi.org/
Fixes https://github.com/hydroshare/hydroshare/issues/4072
Fixes https://github.com/hydroshare/hydroshare/issues/3920
Fixes https://github.com/hydroshare/hydroshare/issues/4029
Fixes https://github.com/hydroshare/hydroshare/issues/4058
Fixes https://github.com/hydroshare/hydroshare/issues/3925
Fixes https://github.com/hydroshare/hydroshare/issues/3919
Fixes https://github.com/hydroshare/hydroshare/issues/3918
Fixes https://github.com/hydroshare/hydroshare/issues/4034
> Discover Bugfixes Round 1

- local-dev-first-start-only.sh
Re-added nodejs build and solr fixes in local-dev-first-time-only.sh for local build environments.
Tested by building and navigating to local url and validating resource creation and login.
Also verified removal and re-add of fields withing the schema.xml.
> Local dev fix

- hs_core/tasks.py
Removing the celery task for syncing mailchimp in favor of using the jenkins jobs.  Currently, both the celery task and the jenkins jobs are running.  This is unnecessary.
- http://ci.hydroshare.org:8080/view/03-Housekeeping/job/update-MailChimp-emails-60days-list/
- http://ci.hydroshare.org:8080/view/03-Housekeeping/job/update-MailChimp-emails-full-list/
1. Check the jenkins jobs linked above.
> disable celery mailchimp sync in favor of using jenkins job

- hs_core/task_utils.py
Anonymous users are requesting a task list with null usernames.  This update returns an empty list for task listings with anonymous users.
1. Download a resource without being logged in, then navigate to a new page.  Confirm the download doesn't start again.
> return empty task list for anonymous users

- .gitignore
- pytest/conftest.py
- pytest/functional/hs_discover/test_solr_haystack.py
A PyTest for Dan to test environments with 3936-discovery-backend-improvements
> Add solr pytest

- theme/templates/resource-landing-page/title-section.html
> updated vocab schema.org url to be compatible with DataONE

- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/tasks.py
- hs_core/tests/api/native/test_irods_user_zone_federation.py
- hs_core/tests/api/views/test_replicate_bag_to_user_zone.py
- hs_core/views/__init__.py
- hydroshare/settings.py
- theme/static/js/generic-resource.js
- theme/static/js/hs-vue/notifications-app.js
- theme/templates/includes/notifications-app.html
- theme/templates/resource-landing-page/modals.html
> added copy resource bag to user zone to async task

- nginx/Dockerfile-nginx.template
- nginx/Dockerfile.template
- nginx/hs_proxy/nginx/docker-compose.yml
This is a feature-parity pull request whose only purpose is to update nginx to the current version 1.19. All of my evidence so far is that this is a clean update with no feature changes or problems. 
Nothing changes at all!
> Update nginx to version 1.19

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/tasks.py
- hs_core/views/__init__.py
- hydroshare/settings.py
- theme/static/js/generic-resource.js
- theme/static/js/hs-vue/notifications-app.js
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/top-right-buttons.html
> get versioning moved to async

- hs_core/tasks.py
1. Download a large bag.
2. Modify the resource.
3. Download again.
> [#4135] Delete an existing bag before repaving.

- pytest/conftest.py
SOLR changed, so the test needs to match.
> Update Discoverable attribute to match new SOLR requirements

- hs_core/hydro_realtime_signal_processor.py
In testing the code for the initial version of this PR, I discovered that SOLR isn't indexing for changes to metadata.  This PR fires new indexing tasks for 
1. Changes to the BaseResource or ResourceAccess object, as before. 
2. Changes to the metadata object associated with the BaseResource (regardless of type).
3. Changes to the extra_metadata object associated with the BaseResource.  
4. Changes to objects referenced by the metadata object of the BaseResource.
1. Changing any discoverable aspect of the resource main metadata (title, description, subjects, ...) after making it discoverable is reflected in discovery.
> add missing realtime processing to SOLR.

- hs_core/hydro_realtime_signal_processor.py
- hs_core/management/commands/solr_check.py
- hs_core/management/commands/solr_update.py
- hs_core/search_indexes.py
- hs_core/templates/search/indexes/hs_core/baseresource_text.txt
- hs_core/templatetags/hydroshare_tags.py
This is an initial effort to feed variables from composite resources into discovery. These variables were lost when we switched from resource types to file types. 
Searching for a variable name yields all resources that contain that variable.
> 4179 fix composite resource discovery

- hs_core/templates/pages/genericresource.html
> 4184 schema org bug

- theme/static/js/composite-resource.js
1. Edit a resource with a box type and ensure the delete icon is available when the spatial coverage is box type.
> update id of radio button to delete box type resource

- hs_core/management/commands/solr_update.py
- hs_core/search_indexes.py
- hs_core/templates/search/indexes/hs_core/baseresource_text.txt
This is the second installment of harvesting aggregation metadata for discovery, including sites, sample mediums, methods, and other attributes of time series. 
1. If a logical file has metadata exposed by this change, specifying the metadata in an unrestricted search term will display the resource. This includes site name, method description, variable type, variable units, etc.
> 4179 discover logical file attributes

- hs_discover/views.py
Fix broken faceting by transitioning to new faceting syntax. 
1. Clicking on a facet in search displays resources with that attribute (not nothing).
> Fix faulty faceting based upon old syntax; convert to new syntax.

- hs_discover/views.py
Fix facet logic. "Or" within facets. "And" outside facets. 
1. Adding individual elements of facets increaases the number of results. 
2. Adding an element of a different facet invokes "and" between the facets.
> Fix boolean logic of facets

- hs_discover/views.py
I made a dumb syntax mistake in the fix that repeated results. FIxed. Sorry. 
1. Each result in discover appears once.
> Fix duplicates in discovery returns due to dumb bug in OR conditions.

- hs_discover/views.py
> update resource_type_exact index to resource_type

- theme/views.py
fixes #4219 
This fixes expired password reset tokens from displaying a "Sorry, an error occurred" message to "The link you clicked is no longer valid."  This message will display whether the user is logged in or not.
1. Request a password reset, click the resulting link twice.  Verify after the first click it sends you to the password reset form.  Verify after the second click it redirects you to the home page and displays "The link you clicked is no longer valid." at the top.
> [#4219] - check for user before checking if user is_active

- hsctl
> [#3702 Replace update_index with solr_update in hsctl]

- hs_composite_resource/models.py
The changes here are to make the WMS and WCS endpoints match the WFS endpoint. The WCS endpoint is being changed because the current endpoint will generate a connection that pulls every resource with WCS compatible data into the GIS Client. The new endpoint which will match the WFS endpoint will fix this issue. The WMS endpoint is being changed to match the other two and be easier to manage.
Edit: I'm still new to updating and adding code to Github so the extra commits were just me testing to see how the changes after a pull request was made would work. Also I deleted the auto-generated checklist by accident.
> [#4199] - Consolidating OGC URL Endpoints

- theme/views.py
Updated the password reset workflow and messaging.  I'll outline the scenarios below.
- User clicks an expired password reset link while logged in.  The User will be redirected to the password reset form.
- User clicks an expired password reset link while not logged in.  The User will be redirected to the password reset request page with a message "The link you clicked is no longer valid, please request a password reset link."
- User clicks a valid password reset link while logged in.  The User will be redirected to the password reset form.
- User clicks a valid password reset link while not logged in.  The user will be logged in and redirected to the password reset form.
1. Walk through the scenarios in the description and validate the expected results.
> 4219 password reset redirects

- theme/static/js/copyToClipboard.js
fixed whitespaces on copytoclipboard check it out
fixes #4200
>  trimmed text conect of copy to clipboard

- hs_composite_resource/models.py
- hs_core/templates/pages/genericresource.html
- hs_file_types/models/netcdf.py
- hydroshare/settings.py
- theme/templates/resource-landing-page/data-services.html
> 3826 netcdf web service

- theme/templates/generic/includes/rating.html
- theme/views.py
> [#2829] - redirect rating form

- theme/management/commands/cleanup_profile_media_files.py
- theme/models.py
- theme/static/css/hydroshare_core.css
- theme/templates/accounts/profile.html
- theme/views.py
This PR addressed the issue #3196. In addition to UI update/fix, the deleted files are now deleted from the system as they should. Specifically, when a profile picture or a CV is deleted, the picture and CV file is deleted from the system media file directory. A management command is also added to clean up the left over deleted files from profile media file directory that are not part of HydroShare user profiles.
> 3196 profile media file

- hs_file_types/model_meta_schema_templates/MODFLOW_Schema_1.0.0.json
- hs_file_types/model_meta_schema_templates/SWAT_Schema_1.0.0.json
> Updating model schema template json files

- hs_file_types/models/model_instance.py
> Fix for model instance aggregation meta xml file

- hs_file_types/forms.py
> Model program file types form field length limitation removed

- hs_file_types/models/model_instance.py
> Fix for model instance schema based metadata missing in view and meta xml file

- hs_core/templates/pages/genericresource.html
> file delete confirmation message change

- hs_file_types/forms.py
- hs_file_types/views.py
Used the wrong issue number in git commits.
fixes #4279
> Readable error message for metadata schema validation

- hs_core/receivers.py
> 4133 Update GeoServer when deleting files

- hs_file_types/models/geofeature.py
fixes #4302
1. Click on a geofeature aggregation in edit mode, verify the metadata form shows on the right side content panel.
> Include **kwargs to not error when user is passed to get_html_forms method

- hs_collection_resource/tests/test_collection.py
- hs_core/templates/pages/my-resources.html
- hs_core/tests/api/views/test_delete_resource.py
- hs_core/urls.py
- hs_core/views/__init__.py
- ref_ts/tests/test_ref_ts.py
- theme/static/js/generic-resource.js
- theme/static/js/hs_resource_table.js
- theme/static/js/modals.js
- theme/templates/resource-landing-page/modals.html
#fixes 3890
1. Press the delete icon on a resource you have owner permissions for.  Confirm the Delete button is disabled until you type "DELETE" in the textbox.
2. Ensure the textbox is cleared when the dialog is closed and reopened.
3. Ensure the resource is deleted when delete is clicked.
4. Follow the same steps on the my-resources page.
> Type "DELETE" resource delete confirmation message

- hs_core/templates/pages/genericresource.html
> Fix for in author name

- hs_core/templates/pages/genericresource.html
- theme/templates/resource-landing-page/coverage.html
1. Locally create a resource. 
2. Add spatial and temporal coverage data to the resource. Add any additional metadata required for publishing the resource. 
3. Then publish the resource. Though this is not going to be an actual publish, for the purpose of testing it should work. 
4.  Check that you are able to delete both spatial and temporal coverage for this published resource.
> Coverage can be deleted for published resource

- theme/forms.py
- theme/static/js/profile.js
- theme/templates/accounts/sign_up_form.html
- theme/templates/includes/form_field.html
1. Try to edit your profile by uploading a profile photo and then saving the changes. If any of the required profile field data is missing you should see a message accordingly and the profile editing form still be displayed. Otherwise the profile photo upload should be successful. 
2. Bring up the hydroshare user signup page. You should find that all required fields are marked with '*".
> Fix for profile update and signup form cleanup

- hs_core/templates/pages/my-resources.html
- theme/static/js/generic-resource.js
- theme/static/js/hs_resource_table.js
- theme/templates/resource-landing-page/additional-metadata.html
- theme/templates/resource-landing-page/title-section.html
1. Attempt to save HTML code to the name and value text fields of additional metadata.  Verify you cannot save them and you are given a notification explaining the issue.
2. Save HTML code through the API and verify the resource landing page displays the HTML text without rendering it.
> [#3685] - add javascript validation and messaging for html injection

- theme/templates/pages/group.html
1. Click the COLLABORATE link
2. Click the GROUPS link displayed in the collaborate page
3. Click the 'Find Groups' link it should refresh the page.
4. Click one of the groups displayed in the groups page to display the group details page.
5. In the group details page, click the 'Find Groups' link. It should take you back to the group listing page.
> Fix for find groups link

- hs_app_timeseries/tests/test_timeseries_metadata.py
- hs_file_types/models/timeseries.py
1. Create a composite resource. 
2. Upload a timeseries CSV file (you can use the file below)
[ODM2_One_Site_Multiple_Series.csv](https://github.com/hydroshare/hydroshare/files/7185867/ODM2_One_Site_Multiple_Series.csv)
3. Create a timeseries aggregation from the uploaded CSV file.
4. Remove the content type using the 'Remove content type' option.
5. Verify that you can recreate a timeseries aggregation from the same CSV file.
6. Upload an ODM2 sqlite file. You can download such a file from hydroshare and then use it for upload.
7. Create a timeseries aggregation from this sqlite file.
8. Remove the content type using the 'Remove content type' option.
9. Verify that you can recreate a timeseries aggregation from the same sqlite file.
> Timeseries content type delete

- hs_communities/templates/hs_communities/community.html
Fix dumb mistake by putting proper community name in title bar. 
> Put proper community name in title bar.

- hs_core/tests/data/test_resource_metadata_files/logan_meta.xml
- hs_geo_raster_resource/models.py
fixes #4354
1. Go to an aggregation rdf/xml
2. Right click on the aggregation
3. Click Download zipped
4. Open the _meta.xml file and compare the structure of spatial reference compared to spatial coverage.
> fix spatial reference rdf/xml generation in raster

- hs_access_control/management/commands/access_community.py
- hs_communities/templates/hs_communities/community.html
This is a quick fix to make the BuPuSa community production-ready by establishing a banner and a mission statement to its community in the community landing page template. Image will be uploaded via the `access_community` management command.  This is in review by @martinseul and @ClaraCogswell for appearance and is deployed currently on cuahsi-dev-1. 
See https://cuahsi-dev-1.hydroshare.org/community/2/.
> HOTFIX banner display for BuPuSa community.

- hs_core/tests/api/native/test_bag_ingestion.py
- hs_core/tests/data/test_resource_metadata_files/fileset_nested/fileset/fileset_meta.xml
- hs_core/tests/data/test_resource_metadata_files/fileset_nested/fileset/fileset_resmap.xml
- hs_core/tests/data/test_resource_metadata_files/fileset_nested/fileset/regularfile.txt
- hs_core/tests/data/test_resource_metadata_files/fileset_nested/fileset/singlefile.txt
- hs_core/tests/data/test_resource_metadata_files/fileset_nested/fileset/singlefile_meta.xml
- hs_core/tests/data/test_resource_metadata_files/fileset_nested/fileset/singlefile_resmap.xml
@pkdash, I missed your request for the nested ingestion test.  Here it is.
1. This is only an added unit test and if the jenkins build passes, we're golden.
> [#4355] - add nested ingestion test

- theme/static/css/hs-file-icons.css
- theme/static/css/hydroshare_core.css
- theme/templates/includes/legend.html
Update content and layout of legend
1. Go to My Resources page
2. Expand the Legend panel
3. Verify that the legend is accurate as described in #4357
> 4357 Outdated legend

- hs_discover/src/main.js
> [#4322] - drop delay to 20 seconds

- hs_core/tests/api/views/test_add_delete_resource_files.py
- hs_core/views/__init__.py
- theme/static/js/resourceLandingAjax.js
1. Create a resource and add abstract and keywords.
2. Add a file. You should see the 'Resource Status' message.
3. Go back to resource view mode and then back again to the resource edit mode.
4. Add another file. This time you should not see the 'Resource Status' message.
> 4149-fix for resource public/publication message repeat

- hs_tools_resource/app_launch_helper.py
- hs_tools_resource/models.py
- hs_tools_resource/tests/test_web_app.py
- hs_tools_resource/utils.py
- hs_tracking/tests/test_tracking.py
- hs_tracking/views.py
- theme/static/js/hs-vue/relevant-tools.js
1. Create a resource. 
2. Create an aggregation in that resource at the data/contents location (for testing aggregation level app launch). 
3. Create a folder and create another aggregation inside that folder (for testing aggregation level app launch).
4. Upload a text file at the data/contents location to test file level app launch.
5. Create a Web App Connector. Set the web app launch urls for file level and aggregation level web app launch. When specifying web app launch url make sure to use url pattern to use path parameter and/or query parameters. 
6. Also configure the web app connector so that app can be launched for the text file as well as the two aggregations you created.
7. Verify the web app launch url encoding by launching the web app from the text file as well as the each of …
>  web app launch url encoding

- hs_tools_resource/app_launch_helper.py
- hs_tools_resource/models.py
- hs_tools_resource/tests/test_web_app.py
- hs_tools_resource/utils.py
- hs_tracking/tests/test_tracking.py
- hs_tracking/views.py
- theme/static/js/hs-vue/relevant-tools.js
> Revert " web app launch url encoding"

- theme/static/css/hydroshare_core.css
- theme/templates/includes/create-group-modal.html
- theme/templates/pages/group.html
Add Owner Settings tab to Group page and adjust Group header layout.
1. Go to a group that you own.
2. Go to the Owner Settings tab and fill out the form.
3. Verify that changes are applied.
> 4372 Add Owner Settings tab

- hs_core/forms.py
2. In the resource editing page:
2.1. Try to update the resource level coverage metadata. Enter a name for the Place/Area name field only. Then click the 'Save changes' button. Coverage metadata update should fail and you should see data missing for specific coverage extent fields. Try to enter a suitable value for either the Longitude or the Latitude field. Then again try to save the changes. Update should fail and you should see data missing for specific coverage extent field.
2.2. Try to update the temporal coverage for the resource. Enter data for the Start date field only. Then click the  'Save changes'  button. Metadata update should fail and you see a message that data is missing for the end date. 
2.3. Upload a text file. Make that a single file aggregation. …
> 4156 Improved error message for coverage metadata

- hs_core/hydroshare/utils.py
- hs_core/tests/api/rest/test_user_details.py
1. GET the `/hsapi/userDetails` endpoint with a username with mismatching capitalizations
> [#4424] - update userDetails endpoint to be case-insensitive

- hs_access_control/models/user.py
- hs_core/templates/pages/groups-authenticated.html
- hs_core/views/__init__.py
- theme/templates/pages/group-unauthenticated.html
- theme/templates/pages/group.html
1. Create a group. Make the group discoverable. 
2. Logout of HydroShare
3. Click on COLLABORATE and then click on GROUPS.
4. In the Find Groups page, use the group search field to find the group you created. Verify you can see the group you created.
5. Login to HydroShare
6. Se the group that you created to private.
7. Logout of HydroShare
8. Click on COLLABORATE and then click on GROUPS.
9. In the Find Groups page, use the group search field to find the group you created. Verify you can't see the group you created
In addition to fixing the bug as described in #4211, this work also fixes several other issues as described in this document:
https://docs.google.com/spreadsheets/d/12rve0oe7Q3n0p7C3LpcGOdmpn7AinytslcbvUcuBCVw/edit#gid=0
> 4211-discoverable group

- theme/static/css/hydroshare_core.css
- theme/static/js/generic-resource.js
- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/references.html
--------------------------
Improve citation text layout for longer content.
- Copy button moved to top right.
- Simplify layout with CSS flex.
With short text:
With long text:
With edit button:
2. Verify proper layout of citation text
> Improve citation layout for longer content

- hs_discover/public/index.html
- hs_discover/src/components/Search.vue
- hs_discover/src/main.js
The Discover survey is no longer being used and should be removed.  This PR reverts the two commits for the discover survey.
1. Go to Discover in private browsing and verify the survey does not show on the right.
> Remove survey

- hs_core/templates/pages/metadata_terms.html
> fix #4449: update terms page to replace isCopyFrom to isDerivedFrom

- hs_core/tasks.py
> fixed issue #4450

- hs_core/management/commands/output_wrong_versioning_resources.py
> fixed a messaging issues

- hs_core/models.py
- hs_core/templates/403.html
- hs_core/templatetags/hydroshare_tags.py
Follow the workflow detailed in the issue #4415 to test. Everything should work as specified in the issue.
> addressed the issue #4415

- hs_core/management/commands/output_wrong_versioning_resources.py
> updates to management command

- theme/templates/accounts/profile.html
1. Edit profile -> click to add a photo. OS file selector will only display media files with image extensions. Save changes.
2. Edit profile -> click to update existing photo. OS file selector will only display media files with image extensions.
> only allow image file extensions for profile pic upload

- hs_collection_resource/templates/pages/collectionresource.html
- hs_core/templates/pages/genericresource.html
1. Open a collection or generic resource, find the bagit ui and click the "Learn more about the BagIt download" link
2. Redirects to [help.hydroshare](https://help.hydroshare.org/creating-and-managing-resources/view-and-download-a-resource)
Resolves #3614
> Resolves #3614 modify bagit help links

- hs_tools_resource/forms.py
- hs_tools_resource/models.py
- hs_tools_resource/serializers.py
- hs_tools_resource/static/js/toolresource.js
1. Create a new tools (app) resource
2. Scroll to "icon" and select "Bowse for file"
3. Save changes
Resolves #4474
> [#4474] hstools image upload (in addition to URL)

- hs_tools_resource/models.py
1. Edit an existing Tools Resource (or create a new one).
2. Preview and save works for the following URLs:
1. https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg
2. https://duckduckgo.com/favicon.ico
3. https://www.google.com/favicon.ico
4. https://www.pngall.com/wp-content/uploads/2016/07/Sun-Download-PNG.png
Resolves #2910
> Resolves #2910 allow web-app connector icons to be .ico and .svg

- hs_core/management/commands/fix_resource_versioning.py
- hs_core/management/commands/fix_resource_versioning_date.py
- hs_core/tasks.py
> 4472 4473 last updated fix

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/hydroshare/utils.py
- hs_file_types/models/base.py
- hs_file_types/models/fileset.py
- pytest/functional/hs_file_types/test_model_aggregation.py
1. Create resource.
2. Create a folder and upload a file to that folder. Set the folder to file set aggregation.
3. Delete the file that you uploaded. The leaves the file set aggregation with no files.
4. Create another folder and upload a file to that folder. Set the folder to Model Instance aggregation. 
5. Delete the file you uploaded in step 4 above. This leaves the Model Instance aggregation with no files.
6. Repeat step 4 and 5  for Model Program aggregation.
7. Make a copy of the resource. Verify the copied resource has one file set aggregation, one model instance aggregation and one model program aggregation.
> 4475 Fix for aggregation copy 

- theme/static/js/hs-vue/left-header-app.js
- theme/templates/resource-landing-page/modals.html
2. Try to add some existing HydroShare user as an Author more than once.
3. Verify that an error message is shown explaining that the user has already been added.
resolves #3608
> Disallow adding duplicate authors on a resource

- theme/templates/includes/navbar.html
- theme/templates/pages/homepage.html
- theme/templates/pages/menus/dropdown.html
1. The following links now open within the same browser tab:
* Top-level nav bar "apps" 
* "Who uses HydroShare?" icons on the homepage/landing-page
Resolves #3378
> internal hrefs no longer open new tab

- theme/static/js/resourceLandingAjax.js
1. Edit a generic resource that contains files
2. Select a file and click to add extended metadata
3. Enter text in the inputs
4. Do not confirm the changes.Press cancel
5. Reopen the extended metadata modal
6. The previous drafted metadata not show in the input boxes
resolves #3526
> clear metadata modal on cancel

- hs_core/templates/email/group_membership.html
- hs_core/templates/email/group_membership.txt
1. Navigate to Collaborate -> Groups and "ask to join" a group that your user is not a member of
2. Check debugger or Hydroshare Docker container logs: you will see that additional requested information has been added.
3. Added info includes:
* Last name
* Organization
* Country
* State
* Email
* Title
Resolves #2275
> update email template for join group requests

- hs_rest_api2/tests/data/json/resource.json
- hs_rest_api2/tests/test_file_json_metadata.py
1. Build should be successful with all tests passing.
> 4531 Fix for JSON api tests

- theme/static/js/hs_file_browser.js
1. Create multiple folders and add some files to them.
2. Delete the folders.
3. After some time, the operation seems to complete and the pinwheel stops spinning as expected.
Resolves #4066
> fix progress wheel after file deletion

- theme/static/js/hs-vue/manage-access-app.js
- theme/static/js/hs_file_browser.js
- theme/templates/resource-landing-page/modals.html
1. Manage who has access on a resource that has adequate metadata to be made public
2. First set the access to private
3. Within the file-browser-container, upload a file if the resource doesn't already have one
4. Right click the file -> "get file url"
5. You will see a message in the modal explaining that the resource is private
6. Now change the "manage access" to discoverable and "Enable private link sharing"
7. Right click the same file -> "get file url"
8. You see a message explaining that the resource is discoverable with link sharing
Resolves #2793
***
> message when sharing URL for private

- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/title-section.html
Resolves #4568
Fixes #4569 
1. Open a resource
2. The "How to Cite" text has been amended to list the areas of a resource that are not editable after publishing
> Fix text related to resource publishing

- Dockerfile
Bandaid resolves #4587 
Deepdiff upgraded on 4/10/22
https://github.com/seperman/deepdiff/commit/9c4dade2deae01307f4fd4ecf8a917d7fdbc5375
That breaks something in our build
Example:
http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/5137/console
Pinning at `deepdiff==1.7.0` resolves the issue for now...
> pin deepdiff

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/views/utils.py
1. Create a composite resource. 
2. Add a text (e.g., test.txt) file. Make the file as a single file aggregation. 
3. Create a folder (e.g., test) with the same name as the file you uploaded. 
4. Delete the folder.  Verify the single file aggregation and the file you uploaded did not get deleted.
> 4588-Fix for folder delete

- theme/static/css/apps_page.css
HOTFIX for issue in rc-1.55
HOSTNAME/apps no longer has a blank tile at the start and end of the app container
> bootstrap clearfix for apps grid

- .github/RELEASE_CHECKLIST_TEMPLATE.md
> add reminder to catch breaking db migration

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
- theme/static/js/resourceLandingAjax.js
Resolves #4065 
1. Upload a bunch of small files to a resource
2. Delete a handful of them
3. Note that you can still interact with the page and the deletion is done asynchronously
> async delete files [#4065]

- hs_core/hydroshare/resource.py
1. Non-production environments skip publishing and only place the resource in a pending state.  You can manually trigger a call to test.crossref.org in the shell.  You'll have to pass the resource object to this function.  https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/resource.py#L981
2. If a 200 status code is returned, then it worked.
> [#4620] - turn off crossref ssl verify

- hs_core/hydroshare/utils.py
- hs_core/models.py
- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- theme/static/js/hs-vue/left-header-app.js
- theme/templates/resource-landing-page/resource-header.html
This PR fixes a regression introduced in PR #4576 
2. Add an author to a resource who is not a hydroshare user
3. Reload the page -- no longer get a template error on page reload
All of the tests in PR #4576 still hold true
> fix is_active template filter [#3077][#3429]

- hs_core/tasks.py
> Turn off SSL verification for pending resources

- hs_core/management/commands/fix_missing_license_statement.py
- hs_core/migrations/0062_auto_20220520_1449.py
> 4611-Comand for fixing license metadata to account for missing license(rights) metadata

- Dockerfile
> [#3429] - use 0.5.0 tag of hsmodels

- hs_core/migrations/0061_auto_20220404_1415.py
> [#3429] - account for empty user ids in description

- theme/templates/includes/big_image_button_app.html
- theme/templates/pages/dashboard.html
Will eventually fix #4659 
1. Navigate to /apps/ and scroll down to "Featured Apps" section. See that it is now a single row
> [#4659] single row for featured apps

- hs_collection_resource/templates/pages/collectionresource.html
- theme/static/js/collection-resource.js
- theme/static/js/hs_file_browser.js
1. Create couple of composite resource.
2. Create a collection resource and add one or more resources to the collection.
3. Download the bag zip file the collection resource. Verify that bag download happens without redirect to a different page.
> 4650-Fix for collection resource bag download

- hs_communities/templates/hs_communities/find-communities.html
- hs_communities/templates/hs_communities/my-communities.html
- hs_core/templates/pages/collaborate.html
- hs_core/templates/pages/groups-authenticated.html
- hs_core/templates/pages/groups-unauthenticated.html
- hs_core/templates/pages/my-groups.html
- hs_core/views/__init__.py
- hydroshare/settings.py
- theme/templates/includes/navbar.html
- theme/templates/pages/group-unauthenticated.html
- theme/templates/pages/group.html
- black backgrounds in some thumbnail images due to PIL conversion between formats
- error on Mezzanine admin page due to (as yet undetermined) issue with manifest collectstatic
- template error preventing Collaborate page from loading
> 1.56 collectstatic hotfix

- hs_core/models.py
- hs_core/templates/pages/my-resources.html
- hs_core/templatetags/hydroshare_tags.py
- hs_core/views/utils.py
- theme/templates/accounts/profile.html
- theme/views.py
1. Checkout develop branch and run hydroshare.
2. Create 200 composite resources (use a management command or run commands in Django shell for this)
3. Load the my resources page and keep a note of the page load time.
4. Checkout branch 4091-my-resources-performance.
5. Reload the my resources page. Verify that the page load time is less (by about 30%) compared to what you noted in step 3.
6. You can also verify the page load time improvement (slight improvement) for the profile page.
> 4091 My resources performance improvements

- hs_core/templates/pages/genericresource.html
**NOTE**: This a fix for a regression bug and needs to go in release 1.57.
1. Create a Web App Connector.
2. Verify that you can see the section "Resource Specific'  in editing mode of the web app connector. Verify that you can edit metadata such as 'Supported Resource Types' or other web app connector specific metadata.
> 4690 Show UI elements for resource specific metadata editing

- theme/static/js/hs-vue/left-header-app.js
Resolves #4699 
2. Add a non-hs author (no linked HS account) to the resource
3. Use drag/drop to change the order of authors
4. Exit "edit" mode and click on the original author link in the left-header area of the resource landing page
5. The links to the HS profile for the original author will be present and point to the correct user profile
> [#4699] author profile links

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/highlights.html
- theme/templates/resource-landing-page/resource-header.html
- theme/templates/resource-landing-page/title-section.html
#4604
1. Go to the resource landing page
2. Observe new icons added next to various elements on the page.
3. Hovering over the icons shows a tooltip.
4. Clicking the icons opens the relevant video in a new tab.
> [#4604] Embed icons of youtube videos on resource landing page

- theme/templates/includes/navbar.html
Resolves #4721 
1. Try to create a new user
2. You will see the normal list of countries during user creation
> [#4721] remove unneeded template tag

- hs_composite_resource/models.py
- hs_core/models.py
- hs_core/views/resource_folder_hierarchy.py
- hs_file_types/models/base.py
- hs_file_types/models/base_model_program_instance.py
- hs_file_types/models/fileset.py
- hs_file_types/views.py
1. The performance improvements can be tested by creating a large number of folders (something like 50 folders) in a resource and checking the page load time for that resource.
> 4711-Improve aggregation lookup

- hs_tracking/views.py
- theme/static/js/hs-vue/relevant-tools.js
1. Use Chrome browser for this testing. However, the bug that this work fixes is not browser specific. Chrome will allow you to see the raw url that it receives. Browser like Firefox, decodes url when it receives it (at least for me on Windows). 
2. Create resource. In that resource create a folder with name "fileset folder". Note the folder name needs to have a space. Upload a file to that folder. Make that folder a fileset aggregation.
3. Create a Web App Connector (name the app as 'Test Web App'). Edit the metadata for the web app to associate it with fileset aggregation. For app aggregation url, enter (Note the domain name is not a real domain name - we are interested to see how hydroshare generates this url to open the app): 
https://mywebapp.org/${HS_RES_ID}/${HS_AGG_PATH}
4. Save …
> 4693 Web App Connector URL Pattern url encoding

- hs_core/templates/pages/genericresource.html
> 4709 schema org update

- hs_core/models.py
> [#4753] readme file fix

- hs_core/views/utils.py
> fixed unzip bug when files and folders have the same name for overriding

- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/modals.html
1. Create a resource. Upload a file.
2. Enable 'Require agreement to rights statement before downloading'
3. Try to download the file. This should display the Resource License Agreement modal. Click the link displayed on this modal. Verify that the license link opens in a new browser tab. 
4. Try to download the resource bag and verify same as step as 3 above.
> [#4146] open license agreement url in a new tab

- hs_core/models.py
> fixed the bag unzip content empty issue

- .github/RELEASE_CHECKLIST_TEMPLATE.md
> update release checklist

- hs_file_types/forms.py
1. Create a resource. Create a raster aggregation.
2. Edit metadata for the raster aggregation.
3. Verify in the log there are no raster form related errors.
> [#4763] Raster aggregation spatial coverage form fix

- hs_core/testing.py
> added test cases to cover file/folder overwriting cases when unzipping

- hs_access_control/models/user.py
- hs_access_control/tests/test_group_membership_request.py
> Merge 1.58.1 into Master

- theme/static/js/hs_resource_table.js
- theme/templates/base.html
Resolves #4773 
1. Open any Group page and note that the URL params are no longer appended
> [#4773] URL query params only on My Resources page

- hs_core/admin.py
> [#4794] - disable admin ability to change usernames

- hs_collection_resource/templates/pages/collectionresource.html
- hs_core/templates/pages/genericresource.html
- theme/static/css/notifications-app.css
- theme/static/js/generic-resource.js
- theme/static/js/hs_file_browser.js
- theme/static/js/modals.js
- theme/templates/includes/navbar.html
- theme/templates/resource-landing-page/modals.html
Resolves #4665 
1. Create a resource with some files
2. Check the "Require agreement to rights..." checkbox
3. In the file browser, select the "Download all content as zipped bagit..."
4. The modal will show and the download will not start before acceptance
5. This is also true for collection resources
> [#4665] wait for rights agreement before zipped download

- hs_core/management/commands/update_party_model_active_user.py
1. Run the management command` update_party_model_active_user` on beta.
2. Verify the command runs without any errors.
> fix for management command that updates party objects

- hs_core/migrations/0065_auto_20221004_1707.py
> Zdt for 1.60 sql

- hs_core/tasks.py
- hydroshare/local_settings.cutover
- hydroshare/local_settings.template
In conjunction with https://github.com/hydroshare/hs-deployment/commit/a81aae94fd32d8939e1dd42c568cc3f44726239e, Resolves #4802 
I've updated our Jenkins Job on beta swap so that we can test this
https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Beta%20deployment/job/beta-swap-worker/configure
> [#4802] check for periodic tasks = disabled

- hs_core/management/commands/reorder_authors.py
- hs_core/tests/api/native/test_reorder_authors_management_command.py
> [#4818] update author reordering mng command

- hs_core/templatetags/hydroshare_tags.py
- hs_core/views/__init__.py
> 4795 improve logging for published resources missing dates

- hs_core/management/commands/update_party_model_active_user.py
- hs_core/migrations/0065_auto_20221004_1707.py
- theme/templates/resource-landing-page/geoconnex.html
> 1.60.1 into django 3.2 branch

- hs_core/templates/pages/genericresource.html
Resolves #4837 
(a regression in Develop as of 4cdc2d6e1979e525842d753a3125feaf7741af15)
1. Create web app connector
2. See the "Resource Specific" section shows with all inputs
> [#4837] fix webapp connector template

- hs_core/views/utils.py
- theme/templates/includes/my-resources-trows.html
1. Create a resource. Edit some metadata for the resource. Verify the last updated date/time is different from the created timestamp.
2. Go to my resources page. Verify the last modified date/time for the resource matches with the last updated shown in the landing page of that resource.
> 4815 resource modified date in my resources page

- hs_core/templates/pages/genericresource.html
- theme/static/js/hs-vue/geoconnex.js
Resolves #4820 
(I was only able to reproduce #4820 use recent version of Chrome)
1. Add a related geospatial feature somewhere in the US
2. Add resource level spatial coverage on a different continent
3. Reload the resource page
4. In Edit mode, the Geoconnex map will show _BOTH_ the spatial coverage and the related item
5. In View mode, the Geoconnex map will show _ONLY_ the related item
> 4820 zoom on geoconnex map when spatial extent is distant from related features

- hs_discover/babel.config.js
- hs_discover/package-lock.json
- hs_discover/package.json
Resolves #4842 
1. `npm audit` no longer shows any 'high' or 'critical' security issues
> [#4842] discover: js security

- theme/static/css/hydroshare_core.css
- theme/static/js/custom.js
- theme/static/js/profile.js
- theme/templates/accounts/profile.html
Resolves #3364 
1. Add multiple organizations to your HS user profile
2. Go to "view" mode and see improved styling
> [#3364] display of multiple orgs

- theme/views.py
Resolves #4854 
1. Navigate to the Home Page
2. Click "Complete Profile"
3. Takes you to your user profile
> [#4854] fix "complete profile" link

- hs_core/tests/api/rest/test_resource_science_meta.py
- hs_tools_resource/tests/test_web_app.py
- hsctl
- irods_browser_app/static/js/irods.js
> [#4857] fix static path

- theme/static/js/hs-vue/geoconnex.js
- theme/templates/resource-landing-page/geoconnex.html
> 4830 use jsonld to map geoconnex names

- hs_core/models.py
1. Create a resource. Create a folder with a space in folder name. Upload a file to the folder. Rename the file to have a space in the filename.
2. Right click on the folder and select 'Get File URL' option. Verify the folder url is property encoded. Copy the url and use it to download the folder. Verify the folder download was successful. 
3. Right click on the file and select 'Get File URL' option. Verify the file url is properly encoded. Copy the file url and use it to download the file. Verify the download of the file was successful.
> 3024 encoding url path for file and folder

- theme/static/js/profile.js
- theme/templates/accounts/profile.html
- theme/views.py
Resolves #3098 
To be honest, I don't really have a good way to test this locally.
To test on beta:
1. Using an account that you don't mind FUBARing, use `iadmin mkuser $1 rodsuser` to create an account where $1 is the hs username
2. Now using the HS Profile page, attempt to create an iRods account -- it will fail with an improved message.
3. With a new user account on HS, use the Profile page to successfully create an iRods account
4. `iadmin rmuser $1` using the second username
5. Now using the HS Profile page, attempt to delete the iRods account -- it will fail with an improved message
> [#3098] iRods acct create/del messaging

- hs_core/hydroshare/resource.py
- hs_core/models.py
- hs_core/router.py
- hs_core/tasks.py
- hs_core/views/__init__.py
- theme/static/js/generic-resource.js
Resolves #4863 
This PR contains updates/modifications to the HIL workflow as discussed on 11/28/2022
This PR must be merged before 2.1 release
1. Create a public resource
1. Attempt publishing the res in each of the following cases; it will result in a message requesting metadata edits:
- less than 3 keywords
- Abstract is > 150 chars
- Title is > 30char
2. Double-clicking on publication submit button is no longer possible--the button is deactivated (w spinner) on click
3. Celery job checking publication status runs hourly instead of daily
4. Wording on final confirmation email has been updated and URLs render correctly now
7. Attempt publication with `DEFAULT_FROM_EMAIL` in your settings, but with no HS user associated with that account. Matching user is generated
8. Approve a …
> 4863 Human in the Loop improvements

- hs_core/tests/api/native/test_core_metadata.py
- theme/templates/resource-landing-page/references.html
Resolves #4861 
1. Navigate to a resource landing page
2. See that the text for the "Relations" section has been updated
> [#4861] remove isDataFor from relations text

- hs_core/views/__init__.py
Resolves #4793 
1. Go to <hostname>/hsapi
2. Click on /userDetails/{user_identiier}/
3. See that user_identifier can be a string
4. Enter an email or username for a current user
5. See the expected json returns
> [#4793] userDetails endpoint accept usernames/emails

- hs_core/hydroshare/resource.py
- hs_core/tasks.py
1. Change the email that will be used for HIL review
> [#4871] update reviewer email for HIL

- hs_core/models.py
- hs_file_types/models/base.py
- hs_tools_resource/models.py
1. Create a web app connector
2. Refresh the page
3. No longer see an error
> Human in the Loop: Web App Connector metadata fix

- hs_core/templates/pages/genericresource.html
Resolves #4894 
1. In a public resource, create an aggregation
2. Request publication for the resource (start the HIL metadata review)
3. In edit mode, you can no longer add metadata or add/remove aggregations
> [#4894] prevent aggregation edit during review

- hs_core/models.py
Resolves #4897 
1. Create a tool resource
2. No longer see recommendation to include readme
> [#4897] dont recommend readme on Tools Resource

- hs_core/models.py
1. Create a composite resource with title 'R-v0'. Make this resource discoverable by editing required metadata and uploading a file. Once this resource is set to discoverable, use the DISCOVER option to verify that this resource is listed in discover. 
2. Create a new version of the above resource. Change the title of the resource to 'R-v1'. Verify that 'R-v0' is the only one resource listed in discover. Make 'R-v1' resource discoverable or public. Verify that 'R-v1' is the only resource listed in discover. Make resource 'R-v1' private. Verify 'R-v0' is the only resource listed in discover. 
3. Create a new version from 'R-v1'. Change the title of this new version to 'R-v2'. Make 'R-v2' to public or discoverable. Verify 'R-v2' is the only resource listed in discover. Make 'R-v1' …
> [#3936] resource version fix for discover/index

- hs_core/views/utils.py
1. Create a resource. Upload a zip file (e.g., test.zip). Create a folder with the same name as the zip file name (test). Upload any file to the folder. Verify when you try to zip the folder (test), the zipping fails and you seen an error message. Try to zip the folder providing a different name for the zip file. Zipping should be successful.
> 4896-Prevent overwriting existing zip file

- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/models.py
- hs_tools_resource/models.py
1. With this code changes it should take less time to create a resource. However, it may not be easy to test that very accurately. The other way to verify is that it now takes about 50 minutes less to run all the tests which is due to less time for creating a resource (http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/5987/testReport/) .
> 4923-optimize resource create

- hs_tracking/models.py
Resolves #4916 
2. Note that there are no longer a bunch of timezone warnings
> [#4916] make session timezone aware

- hs_core/hydro_realtime_signal_processor.py
- hs_core/tests/api/native/test_delete_resource.py
- hydroshare/settings.py
1. By disabling solr indexing during tests, it seems tests are running about 15 minutes faster.
> 4925-speedup tests

- theme/static/js/hs-vue/geoconnex.js
Resolves #4876 
1. On a resource, add box coverage
2. Attempt to add a Related Feature from the "Mainstems" collection
3. No longer see error, instead it populates either "No items found" or shows the mainstems in the query.
> [#4876] fix mainstem name parse for Geoconnex

- hs_core/page_processors.py
- hs_core/templates/debug/debug_resource.html
- hs_core/views/debug_resource_view.py
- theme/templates/resource-landing-page/title-section.html
> [#4947] no checking of file/folder names on resource page load

- hs_core/debug_urls.py
- hs_core/page_processors.py
- hs_core/tasks.py
- hs_core/templates/debug/debug_resource.html
- hs_core/urls.py
- hs_core/views/__init__.py
- hs_core/views/debug_resource_view.py
- theme/static/js/non_preferred_paths_in_resource.js
- theme/templates/resource-landing-page/title-section.html
1.Create a resource. Add a folder - use folder name with at least one space (e.g. "my folder"). Upload a file and then rename the file to contain a space in file name. Upload another file.  Refresh the resource page. You should see the following message:
`This resource contains some files/folders that have non-preferred characters in their name. Show non-conforming files/folders.`
Click the link `Show non-conforming files/folders`. You should see one folder and a file listed. These are the files/folders that contain a space in their names. 
2. The main thing to test is that the checking of file/folder names for non-preferred characters don't cause timeout error if the resource has to many files/folders. This work has been deployed at cuahsi-dev-2.hydroshare.org if you want to test with …
> [#4951] async check file/folder name for non-preferred characters

- hs_file_types/forms.py
- hs_file_types/models/model_program.py
- theme/static/js/hs_file_browser.js
1. Create a resource. Create a folder. Upload a file to the folder. Create a model program aggregation from the folder. Edit the metadata for the model program aggregation to set a metadata schema.  Verify that you see a link for model  instance metadata schema help page. Click this link and verify it shows the help page for metadata schema. From the dropdown select one of the available schemas. Save the metadata. View the metadata schema. Copy the schema content. 
2. Use the copied schema content to create a new json file. Edit the schema to make it invalid json. Create another folder for the resource. Upload a file to this new folder. Make this folder a model program aggregation. Edit the metadata for this aggregation. For setting the metadata schema for the aggregation use the Browse …
> [#4328] model schema validation error message improvements

- hs_core/hydroshare/utils.py
- hs_core/models.py
Resolves #4956 
More explanation for these changes given on that issue^^^
> 2.2 HOTFIX -- [#4956] defusedxml only when ingesting

- hs_core/tasks.py
> [#4977] hotfix 2.3.1 limit repeat attempts for failed celery job

- hs_core/views/resource_access_api.py
> [#4989] - cast str privilege code to an int and update exception message

- hs_core/tasks.py
- hs_core/views/resource_access_api.py
> Master -> develop after 2.3.2 hotfix

- hs_rest_api2/tests/test_file_json_metadata.py
- hs_rest_api2/views/metadata.py
1. Unit tests cover the scenario
> [#5006] - block editing of published resources via hs_rest_api2

- hs_core/models.py
- hs_core/page_processors.py
> [#5015] Resource view_count fix

- theme/static/js/hs-vue/geoconnex.js
- theme/templates/resource-landing-page/geoconnex.html
> Rc 2.4.2 -> Master after 2.4.2 hotfix

- hs_collection_resource/templates/pages/collectable_resources_modal.html
- hs_collection_resource/templates/pages/collectionresource.html
- hs_collection_resource/utils.py
- hs_collection_resource/views.py
- theme/static/js/collection-resource.js
> [#5030] improve collectable resources queries/template

- hs_core/hydroshare/resource.py
- hs_core/views/utils.py
> Hotfix 2.5.1: publication requests go to support not admin

- theme/migrations/0023_alter_userprofile_subject_areas.py
1. `git checkout 2.5 && ./hsctl loaddb`
2. `git checkout develop && ./hsctl managepy migrate` <-- should give an error like:
```
django.db.utils.DataError: malformed array literal: ""
DETAIL:  Array value must start with "{" or dimension information.
```
3. `git checkout subject_area_migration_fix && ./hsctl managepy migrate` <-- should succeed without the error
> subj_areas migration handle EMPTY -> NULL

- django_irods/views.py
- hs_core/task_utils.py
Resolves #5045 
1. Create an aggregation in hydroshare.
2. Then use hsclient to download that aggregation. Try downloading the aggregation a dozen times and you should see the download works every time
> [#5045] get_stask_notification without create()

- hs_collection_resource/views.py
- irods/use-local-irods.sh
- local-dev.yml
1. Create couple of resources. Assing multiple users as owners of these resources. 
2. Create a collection resource. Access the modal to add resources to collection. Verify that duplicate resources are not listed in this modal.
> [#5059]-HOTFIX Filter out duplicate collectable resources

- hs_collection_resource/management/commands/fix_collection_version_missing_ispartof.py
- hs_collection_resource/views.py
- hs_core/tasks.py
- irods/use-local-irods.sh
- local-dev.yml
Resolves #5057
1. Create a collection
2. Add a resource to the collection
3. Create a new version of the collection
4. You can remove the resource from the new collection without error
> [#5057] remove resource from collection with multiple versions

- hs_collection_resource/management/commands/fix_collection_version_missing_ispartof.py
- hs_collection_resource/views.py
> [#5059] management command check hasPart

- theme/templates/resource-landing-page/citation.html
> [#5077] license edit for published resources

- hs_collection_resource/templates/pages/collectionresource.html
Resolves #5065 
1. Create a collection
2. See modified text on download button
> [#5065] collection download button

- theme/migrations/0023_alter_userprofile_subject_areas.py
Resolves #5022 by improving the migration of Subject Areas in the database.
Original migration in PR https://github.com/hydroshare/hydroshare/pull/5036 failed to account for odd strings that might be entered as Subject Areas.
This PR doesn't handle all possible cases, but I think it should do fine with all of the Subject Areas currently in our prod db.
1. Checkout 2.5.2 or similar previous release
2. Create a user profile with difficult to parse Subject Areas, something ike: "{ this , , will ,, fail{ to parse []}}}"
3. Checkout this branch
4. Run migrations
5. See that the migration succeeds and subject areas are parsed reasonably
> 5022 subject area migration improvement

- theme/templates/resource-landing-page/citation.html
> [#5113] fix youtube link for citation

- hs_rest_api/tests/http/test_discover.py
1. Verify tests are passing as part of PR build.
> [#5119] Unit test for discover search endpoint

- hs_core/views/resource_rest_api.py
> [#5122] fix for file list endpoint

- hs_core/views/resource_rest_api.py
> [#5122] file list endpoint - catch irods exception for missing file

- hs_core/hydroshare/hs_bagit.py
- hs_core/hydroshare/resource.py
- hs_core/models.py
- hs_core/views/utils.py
- hs_file_types/models/base.py
- hs_file_types/models/base_model_program_instance.py
- hs_file_types/models/model_instance.py
1. Create a resource. Upload couple of files to the root of the resource. 
2. Create a folder in the same resource. Upload few files to that folder. 
3. Create another folder and upload files to that folder. Make this folder a fileset aggregation.
4. Download the resource bag and verify the resourcemap.xml file correctly describes the files and folders of the resource.
5. Delete the folder that you created in step 2. Verify the folder and the files in that folder got deleted.
6. Download the resource bag and verify the resourcemap.xml file correctly describes the files and folders of the resource.
7. Delete the folder that you created in step 3. Verify the folder and the files in that folder got deleted.
8. Download the resource bag and verify the resourcemap.xml file correctly describes …
> [#5139] optimize remove folder

- hs_sitemap/sitemaps.py
- hs_sitemap/templates/sitemap.html
- hs_sitemap/urls.py
- hydroshare/settings.py
Resolves #5125 
1. Create 2 resources
2. Make one of the resources discoverable
3. Navigate to `http://localhost:8000/robots.txt` and check the `Sitemap:` property
4. Navigate to the URL listed in step 3 for the sitemap (should be like http://localhost:8000/sitemap.xml)
5. Navigate to the `-resources` <loc> -- it should be like http://localhost:8000/sitemap-resources.xml
6. Confirm `sitemap-resources.xml` shows the discoverable resource but not the private resource
> [#5125] remove private resources from sitemap

- theme/static/js/coverageMap.js
Resolves #5144 (at least partially, couldn't reproduce the first part of the issue with hidden delete)
1. Add box spatial coverage to a resource and save
2. reload the page
3. Toggle the UI to "point" coverage
4. See that the existing box coverage is hidden
5. Add a point dont save
6. Toggle back to "box" edit mode
7. See that the point is gone and your old box is shown
> [#5144] hide coverage when toggle box/point

- hs_core/hydroshare/utils.py
- hs_core/models.py
- hs_core/tasks.py
- hs_core/views/resource_folder_hierarchy.py
2. Upload few files to that resource.
3. Create different type of aggregations including fileset aggregation. 
4. Create a copy of the resource. Verify the new copied resource has all the files and aggregations as the original resource.
5. Create a version of the resource you created in step 1. Verify the new version of the resource has all the files and aggregations as the original resource.
6. You should be able to verify the performance improvement of creating a copy of a resource using the endpoint for resource copy using the following steps.
7. To see the performance improvement, the resource needs to have at least 20 files. So accordingly upload some more files to the new version of resource you created in step 5.
8. Navigate to **localhost:8000/hsapi/**
9. …
> [#5149] optimize creation of resource copy/version

- hs_tools_resource/app_launch_helper.py
- theme/static/js/hs-vue/relevant-tools.js
- theme/static/js/hs_file_browser.js
1. The purpose of the test is to verify that a web app is listed for open with functionality only where it should be available for open with. Since a web app can be configured to open at the resource level, aggregation level, and file level it is a bit of challenge to manually test all the web app configurations. 
2. Create a resource. 
3. Refer to the **Expected Behavior** section of the issue #5115 to create web apps with necessary configurations to test each expected behavior listed there. Note that we don't need to test if the web app actually works when the web app link is clicked.
> 5115-web app fixes

- hs_core/views/resource_rest_api.py
This is a rebased PR of https://github.com/hydroshare/hydroshare/pull/5176, in order to release as hotfix 2.8.1
> 5175 fix file list endpoint rebase

- hs_core/views/resource_folder_hierarchy.py
1. Create a resource. Upload some files to the root of the resource.
2. Verify the files are listed in resource landing page both in view and edit mode.
3. Create a folder. Upload some files to this folder.
4. Verify the files are listed in the resource landing page both in view and edit mode when you list contents of this folder.
5. In order to verify performance improvements in listing files in UI, upload at least 100 files. Note the load time for listing the files. 
6. Compare the performance with the develop branch.
> [#5168] optimize file listing for UI

- hs_core/models.py
- hs_core/views/utils.py
1. Create a resource. Create a folder. Upload 500 or so files (more files is better for testing) to that folder. However, upload only 100 files at a time as there is a separate issue to fix large number of file upload.
2. Rename the folder. Verify the folder rename was successful without any timeout error.
> [#5170] optimizing folder rename operation

- django_irods/views.py
- hs_core/signals.py
- hs_tracking/signals.py
Resolves #5171 
2. Add Files
3. Download the bagit
4. Run the stats management command `hsctl managepy stats --yesterdays-variables > test-log.txt`
5. Check that the log output contains the new variables (including `user_agent` , `doi`, and `resource_metadata`)
> [#5171] add aditional metrics for MakeDataCount

- hs_core/tasks.py
> [#5182] fixing the file selection query for nightly update task

- hs_core/views/resource_folder_hierarchy.py
> [#5168] using db query to list files for the UI

- django_irods/storage.py
> [#5182] strip chars from iquest size call

- theme/static/js/home-page.js
To be reverted once keycloak is released
> [#5157] add custom alert to homepage

- hs_core/tasks.py
1. Create a resource. Make a copy of that resource
2. Use the id of the copied resource to download the **resourcemap.xml** file using this url path: (**localhost:8000/resource/{res_id}/data/resourcemap.xml**)
3. Open the downloaded xml file and verify that the resource id in the file is the id of the copied resource for which you downloaded the file.
> [#5204] resource copy/version fix

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/models.py
> [#5126] optimizing search for readme file

- hs_core/management/commands/solr_update.py
> Update solr_update.py to delete indexes for deleted resources

- hs_core/hydro_realtime_signal_processor.py
- hs_core/views/__init__.py
- hs_rest_api/tests/http/test_discover_res_delete.py
Resolves #5217 
1. make a new user account
2. add a resource and make it discoverable
3. login as admin user and delete the account that you created in step 1 (via the mezzanine admin panel)
4. See that the resource listing does not persist on the Discover search page
> [#5217] update solr when resource deleted

- hs_core/management/commands/list_published_by_year.py
- hs_tracking/management/commands/stats.py
Resolves #5230 
Requires merge of https://github.com/hydroshare/docker-elk/pull/11 and release to metrics system
1. Publish a resource
2. Run `./hsctl managepy stats --resources-details` and ensure that the publication date is included
3. Run `./hsctl managepy list_published_by_year` and see that it prints out the published resource
> [#5230] publication dates management command

- theme/static/js/profile.js
- theme/templates/accounts/sign_up_form.html
Resolves #5226 
1. Open edit mode for profile
2. put text in "Subject areas"
3. Hit tab
4. Autocomplete item is added on blur
5. reopen the edit mode
6. put text in Subject areas
7. Click submit without tab/enter from the input
8. See that the input text is retained
> [#5226] subject areas autocomplete

- hs_core/management/commands/list_published_by_year.py
Resolves #5230 by adding more funder info to the management command
> [#5230] additional funding info for publications management command

- hs_composite_resource/models.py
- hs_core/models.py
- hs_core/views/utils.py
- hs_file_types/models/model_program.py
- hs_file_types/tests/test_fileset.py
- pytest/functional/hs_file_types/test_model_aggregation.py
- pytest/functional/hs_file_types/test_model_instance_aggregation.py
- pytest/functional/hs_file_types/test_model_program_aggregation.py
1. Create a resource. Create a fileset aggregation in that resource
2. Create a folder and upload a file to that folder.
3. Move the folder to the fileset aggregation/folder.
4. Navigate to the file inside the moved folder inside the fileset folder. Verify when you hoover mouse over the file, you see it shows '**File Set Content: One or more files with specific metadata**'
5. Create folder inside the fileset folder. Upload a file to that folder. Verify that the uploaded file becomes part of the fileset aggregation. 
6. Move the folder you created in step 5 out of the fileset aggregation to the root of the resource. 
7. Verify when you hoover mouse over the file inside the folder you moved in step 6, it doesn't show '**File Set Content: One or more files with specific metadata**'
> [#5201] folder move for aggregation fix

- hydroshare/local_settings.cutover
- hydroshare/local_settings.template
> Hotfix 2.10.3

- hs_core/tasks.py
> [#5265] query federation paths

- hs_core/management/commands/list_published_by_year.py
- local-dev.yml
1. Publish a resource and add some funding agencies
2. Run `./hsctl managepy list_published_by_year --year 2023 --csv`
3. See that the csv is generated listing the published resources
> Add ability to write publications report to csv

- Dockerfile
Builds using https://github.com/hydroshare/hs_docker_base/commit/0bc6b1d0f5c1658ff877c8b1a0b38394e9d57bf2
https://hub.docker.com/layers/hydroshare/hs_docker_base/0bc6b1d/images/sha256-275951b3fd5cc6a7e3beea3bdaebb3d0296a203639a8bbfbc300746b5ef041f8?context=explore
> update base image to use new hsmodels with pinned pydantic

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/admin.py
- hs_core/models.py
Rebase of https://github.com/hydroshare/hydroshare/pull/5276 intended for hotfix release as 2.11.2
> [#5275] allow res copy/version when user deleted

- hs_composite_resource/page_processors.py
- hs_composite_resource/tests/test_composite_resource.py
- hs_composite_resource/tests/views/test_aggregation_file_sync.py
- hs_composite_resource/urls.py
- hs_composite_resource/views.py
- theme/static/js/aggregation_files_to_sync.js
- theme/templates/resource-landing-page/title-section.html
1. Create a resource. Create a netcdf aggregation. 
2. Edit the metadata for the netcdf aggregation - add few new keywords. When you save the metadata changes, you should see an option to update netcdf file. Do not update the netcdf file.
3. Refresh the landing page of the resource. You should see a message "**This resource contains content types with files that need to be updated to match with metadata changes. Show content type files that need updating**." towards the top of the landing page. Click the link "**Show content type files that need updating**" to see the file paths of the files to be updated. Verify you see the name of the netcdf file you uploaded to create the netcdf aggregation.
4. Create a time series aggregation in the same resource. Edit the metadata of this aggregation …
> [#5236] Ajax call to get the list of aggregation files to update

- hs_core/management/commands/check_unknown_funder_names_published_resources.py
- hs_core/views/__init__.py
> Rc 2.12.2 -> develop after hotfix

- hs_core/management/commands/repair_resource.py
Resolves #5300 by improving exception handling in `repair_resource` management command. The command was previously stopping prematurely when any given resource repair raised an exception.
Preferred behavior is to continue repairing resources and log exceptions.
1. Create a resource and add some files
2. Use the database or shell to remove some of the files from django to put the resource in  a "broken" state
3. Publish the resource
4. Run the `repair_resource --published --admin` management command and see that the published resource can now be fixed by the management script
> [#5300] exception handling in repair_resource cmd

- hs_core/models.py
- hs_core/tests/api/native/test_publish_resource.py
1. For testing resource publication locally, make sure the local_settings.py file has this variable `USE_CROSSREF_TEST = True` and crossref login information set using these settings variables - `CROSSREF_LOGIN_ID` and `CROSSREF_LOGIN_PWD`. 
2. Create a resource. Make sure to set abstract and couple of funding agencies for the resource. Upload a file. Make the resource public. Then publish the resource.
3. Login as admin user. Access the landing page for the resource. Approve the resource for publication.
5. Log into crossref test site (**https://test.crossref.org/servlet/home**) and verify that the metadata for the resource has been submitted. Check the submitted metadata xml has the **publisher** element.
> [#5319] Adding publisher to Crossref meta deposit

- hs_core/management/commands/compute_bag_size_depending_on_last_update.py
Hoping might eventually fixes #5310 
> [#5310] add management command to calculate bag sizes for "stale" resources

- hs_core/tasks.py
> [#5326] Fix for missing updates to crossref deposit status

- hs_core/tasks.py
> [#5345] Fix for query parameter used in querying CrossRef deposit logs

- Dockerfile
> [#5382] downgrade Pillow for community/group photos

- hs_rest_api2/serializers.py
> fix for pydantic schema key error

- hs_core/forms.py
- hs_core/models.py
- hs_core/tests/api/native/test_clean_abstract.py
- hs_core/tests/api/native/test_core_metadata.py
- hs_core/tests/api/native/test_publish_resource.py
Resolves #5387
1. Create a resource and add an abstract containing carriage returns
2. Save the abstract metdata and see that it succeeds
> [#5387] Revise Clean abstract and validation

- theme/static/css/hydroshare_core.css
- theme/templates/pages/group.html
Resolves #5393
1. Create a new group with a long (>200char title and purpose)
2. Save the group and see that lines no longer break in the middle of words
> [#5393] Add word-break property to full-width class

- hs_core/tasks.py
> [#5406] Dont send publication notification during metadata update

- hs_rest_api2/metadata.py
- hs_rest_api2/serializers.py
1. Locally once you run this fix, navigate to access the OpenAPI documentation at localhost:8000/hsapi2 
2. Verify when you access the documentation for any of the endpoints listed, you don't see any errors.
> [#5391] Fix for OpenAPI version incompatibility

- hs_rest_api2/serializers.py
1. Navigate to `/hsapi2` Swagger documentation page.
2. Verify when you view documentation for GET and PUT for this endpoint: `/resource/{id}/json/ModelProgram/{aggregation_path}` there is no errors.
> [#5391] Fix for model program OpenApi documentation errors

- hydroshare/settings.py
> Modify the order of the DEFAULT_AUTHENTICATION_CLASSES

- hs_core/authentication.py
Resolves #5437 by logging and redirecting to the **signin page** (instead of the signup page), in the case of error.
> [#5437] Add logging to build_oidc_url function

- hs_core/authentication.py
- theme/backends.py
- theme/utils.py
> [#5447] Update authentication logic in hs_core/authentication.py

- hs_core/authentication.py
> [#5447] - fix basic auth return type to tuple

- django_irods/views.py
- hs_composite_resource/models.py
- hs_composite_resource/tests/test_composite_resource.py
- hs_core/models.py
- hs_file_types/enums.py
- hs_file_types/models/base.py
- hs_file_types/models/base_model_program_instance.py
- hs_file_types/tests/test_generic_metadata.py
- hs_file_types/tests/test_geofeature_metadata.py
- hs_file_types/tests/test_netcdf_metadata.py
- hs_file_types/tests/test_raster_metadata.py
- hs_file_types/tests/test_reftimeseries_metadata.py
- hs_file_types/tests/test_timeseries_metadata.py
- hs_file_types/tests/test_view_functions.py
1. Refer to issue #5473 to test.
> [#5473] Aggregation meta file download fix

- theme/static/js/hs-vue/funding-agency-app.js
- theme/templates/resource-landing-page/funding-agency.html
Resolves #5404 by limiting query to US funders
> [#5404] Update funding agency app to limit queries to United States

- theme/management/commands/dump_user_quota.py
PR fixes the issue that the management command fails to run when it encounters a user that is NOT ACTIVE.
Test run here:
https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Production-Deployment/job/prod-hsctl-command/360/console
> Update dump_user_quota.py to handle inactive users

- Dockerfile
- Dockerfile-multistage-node
```
RUN pip install google-cloud-pubsub==2.21.2
RUN pip install numpy==1.26.4
RUN pip install pandas==2.2.2
RUN pip install django-storages[google]==1.14.3
```
> Pin-dependencies

- hs_core/tasks.py
> Exclude recently repaired resources from nightly repair task

- hs_discover/public/index.html
> include discover map js

- .github/workflows/hydroshare-pull-requests.yml
- hs_core/hydroshare/hs_requests.py
- hs_core/tests/api/native/test_hs_requests.py
- hs_tools_resource/tests/test_web_app.py
> try publish results after tests

- .github/workflows/hydroshare-pull-requests.yml
> update gh actions versions

- Dockerfile
- Dockerfile-multistage-node
- Dockerfile-users-irods
- local-dev.yml
This updates hydroshare container to use 2.4.11 icommands (from 2.4.10)
It updates the local dev runs (as well as PR builds) to use irods server 2.4.11
And updates the multi-stage node build dockerfile (which is used for prod deployments) to use the 2.4.11 icommands as well.
Relies on https://github.com/hydroshare/hs_docker_base/pull/134
Relies on https://github.com/hydroshare/hs-irods/pull/8
Relies on https://github.com/hydroshare/hs-irods/pull/7
Resolves https://github.com/hydroshare/hydroshare/issues/5556
> Update to irods:4.2.11

- Dockerfile
- Dockerfile-multistage-node
- django_irods/storage.py
- hydroshare/settings.py
Resolves https://github.com/hydroshare/hydroshare/issues/5515
we added loggers to stdout in https://github.com/CUAHSI/platform-recipes/pull/23
but every log shows up as error level in GCP
so needed to use:
https://cloud.google.com/python/docs/reference/logging/latest/handlers-structured-log#google.cloud.logging_v2.handlers.structured_log.StructuredLogHandler
This PR implements the StructuredLogHandler
> add ability to use google cloud logging format

- theme/static/js/profile.js
- theme/templates/accounts/profile.html
> [#5579] remove ability to request irods userzone account

- hsctl
- hydroshare/local_settings.cutover
- hydroshare/local_settings.template
Resolves #5558
And in helm https://github.com/CUAHSI/platform-recipes/pull/32
> [#5558] Update database connection timeout setting and PostgreSQL configuration

- theme/static/js/hs-vue/manage-access-app.js
- theme/templates/resource-landing-page/modals.html
> Fix incomatibility between DAL and BS modals

- hs_communities/static/js/community.js
- hs_communities/templates/hs_communities/community-settings-add-owner.html
- hs_communities/templates/hs_communities/community-settings.html
- hs_communities/templates/hs_communities/community.html
- hs_communities/templates/hs_communities/my-communities.html
- hs_core/templates/pages/my-groups.html
- hs_core/views/__init__.py
- theme/static/js/group-actions.js
- theme/static/js/hs-vue/left-header-app.js
- theme/static/js/resourceLandingAjax.js
- theme/templates/base.html
- theme/templates/pages/group.html
> additional DAL fixes

- hs_core/hydroshare/resource.py
- theme/templates/resource-landing-page/resource-header.html
Steps:
Create a Resource: Create a new resource (not yet published).
Check Before Publication: Verify ***last_updated*** is set, and no ***published_date*** exists.
Publish Resource: Publish the resource.
Expected: last_updated equals ***published_date***. No red "(Metadata update)" flag.
Modify After Publication: Edit the resource metadata (e.g., change the title).
Expected: last_updated changes, and the red "(Metadata update)" flag appears.
Postconditions:
No metadata update flag immediately after publishing.
Metadata update flag appears only after post-publication modifications.
> Added Published Date and Meta Data Update in Last Updated

- hs_core/views/resource_folder_hierarchy.py
i haven't tried this outside of S3 because my machine can't run the irods container (apple silicon). It should work regardless.
> detect unreferenced files and ingest on directory listing

- theme/static/css/hydroshare_core.css
- theme/static/js/hs-vue/funding-agency-app.js
- theme/templates/generic/includes/comment.html
- theme/templates/resource-landing-page/funding-agency.html
> Non-Confirming Funders Notification and Delete Styling issues

- Dockerfile
- Dockerfile-multistage-node
> Downgrade Bleach

- theme/static/js/hs-vue/funding-agency-app.js
> Duplication issue in funding agency

- theme/templates/resource-landing-page/resource-header.html
> Updated the published date content

- hs_core/tasks.py
- theme/templates/includes/navbar.html
> [#5648] Update task notification cleanup frequency and adjust notification check delay

- hydroshare/settings.py
> add file based cache and disable cache middleware

- hs_core/models.py
- hs_core/static/js/hs_uppy.mjs
- hs_core/templates/uppy.html
- hydroshare/settings.py
> feat: add max number of files limit for local uploads in Uppy

- theme/static/js/hs_file_browser.js
> Show hint for file and folder on hover

- hs_core/tests/api/native/test_publish_resource.py
> [#5666] fix funder doi in XML tests

- hydroshare/urls.py
> [#5654] change path to re_path for robots.txt URL

- hs_core/static/js/hs_uppy.mjs
> fix: allow reassignment of RESTRICTED_SIZE based on remaining quota

- hs_core/models.py
- hs_core/tests/api/native/test_publish_resource.py
> Updated funder registry to ror from crossref

- hs_core/templates/pages/baseresource.html
> update YouTube link for file upload in baseresource template

- .github/RELEASE_CHECKLIST_TEMPLATE.md
In conjuction with https://github.com/CUAHSI/platform-recipes/pull/72
> Delay automatic collectstatic

- hs_core/hydroshare/resource.py
- hs_core/management/utils.py
- hs_core/tasks.py
- hs_core/views/__init__.py
- hs_core/views/utils.py
- hs_sitemap/sitemaps.py
- theme/models.py
> Flakey-flake8

- hs_core/hydroshare/resource.py
- hs_core/management/utils.py
- hs_core/tasks.py
- hs_core/views/__init__.py
- hs_core/views/utils.py
- hs_discover/views.py
- hs_sitemap/sitemaps.py
- theme/models.py
> Filter query added to remove older versions in discover page

- hs_core/management/commands/crossref_to_ror.py
- hs_core/models.py
- hs_core/tests/api/native/test_publish_resource.py
- hs_discover/views.py
- theme/static/js/hs-vue/funding-agency-app.js
- theme/static/js/hs_file_browser.js
- theme/templates/resource-landing-page/funding-agency.html
Reverts hydroshare/hydroshare#5719
> Revert "Partial Revert of rc2.15.11"

- .github/ISSUE_TEMPLATE/release_checklist.md
~- [ ] Positive Test Case Written by Dev~
> replace release checklist template with a new issue template for better tracking of release tasks

- hs_core/static/js/hs_uppy.mjs
Resolves #5721
2. Drag and drop files into the file browser
3. See that uppy starts uploading the files immediately instead of waiting for confirmation in the modal
> [#5721] enable autoProceed option in Uppy configuration

- .github/workflows/lifecycle-policy-sync.yml
- .github/workflows/thredds-sync.yml
> add cron schedule to thredds and lifecycle policy jobs

- .github/workflows/lifecycle-policy-sync.yml
> set MinIO alias for lifecycle policy sync workflow

- .github/workflows/hydroshare-resouce-to-beta.yml
- .github/workflows/thredds-sync.yml
Resolves #5755
1. Run the actions and see that they succeeds
> S3-related-actions

- .github/workflows/thredds-sync.yml
> remove environment variable setup for MinIO in THREDDS sync workflow

- hs_core/models.py
>  [#5758] Only create a license node if there is a rights URL

- django_irods/storage.py
- django_irods/views.py
- hydroshare/local_settings.template
- hydroshare/settings.py
- local-dev.yml
- nginx/nginx-local-dev.conf
> 5748-minio-content-disposition-header

- hs_core/middleware.py
- hydroshare/settings.py
Resolves #5765
1. Spin up hsclient locally, using a version <1.1.5
2. Spin up this PR locally
3. Make requests from hsclient against your local version of HS
4. See that the responses are 400
5. Checkout hsclient v 1.1.5 locally
6. Make requests against HS (this PR) locally
7. See requests come back 200
> add HSClientMiddleware to enforce minimum hsclient version requirement

- hs_core/middleware.py
> fix: improve user-agent version extraction in HSClientMiddleware

- .github/workflows/hydroshare-resouce-to-beta.yml
> fix: correct BETA_ALIAS_STRING to use MINIO_BETA_ACCESS_KEY in workflow

- hs_core/task_utils.py
> setting task status to aborted while task is revoked

- theme/forms.py
> User unable to update/edit details on Profile Page

- .github/workflows/docs-gh-pages.yml
- docs/contributing.md
- docs/devcommunication.md
- docs/devenv.md
- docs/hs_composite_resource/models.md
- docs/hs_composite_resource/views.md
- docs/hs_core/models.md
- docs/hs_core/views.md
- docs/index.md
- docs/testing.md
- mkdocs.yml
- requirements-mkdocs.txt
> [#5728] Documentation

- django_irods/storage.py
- django_irods/utils.py
- hs_core/tests/api/rest/test_folders.py
- hs_core/views/utils.py
Resolves https://github.com/hydroshare/hydroshare/issues/5780
Resolves https://github.com/hydroshare/hydroshare/issues/5774
Resolves https://github.com/hydroshare/hydroshare/issues/5783
> 5780 folder listing v2

- django_irods/storage.py
fixes #5779 
1. Download a resource bag with a sum of the resource files size that is greater than 2GB
> support zipping files larger than 2GB

- hs_core/tests/test_update_quota_usage.py
> fix: update zip file size in quota usage test

- Dockerfile
- django_irods/storage.py
- hs_core/tests/test_update_quota_usage.py
Here is an actual implementation of stream zipping. The previous implementation was constrained by available memory. I did a local run bagging a 10 GB resource. Deploying to beta for more thorough testing.
> implement stream zipping without memory constraints

- Dockerfile-multistage-node
> Update Dockerfile-multistage-node to include smart_open[s3]

- .github/workflows/hydroshare-resouce-to-beta.yml
- Dockerfile
- Dockerfile-multistage-node
- django_irods/storage.py
- hs_composite_resource/tests/test_composite_resource.py
- hs_core/static/js/hs_uppy.mjs
- hs_core/templates/uppy.html
- hs_core/testing.py
- hs_core/tests/api/native/test_utils.py
- hs_core/tests/test_update_quota_usage.py
- hs_file_types/models/geofeature.py
- hs_file_types/nc_functions/nc_meta.py
- hs_file_types/raster_meta_extract.py
- hs_file_types/tests/test_fileset.py
- hs_file_types/tests/test_raster_metadata.py
- hs_file_types/tests/utils.py
- local-dev.yml
- pytest/functional/hs_file_types/test_model_instance_aggregation.py
> OAMS_TRADITIONAL_GIS_ORDER

- django_irods/storage.py
Rebased off the 3.0.5 tag instead of develop
> Hotfix 3.0.6

- django_irods/storage.py
> [#5823] - use updated path in whole listdir method

- Dockerfile
- Dockerfile-multistage-node
Requires https://github.com/hydroshare/hs_docker_base/pull/150
Contains these upgrades: https://github.com/hydroshare/hs_docker_base/pull/150/files
Related to these warnings: https://github.com/hydroshare/hs_docker_base/security/dependabot
> Security-updates

- Dockerfile
- Dockerfile-multistage-node
resolves #5853 by downgrading Pillow
Requires https://github.com/hydroshare/hs_docker_base/pull/152
> [#5853] Fix image thumbnail creation

- theme/forms.py
- theme/models.py
> [#5854] Fix bucket naming in UserProfileForm

- hs_composite_resource/models.py
- hs_composite_resource/tests/test_composite_resource.py
Instead of https://github.com/hydroshare/hydroshare/pull/5837
Resolves a regression introduced in https://github.com/hydroshare/hydroshare/pull/5732
> Fix logical file type name check in CompositeResource model

- theme/templates/includes/legend.html
Resized the CSV icon in Discover legend 
Before Code Changes:
After Code changes:
> [#5709] - resized CSV icon in Discover legend

- Dockerfile
- Dockerfile-multistage-node
https://github.com/hydroshare/hs_docker_base/compare/599fc4c...600ab11
1. The effective positive test case for this PR is all unit tests passing: https://github.com/hydroshare/hydroshare/runs/39401391101
2. Additional QA will be recommended before release
> Update Docker base image for security on DRF and Gunicorn

- theme/models.py
> revert: simplify user profile bucket name assignment condition

- hs_core/templates/pages/find-groups.html
- hs_core/views/__init__.py
> [#5868] - remove membership information from find groups page

- hydroshare/urls.py
> Support django_irods urls for backwards compatibility

- hs_tracking/management/commands/stats.py
Resolves #5835
https://develop.cuahsi.io/hydroshare/get_publication_stats/
> [#5835] add stats commands for publications

- hydroshare/settings.py
> move some settings so they can be overriden by local_settings

- hs_core/tasks.py
- hs_tracking/management/commands/truncate_variables.py
- theme/views.py
1. Check beta.hydroshare.org to see page load speed increase.
> 5848 truncate variables

- hs_core/tasks.py
- hydroshare/settings.py
> add periodic task to clear expired tokens from the database

- hydroshare/settings.py
> fix: update COMPANION_URL to remove trailing slash

- Dockerfile
- Dockerfile-multistage-node
> upgrade setuptools and celery

- hs_file_types/raster_meta_extract.py
> fix: update GetStatistics call in get_band_info to include no data handling

- hs_file_types/urls.py
> [#5931] Fix for internal url paths

- hs_core/hydroshare/hs_bagit.py
- hs_core/hydroshare/resource.py
- hs_core/models.py
- hs_core/resourcemap_urls.py
- hs_core/tests/api/views/test_aggregation_zip_download.py
- hs_core/views/__init__.py
> 5927 folder agg download 3.3.1

- django_s3/s3_backend.py
- local-dev.yml
fixes #5946
fixes #5783
1. This is difficult to test and currently only possible on beta and production because of a combination of the number of files and the ilm configuration of the minio server. I was able to reproduce the issue on beta before deploying this patch to beta.
2. pull up a shell in hydroshare container
3. copy a file into a folder in your test resource e.g. `mc cp LICENSE.txt hydroshare/sblack/d03ccfed09e847adb29afa32b0ec3264/data/contents/very/nested/folder/in/here/LICENSE.txt`
4. Delete the folder through the HydroShare UI
5. Observe the folder is no longer listed
> [#5946] - check for common prefixes with files marked for deletion

- django_s3/storage.py
- hs_core/tasks.py
- hs_core/views/utils.py
fixes #5964
1. Download a folder and/or an aggregation. Verify the download works.
> [#5964] - create zip without copy to temporary location

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/models.py
> [#6009] - handling missing file when calculating file size

- hs_core/hydroshare/resource.py
- hs_core/tests/api/native/test_publish_resource.py
> Create bag when publishing resource

- django_s3/tests/test_tus_upload.py
- django_s3/views.py
> [#6057] - check for published resource status in tus uploader

- hydroshare/local_settings.template
- local-dev.yml
- nginx/nginx-local-dev.conf
> Use Tus for resumable google drive uploads

- hs_core/models.py
- theme/static/css/hydroshare_core.css
Resolves #6065
1. Pull this PR
2. Create a resource
3. Upload a .md file with the table content mentioned in the issue: https://github.com/hydroshare/hydroshare/issues/6065#issue-3422725691
4. See that the table correctly renders in the readme preview
> [#6065] add support for tables in readme markdown rendering
