hydroshare/hydroshare

- hs_core/templates/pages/create-resource.html
- hs_geo_raster_resource/migrations/0001_initial.py
- hs_geo_raster_resource/models.py
- hs_geo_raster_resource/raster_meta_extract.py
- hs_geo_raster_resource/receivers.py
addressed issue #38 to improve raster resource type presentation. Should be a simple merge since the changes are pretty much isolated in raster resource type app.
> [#38] fixed

- hs_core/templates/pages/genericresource.html
- hs_geo_raster_resource/forms.py
- hs_geo_raster_resource/migrations/0001_initial.py
- hs_geo_raster_resource/models.py
Ready to be merged into develop - should be a low-risk, simple, and automatic merge.
> issues [#66] and [#39] fixed

- hs_core/views/__init__.py
- hs_geo_raster_resource/migrations/0001_initial.py
- hs_geo_raster_resource/migrations/0002_rastermetadata_bandcount.py
- hs_geo_raster_resource/migrations/0003_auto_20150123_2044.py
- hs_geo_raster_resource/migrations/0004_auto_20150126_1932.py
- hs_geo_raster_resource/models.py
- hs_geo_raster_resource/receivers.py
Completed the first step to convert raster resource type to use Pabitra's new metadata implementation on top of the old code base. The changes are isolated in raster resource type app and can be merged automatically into develop branch. After this gets merged into develop and after Pabitra's new resource creation workflow gets merged into develop also, it should be much easier to do the final integration to ensure raster resource type to work with the new resource creation workflow and metadata editing.
> 82 raster new metadata

- fig.yml
- hydroshare/urls.py
Add update to urls.py for email verification with dashes.
Update fig.yml to call init script instead of runserver by itself
> hotfix - update fig.yml and hyrdoshare/urls.py

- hs_core/views/__init__.py
Added logic to handle the special case for reference time series resource, which can be merged automatically.
> addressed issue [#107]

- hs_core/hydroshare/utils.py
- hs_core/views/__init__.py
Ready to be merged to develop branch.
> 116 fix multiple bags per resource

- hs_core/views/resource_api.py
> 118-ResourceFileCRUD-bug-fix done

- fig.yml
- hs_core/hydroshare/users.py
- hs_core/tests/api/native/test_get_resource_types.py
Modification to hs_core/hydroshare/users.py.
* Enable resources to be queried by type
* Added test case to verify that these changes are working properly
This feature is required in order to link the model program and model instance resources.
> 93 get resources by type

- hs_core/models.py
- hs_geo_raster_resource/models.py
Addresses #182.  Makes it much simpler for custom resource types to serialize metadata elements to XML.  @hyi should probably look at this as it builds on the new resource metadata model.
> Implemented helper method for serializing metadata elements to XML

- hs_core/forms.py
- hs_core/page_processors.py
> form related code cleanup in hs_core

- hs_app_timeseries/models.py
- hs_core/models.py
- hs_core/templates/pages/create-resource.html
- hs_core/templates/pages/genericresource.html
- hs_geo_raster_resource/models.py
> 232 hotfix-file type validation when adding a file

- hs_core/views/__init__.py
Just a one-line fixer. Can be merged automatically.
> fixed issue #241

- hs_core/hydroshare/hs_bagit.py
Based on the review on alpha I had to make more changes to resourcemap.xml document generation code. Please merge this.
> [#169] additional fixes to resourcemap.xml document

- hs_core/page_processors.py
> [#257] metadata migration code removed

- hs_core/templates/pages/genericresource.html
This has small JS code change.
> fix for bug#40

- hs_core/templates/pages/create-resource.html
- hs_tools_resource/admin.py
- hs_tools_resource/forms.py
- hs_tools_resource/migrations/0001_initial.py
- hs_tools_resource/migrations/0002_auto_20150324_0300.py
- hs_tools_resource/models.py
- hs_tools_resource/page_processors.py
- hs_tools_resource/receivers.py
- hs_tools_resource/templates/pages/toolresource.html
- hs_tools_resource/tests.py
- hs_tools_resource/tests/test_metadata_models.py
- hs_tools_resource/tests/test_metadata_views.py
- hs_tools_resource/urls.py
- hs_tools_resource/views.py
- hydroshare/settings.py
@mjstealey, this is the first cut of the tool resource. Not terribly useful yet, so I'm not sure if it should be deployed, but I would like to be able to demo it for the team so we all know where it's at...
> editing working, res types not, added unit tests

- hs_geo_raster_resource/raster_meta_extract.py
Sorry for the previous pull request created with a wrong base master. Closed that request and recreating this one to be merged into develop. Only one file changed, so should be a simple merge into develop to get bad tif file validation in for release 1.5.
> fixed [#307]

- docs/DesignDocs/API/index.md
Adds markdown-version of the API specification.  Addresses #250.
> 250 api documentation

- hs_app_netCDF/migrations/0003_auto_20150415_1751.py
- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- hs_model_program/migrations/0003_auto_20150415_1751.py
- hs_tools_resource/forms.py
- hs_tools_resource/models.py
- hs_tools_resource/page_processors.py
- ref_ts/views.py
This code is the first cut of adding relevant tools to the landing pages of the resources and is ready for testing on a tethys app for visualization of ref_ts resources
> 305 tool dev

- hs_core/page_processors.py
- hs_tools_resource/forms.py
- hs_tools_resource/models.py
- hs_tools_resource/page_processors.py
- ref_ts/views.py
These are some fixes described in #322
> little fixes described in issue 322

- hs_geo_raster_resource/migrations/0004_auto_20150505_1925.py
- hs_geo_raster_resource/models.py
Fixed issue #354 - increased max name length to be 500 to be consistent with hs_core file name length. Asking to be merged into release-candidate-1.5.0.
> fixed issue #354

- hs_core/hydroshare/users.py
- hs_core/urls.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
> 372 rest refactor phase2

- hs_swat_modelinstance/templates/pages/swatmodelinstanceresource.html
Fixed the bad page style for the SWAT Model Instance resource type [#388]
> [#388] fix SWAT MIR page style

- hs_geo_raster_resource/forms.py
- hs_geo_raster_resource/models.py
- hs_geo_raster_resource/page_processors.py
- hs_geo_raster_resource/templates/pages/rasterresource.html
Update the raster extended metadata forms based on the file from  https://my.alfresco.com/share/s/DeXkAhEgS8GjrgTWOSpp0w
> 324 raster metadata refine

- hs_core/templates/pages/my-resources.html
This fixes the white background on the 'Create New' button on My Resources page.
> [#387] Minor fix on button background

- hs_core/urls.py
- hs_core/views/pagination.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
> 381 rest api refactor phase3

- hs_core/hydroshare/hs_bagit.py
- hs_core/models.py
- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- hydroshare/irods/ruleGenerateBagIt_HS.r
- hydroshare/local_settings.py
Got the new bagit workflow working in my local development environment. Will coordinate with Michael to have it deployed to a VM server for team testing. In the meanwhile, create this pull request for code review to speed up the process to have it ready to be merged.
> 352 new bagit workflow

- hs_core/forms.py
- hs_core/hydroshare/utils.py
- hs_core/models.py
- hs_core/templates/pages/genericresource.html
- hs_core/templates/pages/my-resources.html
> 293 first author resource list

- hs_core/hydroshare/hs_bagit.py
This also fixes the duplicate creation date for the Aggregation element.
> fix for resource files not listed in resource map document

- hs_core/migrations/0001_initial.py
- hs_geo_raster_resource/migrations/0001_initial.py
- pg.development.sql
migrations and database updates for newly merged code.
> update migrations and development database

- hs_core/hydroshare/users.py
- hs_core/hydroshare/utils.py
- hs_core/templates/pages/my-resources.html
- hs_core/views/__init__.py
- hs_core/views/autocomplete.py
Abstract and Title are added to full text search.
Owner, Author, Contributor, and Subject are added to typed autocomplete mechanism.
> More Search Fields: Owner, Author, Contributor, Subject, Abstract

- Dockerfile
- Dockerfile.irods
- Dockerfile.local
Part of the fix to large file upload in conjunction with a django_irods merge pull request. My testing reveals upgrading to icommands 4.1 fixed large file uploading issue. Asking to be merged into develop.
> 419 irods icommand 41

- docker-compose.yml
- hs_core/models.py
- hs_core/page_processors.py
- hs_core/views/resource_api.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
- hydroshare/local_settings.py
@hyi Please review and test this code.
> Update bag URL generation to remove duplicate definition of URL scheme.

- hs_core/resourcemap_urls.py
- hs_core/views/__init__.py
- hydroshare/urls.py
@selimnairb or @hyi  Can you review?
> resourcemap url mapping

- hs_core/models.py
Fix the bug for required meta check for specific resource types
> [#432] required meta check

- hs_core/templates/pages/create-resource.html
Simple re-naming and re-ordering of available resources in create-resource.html
> [#436] update naming/order of resources

- hs_modelinstance/forms.py
- hs_modelinstance/models.py
- hs_modelinstance/receivers.py
Fixed issue #406 , modified the resourcemetadata.xml representation, and did some code refinement.
> 406 modelinstance refinement

- hs_model_program/templates/pages/modelprogramresource.html
- hs_model_program/views.py
- hs_modelinstance/forms.py
- hs_modelinstance/static/js/model_instance.js
- hs_modelinstance/templates/pages/modelinstanceresource.html
This is mostly a refinement of the model program and model instance relationship.  
1. Incorrect kwarg was being passed into hs_core causing **model program** lookup to fail
2. Some refinements of the javascript and html pages for both the model instance and model program resources
3. fixed datetime formatting issues.
> 440 program instance linking bug

- hs_core/templates/pages/genericresource.html
- hs_core/urls.py
- hs_core/views/__init__.py
> remove feature to add creators/contributors from users

- theme/static/css/hydroshare_core.css
[#448] Just a minor border style fix for search box on my resources.
> 448 search box border fix

- hs_core/templates/pages/genericresource.html
@pkdash, @mjstealey, could one of you test this change in your local environment? My machine crashed before I could test it and I'm having problems getting it back on?
> [WIP][#450] Removed Executed By option from list menu

- hs_model_program/forms.py
- hs_model_program/models.py
- hs_model_program/templates/pages/modelprogramresource.html
- hs_modelinstance/forms.py
- hs_modelinstance/models.py
- hs_modelinstance/templates/pages/modelinstanceresource.html
* fixed typo on model program landing page
* added a check for https in modelinstance.html to ensure the model program resource path is correct.
* removed class name **MpModelProgram** from model program edit page
* fixed issue that was preventing files from being uploaded after model program and model instance are created.
* Changed *Unknown* to *Unspecified* when selecting a program on the instance edit page.
* Displaying *Unspecified* for program on instance landing page, if no program has been selected.
> 444 program minor fixes

- hs_core/templates/pages/create-resource.html
- hs_core/templates/pages/help.html
- hs_modelinstance/models.py
Cosmetic updates pre-NFIE tagging
> update cosmetics for site prior to tagging

- hs_modelinstance/templates/pages/modelinstanceresource.html
Minor fix. The Model Instance landing page comment area should be available after this merge.
> [#469] Fix landing page style

- hs_core/page_processors.py
This commit only addresses issue #467
> fixed issue 467 for application resource type

- ref_ts/receivers.py
- ref_ts/templates/pages/create-ref-time-series.html
- ref_ts/templates/pages/reftimeseries.html
- ref_ts/ts_utils.py
- ref_ts/urls.py
- ref_ts/views.py
@selimnairb @hyi 
We moved temp files to /tmp/ using tempfile module. Line 538 - 554 in ref_ts/ts_utils.py
Please review it.
Thanks
Drew and Jeff
> [466] fix temp files storage and some cleanup

- hs_app_netCDF/models.py
- hs_app_netCDF/receivers.py
refine the metadata extraction for 'rights' element
add the 'missing_value' element in science metadata xml
> 8 netcdf meta refine

- ref_ts/ts_utils.py
- ref_ts/views.py
Fixed #499. All changes are isolated in this app.
Note: This hotfix is still based on the old HISTimeSeries workflow. New workflow #502 is under development.
> Fixed HISTimeSeries Issue 499 in NFIE release 1.5.2

- hs_core/templates/pages/genericresource.html
Only two lines of code changes to reinstate previous fix that got lost along the way.
> fixed issue [#529]

- hs_core/hydroshare/utils.py
- hs_core/views/__init__.py
removed some unused imports and removed global variables whose uses have already been removed. @pkdash @selimnairb could you review to make sure they don't cause any issues? I have already done a global search and the removed don't appear to be used anywhere.
> resolve [#370] to remove globals

- run-tests-jenkins
```run-tests-jenkins``` script will generate both test results and coverage reports in xml format suitable for the Jenkins Cobertura Coverage Report plugin and JUnit Test Result Report plugin. Both these plugins generate much better looking reports as well more useful reports.
You can find an example of coverage summary report in Jenkins (generated using this branch) at the following link: 
https://jenkins.renci.org/job/test-jenkins-coverage-report/18/cobertura/
A more detailed coverage report in Jenkins can be found at:
https://jenkins.renci.org/job/test-jenkins-coverage-report/18/cobertura/_default_/
Example of Jenkins test results report can be found at:
https://jenkins.renci.org/job/test-jenkins-coverage-report/18/testReport/
> coverage and test reports for jenkins

- hs_core/models.py
@mohamedmorsy - If you want you can pull this branch and test to see if the issue got resolved.
I can't build this branch now on dev.hydroshare.org from within Jenkins to generate a link for the coverage report. As soon as Michael resolves the issue, I will run a build job on Jenkins. In the mean time my local test run reported all tests passing with 42% (no change in code coverage) code coverage.
> fix for date values in metadata xml document

- hs_core/templates/pages/genericresource.html
Just a minor fix for another ambiguity in spatial coverage labels.
> [#538] Fixed another ambiguity in spatial coverage labels

- .gitmodules
Resolved issue [#90] to remove submodule dublincore which is not used, and everything works in my local dev environment based on my testing. @mjstealey could you review to see whether everything looks right?
> Removed submodule dublincore

- hs_core/templates/pages/create-resource.html
remove app res type from user interface for 1.5.3.
> [#582] remove app res type from user interface

- hs_core/views/resource_rest_api.py
> Fix error when creating NetCDF resources using REST API

- hs_core/templates/pages/create-resource.html
- hs_core/views/__init__.py
- hs_core/views/utils.py
- irods_browser_app/static/css/site_base_irods.css
- irods_browser_app/static/js/irods.js
- irods_browser_app/templates/irods_upload_add.html
- irods_browser_app/views.py
allow users to use SHIFT and CTRL key for multiple file selection in iRODS file browser in the similar way as other regular file browsers. Ran coverage test locally and coverage stays the same 42% as before with no failure.
> 560 irods multi file selection

- hs_core/views/resource_rest_api.py
> Remove unnecessary processing of filtered resource list

- hs_modelinstance/forms.py
This is a simple fix for Model Instance resource type to work with the new base model
> [#633] simple fix to Model Instance

- theme/templates/generic/includes/rating.html
- theme/templatetags/ratings_tags.py
Fixed regression error with ratings and implemented new rating functionality as outlined in issue [#611]
@mauriel133 @ironfroggy could you give a quick review of the code?
> fixed issue [#611] - make rating work again

- hs_app_netCDF/serialization.py
- hs_app_timeseries/serialization.py
- hs_core/hydroshare/date_util.py
- hs_core/serialization.py
- hs_core/tests/serialization/__init__.py
- hs_core/tests/serialization/test_generic_resource_meta.py
- hs_core/tests/serialization/test_resourcemeta_sax_parsing.py
- hs_geo_raster_resource/serialization.py
- hs_model_program/serialization.py
- hs_modelinstance/serialization.py
- hs_swat_modelinstance/serialization.py
- hs_tools_resource/serialization.py
Work in progress, do not merge yet.
> REST API ingestion of BagIt archives

- hs_core/serialization.py
Addresses #651.  This fix is needed for migration.  @pkdash @hyi @ironfroggy Please review so that @mjstealey can merge ASAP.  Thanks.
> Relax os.path.isfile checks to os.path.exists

- hs_app_netCDF/serialization.py
- hs_app_timeseries/serialization.py
- hs_core/serialization.py
- hs_core/tests/serialization/test_generic_resource_meta.py
- hs_geo_raster_resource/serialization.py
- hs_model_program/serialization.py
- hs_modelinstance/serialization.py
- hs_swat_modelinstance/serialization.py
- hs_tools_resource/serialization.py
Addresses problems 1 and 3 in #670.  @pkdash @hyi Please review as soon as you can so that this can be merged in used in the next and hopefully final migration dry run.
> 670 remaining migration problems

- hs_core/hydroshare/hs_bagit.py
- hs_core/models.py
This PR adds additional xml attributes related to resource 'type' element to include resource verbose name in addition to the existing resource class name
> additional xml attributes for science matadata and resource map document

- theme/views.py
Resources for which the current user has no access to are no longer shown in profile resource listing.
> 320 Profile page resource listing fix

- hydroshare/settings.py
- theme/templates/email/signup_verify.html
- theme/templates/email/signup_verify.txt
- theme/templates/email/signup_verify_subject.txt
Address issue [#565]. @ironfroggy could you give a quick code review?
> 565 account reg email content

- hydroshare/settings.py
@selimnairb @ironfroggy @robline please review this PR ASAP so that it can be merged in for a release 1.6.1 hot fix on www.
> fixed issue [#703] to allow anonymous users to download public bags

- hs_core/templates/pages/create-resource.html
- hs_core/templates/pages/genericresource.html
- hs_geographic_feature_resource/receivers.py
@dtarb @mauriel133 @hyi @pkdash 
please review
#710 hotfix
> [#710] fix frontend file extension check

- hs_core/templates/pages/create-resource.html
disable HIS refts in dev and master
> [#727] disable his refts

- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
- hs_core/views/utils.py
@hyi @pkdash Please review this in-progress work, in particular my additions to the hs_core.views.utils.authorize() method (there may be a better way to do this).
> Make system and science metadata world-readible for resources that are discoverable

- README.md
Add build/test status from Jenkins workflow to README.md file in develop branch
> Add Jenkins CI workflow badge to README.md file

- theme/static/css/hydroshare_core.css
- theme/templates/accounts/profile.html
This fixes a minor bug where some authors are not listed for a resource item in the profile page.
Also includes minor style changes.
> [#744] Profile page hotfix

- hs_core/templates/pages/genericresource.html
- hs_core/views/__init__.py
- theme/static/css/hydroshare_core.css
This fixes the issues of the access control interface where some buttons would be enabled when they should not. 
I added a function that takes in the current access level and disables the corresponding parts of the interface. This function is called after access has been granted or changed.
> 717 editors delete owners

- hsctl
to run non-interactively as a cron job.
> added update_index command in hsctl script #755

- hs_app_netCDF/page_processors.py
- hs_app_netCDF/templates/pages/netcdfresource.html
Need front-end layout update before merge.
> 779 opendap

- docker-compose.yml
- hs_core/customer_form.py
- hs_core/templates/search/search.html
update based on feedbacks from issue 783. @mjstealey @hyi I hope we could get some update versions of pg.www.sql data for test. Since the solr faceted search is really sensitive to data. I really need some updated date to test my code. Thanks so much!
> 783 solr discovery improvement

- hs_core/templates/search/search.html
- theme/static/css/hydroshare_core.css
improved search faceted result colormap according to http://colorbrewer2.org/ guidance and added colormap legend. Have emailed others for feedback and have not heard any objections to have it included for AGU, so create this PR to get code review going to have it included for AGU release.
> improved search faceted result colormap and added colormap legend

- hs_core/views/__init__.py
- hs_labels/migrations/0001_initial.py
- hs_labels/models.py
- hs_labels/tests/test_resource_labelling.py
- hs_labels/views/__init__.py
Need to be reviewed and merged for AGU release.
> 795 refactoring of hs_lables app models

- hs_core/page_processors.py
@hyi Can you please test this branch on your local dev to see if it fixed the issue before merging?
> 799 fix for anonymous user accessing public/discoverable resource

- hs_core/templates/search/search.html
Made improvements based on issue #805
> made improvements based on  issue 805

- docker-compose.yml
- hs_core/templates/pages/genericresource.html
- hs_core/templates/pages/my-resources.html
- theme/static/css/hydroshare_core.css
This PR addresses many of the issues in #798 and contains many code improvements.
> 798 my resource page improvements

- hs_access_control/models.py
- hs_access_control/tests/test_access_control.py
This needs to be reviewed and merged in order for @mauriel133 Mauriel to fix some issues with my resource page.
> 810 fix for premission specific resource list api

- hs_core/templates/pages/my-resources.html
- theme/static/css/hydroshare_core.css
[#803] Fix redirection when pressing Enter key.
[#803] Autofocus input when create label window appears.
[#802] Fix for table buttons in firefox.
> 803 create label fix

- hs_labels/models.py
- hs_labels/tests/test_resource_labelling.py
@hyi or @alvacouch please review
> 813 api to suport label cascade delete

- hs_core/templates/pages/my-resources.html
Fixes an issue where filters wrongly show 0 occurrences in My Profile page.
> Fix for filter showing 0 occurrences.

- hs_core/views/__init__.py
@hyi or @mauriel133 Please review and merge.
> 825 fix for labels and favorite persist problem

- README.md
Improve the CI report on the README.md file when viewed from Github.
Include status for all stages, Workflow, Clean, Build, Unit Tests, REST Tests
> Build status update - appears in README.md file as status icons from Jenkins

- hs_model_program/migrations/0006_auto_20151216_1500.py
- hs_modelinstance/migrations/0006_auto_20151216_1500.py
Add missing migrations files for hs_model_program and hs_modelinstance
> [#834] add two missing migrations files

- hydroshare/local_settings.py
- theme/templates/email/signup_verify.html
- theme/templates/email/signup_verify.txt
addressed both issue [#565] - changing sign-up email content and issue [#843] - changing site name to be HydroShare from Hydroshare. @mjstealey Could you give a quick code review and see if you can give a +1?
> 565 change reg email content

- hs_core/templates/pages/genericresource.html
@mjstealey could you do a quick review to see if you can give a +1? It is just a simple style change to make irods signin presentation on resource landing page to be consistent with the presentation on resource creation page.
> fixed issue [#840] - change irods signin style from resource landing page

- theme/templates/email/signup_verify.html
- theme/templates/email/signup_verify.txt
removed expiry statement from signup email as suggested by @dtarb. @mjstealey could you give a quick code review and merge it?
> removed expiry statement from signup email

- theme/views.py
@mjstealey Could you do a quick review and merge if you can give a +1? Just simple notification message expansion exactly as @dtarb suggested in the issue.
> addressed issue [#864] - expand notification message about email confirmation

- hs_core/views/utils.py
UserAccess class no more has the 'admin' attribute.
> [#875] authorize function bug fix

- hs_core/templates/pages/create-resource.html
- hs_core/templates/pages/genericresource.html
- irods_browser_app/static/js/irods.js
- theme/static/css/hydroshare_core.css
Layout has been improved/refined according to suggestions by Dave on issue [#840]. Both create resource page and resource landing page have been modified to have consistent layout changes related to iRODS file sign-in and browsing. @mauriel133 @ironfroggy could you do a quick code review to see if you can give a +1?
> 840 refine irods signin layout

- hs_core/templates/pages/my-resources.html
Fixes sorting in My Resource page for Last Modified column.
> 863 - Last Modified column sorting

- hs_core/tests/api/rest/__init__.py
- hs_core/tests/api/rest/test_user_info.py
- hs_core/views/user_rest_api.py
> Add first and last name to userInfo REST endpoint

- theme/templates/base.html
One line change that fixes duplicate javascript inside block extra_js
> [#869] Removed block extra js from base.html

- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- hs_tools_resource/forms.py
- hs_tools_resource/migrations/0007_auto_20160122_2240.py
- hs_tools_resource/models.py
- hs_tools_resource/page_processors.py
- hs_tools_resource/static/js/toolresource.js
- hs_tools_resource/templates/pages/toolresource.html
- hs_tools_resource/tests/test_web_app.py
A few minor errors were found and fixed. Changes were made to models.py to change the required (*) fields. A few variable names changed to be more intuitive. No new functionality was introduced.
> 900 Clean-up, rename variables/fields/labels, repair impaired functionality

- hs_core/templates/pages/genericresource.html
- hs_core/templates/pages/my-resources.html
- hs_core/views/__init__.py
- theme/static/css/hydroshare_core.css
Implements the resource shareable flag.
Also includes minor bug fix in the manage access interface.
> 664 resource shareable flag

- hs_core/templates/pages/my-resources.html
- theme/static/css/hydroshare_core.css
Fixes table issues outlined in #908
> 908 my resource page scrolling

- hsctl
Fix for google map display in resource landing page
> Release 1.6.5.1 - google maps hotfix

- hs_core/templates/pages/my-resources.html
> [#950] Time is now considered when sorting by date.

- hs_core/templates/400.html
- hs_core/templates/404.html
- hs_core/templates/500.html
- hs_core/templates/503.html
- theme/static/js/custom.js
- theme/templates/base.html
Also removed unused reference in base html
> [#939] Apps link now open in new tab.

- hs_core/models.py
- hs_core/templates/pages/genericresource.html
[#940] Added Described By relation and help text below the button to add relations.
> 940 - Described By relation

- Dockerfile
> Release 1.6.6 Prep

- hs_core/templates/pages/my-resources.html
- theme/static/css/hydroshare_core.css
This change reverses the table scrolling as discussed in #908
> [#908] Reversed table scrolling

- theme/static/js/coverageMap.js
- theme/static/js/resourceLandingAjax.js
- theme/static/js/resourcelanding.js
These are the missing scripts after refactoring of genericresource.html
> [#969] Added missing scripts

- docker-compose.template
- hsctl
- nginx/run-nginx
- scripts/backup-hs
- scripts/pre-remove-hs
- scripts/rebuild-index-solr
- scripts/restore-hs
> hsctl - control script updates, solr, nginx, cleanup

- hs_geo_raster_resource/forms.py
- hs_geo_raster_resource/templates/pages/rasterresource.html
- theme/static/css/hydroshare_core.css
Also fixed minor border radius issue for form elements.
> [#1009] Made band information box wider.

- hs_core/templates/pages/genericresource.html
- theme/static/js/coverageMap.js
This fixes the issue of the coverage map not running. The problem was caused by the script running before the map container was rendered in the page.
> [#997] coverage map chrome

- hs_model_program/page_processors.py
- hs_modelinstance/page_processors.py
- hs_swat_modelinstance/page_processors.py
Fix has been manually applied on www
> fix for AttributeError: 'NoneType' object has no attribute 'user'

- hs_app_netCDF/page_processors.py
- hs_app_netCDF/templates/pages/netcdfresource.html
Please merge this so that I can test on a real netCDF resource in production site. And then I can make sure the code update works as expected. Thanks!
> [#1035] update hyrax link initial implementation

- .gitignore
- hsctl
@hyi - This will ensure the celery directory exists at start up (rebuild, rebuild --db, start, restart)
> persist the celery folder on each start

- hs_core/tests/api/rest/base.py
> Final fix for tests causing Docker containers to exit after test completion.

- hs_core/templates/pages/create-resource.html
applying to develop branch (previously applied to release-candidate)
> [#1065] file validation bug fix initial implementation

- hs_geo_raster_resource/receivers.py
@pkdash please review it thanks~
> [#1086] hide warning info for unit test

- hs_core/hydroshare/resource.py
@pkdash Could you give a quick review and see if you can +1? Only a couple of line changes, so should be a very quick review.
> set up immutable attribute for obsoleted resources

- hs_collection_resource/models.py
- hs_collection_resource/page_processors.py
- hs_collection_resource/templates/pages/collectionresource.html
- hs_collection_resource/tests/test_collection.py
- hs_collection_resource/views.py
- hs_core/hydroshare/resource.py
- hs_core/testing.py
- theme/templates/resource-landing-page/top-right-buttons.html
1) versioning
2) publishing
3) collection holds collections
> 1111 collection res type phase 2

- hs_modelinstance/models.py
- hs_swat_modelinstance/models.py
- hs_swat_modelinstance/tests/__init__.py
- hs_swat_modelinstance/tests/test_swat_modelinstance_metadata.py
> 572 swat model instance tests

- theme/templates/resource-landing-page/modals.html
> hotfix for tag 1.6.9

- hs_core/templates/search/search.html
- hs_core/views/discovery_json_view.py
Fixed the Chrome layout render issue reported by Mohamed. #1139
> fix discovery reported issues

- Dockerfile
@mjstealey would you please code review it and +1 if it is OK for merge? Thanks
> [#1149] enable ncdump command

- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
this pr is to address #1138 and a minor bug #1155
> #1138 -- supported res type names should exactly match with res type names and fix webapp icon bug

- hs_swat_modelinstance/models.py
- hs_swat_modelinstance/templates/pages/swatmodelinstanceresource.html
> [#1164] Fixed the bug

- hs_swat_modelinstance/migrations/0007_auto_20160428_1843.py
Generated SWAT Model Instance missing migrations related to #1170. @mjstealey please revise
> [#1170] Generated SWAT missing migrations

- hs_swat_modelinstance/migrations/0007_auto_20160428_1843.py
> 1170 swat missing migrations

- hs_core/HydroRealtimeSignalProcessor.py
- hs_core/hydroshare/resource.py
- hs_core/models.py
- hs_core/search_indexes.py
- hs_core/templates/search/indexes/hs_core/baseresource_text.txt
- hs_core/templates/search/search.html
- hs_core/views/discovery_view.py
- hydroshare/settings.py
Using current state of branch to merge with release candidate.
Leaving PR for develop branch open until further vetting is done by team.
> Discovery issue fix - release candidate version

- ref_ts/templates/pages/create-ref-time-series.html
> [#1178] HIS-RefTS-UI-bug

- ref_ts/templates/pages/create-ref-time-series.html
Adding to release candidate.
Already merged into develop.
> 1178 his ref ts ui bug

- hs_script_resource/page_processors.py
> [#1191] fix script creation bug

- hs_core/templates/search/search.html
> Fix discovery blank page issue 

- Dockerfile
- hs_access_control/models.py
- hs_core/autocomplete_light_registry.py
- hs_core/views/__init__.py
Filter out inactive users/groups for autocomplete UI.
For previous conversions related to this PR refer to https://github.com/hydroshare/hydroshare/pull/1200
> Inactive users and groups

- hs_app_timeseries/templates/pages/timeseriesresource.html
- theme/templates/resource-landing-page/modals.html
block modal_add_file was duplicated, causing the error.
> [#1151] Fix for extract metadata option

- hs_core/models.py
- hs_core/tests/api/native/test_core_metadata.py
- hs_core/tests/api/native/test_update_metadata.py
- hs_geographic_feature_resource/tests/test_geo_feature.py
Added validation for 'point' values and bounding 'box' values.
> Coverage metadata validation

- hs_core/templates/pages/genericresource.html
- theme/static/js/resourceLandingAjax.js
Notifications of metadata status are now displayed when updating keywords.
> [#1225] [#1186] Notification message when updating keywords

- hs_geo_raster_resource/forms.py
- hs_geo_raster_resource/migrations/0005_auto_20160509_2116.py
- hs_geo_raster_resource/migrations/custom_migration_for_raster_meta_update_20160512.py
- hs_geo_raster_resource/models.py
- hs_geo_raster_resource/raster_meta_extract.py
- hs_geo_raster_resource/receivers.py
- hs_geo_raster_resource/templates/pages/rasterresource.html
- hs_geo_raster_resource/tests/test_raster_metadata.py
This branch solves the issues related to raster resource #1110, #1162
> Raster issues

- theme/templates/pages/group.html
Also allows only for owners to invite other users to the group.
> [#1277] Fix for broken link to user profile

- hs_core/templates/search/search.html
Added mapping to sort by Last Modified correctly.
Added resource type icons and resource access status to resource table.
Resource list table style change.
Can be tested at https://playground.hydroshare.org
> [#863] Discover page - Last Modified sorting

- hs_geographic_feature_resource/receivers.py
This pr is supplement to the 1120-feature-fix branch for the irods user space feature.
This pr add "try expect" statements to every receiver functions and save errors in log file.
> [#1120]add error log to feature

- hs_tracking/migrations/0003_auto_20160623_1718.py
- pg.development.sql
Update development database
- Add Collaborate page
- include missing migrations files
> [#1297] update database and migrations

- Dockerfile
- gunicorn_start
update Dockerfile references and gunicorn settings
> Release candidate 1.7.2

- hs_core/models.py
@mjstealey Can this be applied as a hotfix to www?
> Changes to coverage validation

- hs_script_resource/page_processors.py
a missing parameter in page processor has been added to fix issue #1320
> [#1320] add the missing parameter in page processor

- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/top-right-buttons.html
Fixes issue described in #1300
> [#1300] Add to My Resources button bug fix

- theme/forms.py
- theme/templates/accounts/profile.html
@pkdash @mjstealey This simple one-line change will fix the bug @mjstealey found regarding saving profile changes resetting iRODS user account setting. @pkdash Please give a quick review so that it can be merged.
> Saving profile changes now works correctly with irods user account

- hs_geographic_feature_resource/page_processors.py
This pr is a hotfix for issue #1344.
> [#1344] 1.7.3-hotfix-feature-res-warning-popup

- hs_core/views/resource_rest_api.py
- ref_ts/urls.py
- ref_ts/views.py
> hotfix - download refts res via rest api

- Dockerfile
- hs_core/xmlparser.py
- hydroshare/_xmlcache/LS8vRFVCTElOIENPUkUvL0RDTUVTIERURCAyMDAyLzA3LzMxLy9FTg==
> Added a new custom XML parser that caches DTDs that it requires

- Dockerfile
- hs_geo_raster_resource/raster_meta_extract.py
- hs_geo_raster_resource/receivers.py
fix the bugs with raster 
#1162 #1335 #1367
> Raster bug fix

- hs_core/views/utils.py
@pkdash @mjstealey This PR currently points to the corresponding 1295-branch in django_irods repo and needs to be reviewed together with PR https://github.com/hydroshare/django_irods/pull/11. Once django_irods PR is merged, will update django_irods reference SHA to point to master branch in this PR before merging.
> clean up irods temp environment files

- Dockerfile
used updated base image with GDAL 2.1.0 installation for release 1.7.4
> 1.7.4 base image updates

- hs_core/page_processors.py
- theme/templates/resource-landing-page/title-section.html
Now also listed while editing the resource.
> [#1076] Required elements to make a resource public 

- hs_tools_resource/forms.py
This is a hotfix for 1.7.4 beta to address issue #1379.
> [#1379] 1.7.4 Hotfix -- fix webapp forms logic

- theme/static/css/hydroshare_core.css
- theme/templates/resource-landing-page/top-right-buttons.html
Updated manage access icon to an arrow escaping a box to make it more intuitive.
> [#1245]Manage access icon

- Dockerfile
> release 1.7.4

- hs_core/views/utils.py
@mjstealey Would you please take this pull request as hot fix and merge it to master branch after it gets +1 ? Thank you.
> Rest API bug fix to create the coverage box and point metadata

- hs_core/tasks.py
- hydroshare/irods/ruleGenerateBagIt_HS.r
This is a follow-up simple "sha2" to "sha256" replacement to be more specific in checksum hash algorithm being used. Since it is a simple name replacement and the original PR has been +1'ed, I am going to merge this without further code review.
> changed sha2 to sha256 to be more specific in manifest files

- theme/templates/pages/group.html
One line change. Fixed erroneous selector.
> [#1409] Group shared resources message

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
Applied suggestions discussed in #1406
> [#1406] Contact to Authorship

- docs/bagit/readme.txt
- hs_core/hydroshare/hs_bagit.py
- hs_core/tasks.py
- hydroshare/irods/ruleGenerateBagIt_HS.r
- hydroshare/local_settings.py
- setup.cfg
@pkdash Could you do a code review for this small PR whenever you get a chance? Code changes in hs_bagit.py are mostly to fix pylint code style compliance, so the actual code change is small. @mjstealey Could you apply this change to beta so that @horsburgh can do a quick test once this PR is merged into develop? I am hoping to have this PR merged and deployed for the next release so that bag_modified for all resources will be manually reset to false one time for the next release rather than doing it again for subsequent release.
> 517 include bagit readme

- hs_swat_modelinstance/page_processors.py
@pkdash @mjstealey this is a simple fix to issue #1440. Hope we could merge it to release 1.7.5
> Simple fix to issue #1440

- hs_core/templates/pages/collaborate.html
- theme/static/css/hydroshare_core.css
In collaborate page:
Added scrolling for long group descriptions.
Added scrolling for Members list.
> [#1233] Constrained group description height

- theme/templates/resource-landing-page/title-section.html
Minor change. Fixed as specified in #1445
> [#1445] Edit resource help message

- hs_core/views/__init__.py
This needs to be merged before next deployment for 1.8. I have also updated beta with the fix for further testing and validation. @gantian127 can you do a code review and also test on beta to see whether this issue has been fixed and ready to merge? If so, you can give a +1 and I can then merge the PR.
> fixed issue [#1521]

- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
Fixes button behavior described in #1526
Also contains minor style changes
> [#1526] Buttons activation

- hs_core/hydroshare/hs_bagit.py
- hs_core/resourcemap_urls.py
@pkdash This PR needs to be merged for 1.8 deploy, so please do a quick code review at your earliest convenience. Thanks.
> fixed issue [#1540]

- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/templates/pages/genericresource.html
- hs_core/tests/api/native/test_create_new_version_resource.py
- hs_core/views/utils.py
- setup.cfg
This PR needs to be merged before 1.8 deploy. @pkdash Can you do a quick code review at your earliest convenience. I have also updated beta that includes fixes to both issue #1528 and #1527. @dtarb Can you test on beta again when you get a chance to confirm these two issues have been fixed on beta?
> fixed issues [#1528] and [#1527]

- hs_core/templates/search/search.html
- This PR fixed issue #1563 
- Basically, the "Map Results" option on list view is a duplicated function to the table under the map. So I just removed all code related to it. 
- This PR also fixed an issue related "reset map zoom" button on the map.
- This PR also removed the unused "rectangle" object on map.
> remove the ambiguous options for "Map Results" and "All Results"

- hs_swat_modelinstance/templates/pages/swatmodelinstanceresource.html
@pkdash another minor fix for you to review please
> [#1552] fixed comma issue

- hs_modflow_modelinstance/models.py
@pkdash please review this minor fix
> [#1550] fixed issue, study area deletes if empty

- hs_core/templates/pages/collaborate.html
- theme/static/css/hydroshare_core.css
- theme/templates/pages/group.html
Also: [#1260] The entire group image is now displayed, instead of a zoomed in version of it.
> [#1260] Group previews now have the same height.

- hs_core/views/resource_folder_hierarchy.py
@pkdash Please give a quick review to this issue and see if you can +1. This needs to be merged for the next 1.8 release. I have also updated beta so that you can test downloading of two files with the same file name on beta now. This issue has been fixed based on my testing on beta.
> fixed issue [#1602]

- hs_modflow_modelinstance/models.py
partial fix for modflow model instance specific problem in issue #1601 which has problems with other resource types which still need to be addressed
> [#1601] accounts for possible None values in validation

- hs_geographic_feature_resource/parse_lib.py
- hs_geographic_feature_resource/tests/test_geo_feature.py
This pr was to fix #1585.
Title meta will be extracted from shp.xml if possible. Title that is longer than hs title field limit will be truncated.
> 1585-failed-to-create-feature-res

- .gitignore
Some people might find this helpful. I added some metadata files that Sublime Text and PyCharm create to our .gitignore file. Feel free to ignore this until after AGU of course.
> Mrh gitignore additions

- hs_core/models.py
- hs_core/signals.py
- hs_core/views/__init__.py
- hs_tracking/management/commands/stats.py
- hs_tracking/middleware.py
- hs_tracking/models.py
- hs_tracking/signals.py
- hs_tracking/utils.py
Added use tracking for: 
* resource create
* resource download
* resource delete
Added tracking variables:  #1577
* ip address
* activity name
* http code
* request method
* user type
* resource info
* email domain
> 1531 download tracking

- theme/templates/accounts/profile.html
Changed user name validation rule to conform to the rules used in Django. @pkdash or @mauriel133 Can you do a quick review of this PR - only one line change in regular expression validation. This PR needs to go to AGU release.
> addressed user name validation issues when editing profiles

- hs_core/discovery_form.py
- hs_core/search_indexes.py
- hs_core/templates/search/indexes/hs_core/baseresource_text.txt
- hs_core/templates/search/search.html
- hs_core/views/discovery_json_view.py
- hs_core/views/discovery_view.py
This PR is related to issue #1517 and #1185. 
Add "Published" as a value under the "Filter by Availability" facet
> add filtering by published feature

- hs_core/templates/403.html
- hs_core/templatetags/hydroshare_tags.py
- setup.cfg
This PR implemented customized 403 forbidden page exactly as specified by @dtarb. This PR needs to go in for AGU release. @pkdash Please review yourself or assign someone to review as appropriate. @dtarb I can deploy this to a VM for you to test if you'd like. Just let me know if you want me to do so, otherwise, I will not bother to do that since I implemented exactly as shown in the mockup screen capture in the issue.
> 697 error page improvement

- hs_core/page_processors.py
- hs_tools_resource/forms.py
- hs_tools_resource/migrations/0010_auto_20161201_1905.py
- hs_tools_resource/migrations/0010_auto_20161203_1913.py
- hs_tools_resource/models.py
- hs_tools_resource/page_processors.py
- hs_tools_resource/receivers.py
- hs_tools_resource/tests/test_web_app.py
This pr is to address #1659 which is also listed in #1650
> 1659-make-webapp-public-without-associating-any-res-type

- hs_collection_resource/models.py
- hs_core/hydroshare/resource.py
- hs_core/models.py
- hs_tools_resource/models.py
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/title-section.html
- theme/templates/resource-landing-page/top-right-buttons.html
This PR addressed the issue #1648 to disable web app resource from being published. This is important since we don't want people to wrongly publish web app resources. This needs to go to AGU if possible. @pkdash Can you give a quick review at your earliest convenience?
> disabled web app resource from being published

- hs_access_control/models.py
- hs_access_control/tests/test_group_flags.py
Due to this bug, the user as a member of a deleted group was not seeing the access control panel even if the user had explicit access on that resource.
> Fix for bug in view_users() and edit_users()

- hs_core/views/resource_folder_hierarchy.py
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/title-section.html
This alert now disappears as soon as the requirements are met. No page reload is needed.
> Missing metadata and files alert

- theme/static/css/hydroshare_core.css
- theme/templates/accounts/profile.html
- theme/templates/pages/homepage.html
- theme/templates/pages/menus/dropdown.html
These are the home page changes discussed in #1597 and #1554
> [#1597] Reorganize page elements

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
- theme/templates/resource-landing-page/modals.html
Added 'Get file URL' menu item to file browser as discussed in #1522
> [#1522] Added get file URL menu item

- hs_core/templates/pages/genericresource.html
- hs_core/tests/api/views/test_group.py
- hs_core/views/__init__.py
- theme/static/css/hydroshare_core.css
- theme/static/css/hydroshare_extends.css
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/modals.html
Could not reproduce the error on self unsharing of a resource. However, it now redirects to my resource page upon unsharing.
> Self unsharing resource

- ga_resources/admin.py
@mjstealey This PR removes ga_resources from admin panel. Can you code review and +1 if it looks good to you? I did not bother to remove django_docker_processes from admin panel since the whole app will be removed soon which would remove django_docker_processes from admin panel automatically.
> removed ga_resources from admin panel

- hs_core/templates/pages/my-resources.html
I commented out the erroneous lines. We could merge this as a hot fix so we can get a stable development branch. 
The error was caused by a reference error in PR #1614. Perhaps some parts of the code is missing from merge.
> [#1730][WIP] Resources not appearing in My Resources page.

- Dockerfile
Reverting back to prior base image appears to resolve bag download issue.
> [#1730] revert base image

- hsctl
Addresses #1734 - enable/disable /tests/ based on USE_SSL state.
> [#1734] add /tests/ URL switch

- hs_access_control/models.py
- hs_access_control/tests/test_explicit_access.py
1. via_group and via_user arguments added to get_resources_with_effective_access. 
2. excess antibugging removed. 
See issue #1710
> 1710 various problems in access control

- hs_core/tests/api/native/test_get_citation.py
@pkdash here is the fix I mentioned in the call.
> Fixed 2016 hard-coded date problem

- hs_app_netCDF/migrations/0006_auto_20170120_1445.py
- hs_core/migrations/0032_auto_20170120_1445.py
- hs_core/models.py
- hs_core/search_indexes.py
- hs_core/templates/search/indexes/hs_core/baseresource_text.txt
- setup.cfg
@pkdash @mjstealey @dtarb I think I fixed it. I know that the individual `prepare_\*` routines are correct. Awaiting a final test on the text template.
> 1765 fix metadata none error

- hs_modflow_modelinstance/models.py
- hs_swat_modelinstance/models.py
This PR solves the model resources versioning problem with ManyToMany relation regarding issue #1601. there are other resource types use ManyToMany relation and require the same fix. @zhiyuli I think web app resources may require the same fix.
> 1601 second solution

- hs_core/models.py
- hs_core/templates/pages/genericresource.html
- hs_core/tests/api/native/test_core_metadata.py
- hs_core/views/__init__.py
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/subject.html
This work involves:
- Prevent duplicate keywords
- Allow deleting all keywords (If all keywords are deleted, then the resource gets set to private by the system)
> Keywords editing improvements

- theme/templates/resource-landing-page/top-right-buttons.html
@mauriel133 I'd forgotten to make the pull request for this. Could you approve on the PR?
> [#1699] changed mange access icon to user-plus

- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
Note: if more file type icons are needed, this would be a good time to add them.
> [#1764] Added sqlite file type icon

- hs_core/models.py
- hs_core/tests/api/rest/test_resource_science_meta.py
- hs_core/views/resource_metadata_rest_api.py
Trying to solve #1788 
Seems like a simple enough fix using the existing model code but open to other solutions, or to the idea that this solution isn't quite adequate.
> 1788 creator rules obey

- hs_core/tasks.py
- hydroshare/celery.py
- hydroshare/local_settings.py
@mjstealey @pkdash Can you code review this to see if you can +1? I will deploy this to a VM for you to test as well.
> 1799 strip pickle

- hs_app_timeseries/forms.py
In the editing mode of the time series resource, help text will be displayed when user hovers over a metadata input field.
> Help text for timeseries resource metadata form elements

- hs_core/page_processors.py
Additional check in page preprocessor for resource edit permission. We should be able to close issue #729 after this PR gets merged. Other parts of this issue have already been addressed.
> Rresource edit permission check improvement

- ref_ts/models.py
1) add a missing parameter to get_xml() in ref_ts code
2) remove unused parameter in create_bag_by_irods() in django_irods submodule (see #1822 pr at django_irods).
> 1822 failed to create refts

- hs_access_control/models.py
- theme/static/css/hydroshare_core.css
- theme/static/js/resourceLandingAjax.js
Minor change for Manage Access interface as discussed in #1252
Also fixes a minor issue where a row would stay in loading state after attempting to remove access.
> [#1252] Access error message improvement

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/templates/resource-landing-page/modals.html
This PR implements dragging and dropping table rows in the Authors listing to change the order in which they appear.
> [#943] Simplify Changing Author Order

- hs_core/templates/pages/genericresource.html
- hs_core/views/__init__.py
- theme/static/js/hs_file_browser.js
- theme/static/js/resourceLandingAjax.js
The work in this PR allows for files to be uploaded to the current directory in the resource landing page file browser.
> [#1671] Upload files to subfolders

- theme/static/js/coverageMap.js
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/coverage.html
#1889 This fixes a parsing error for date fields in the coverage section of the resource landing page.
We should try to get this merged as a hotfix.
> [#1889] Coverage date parsing bug fix

- Dockerfile
- hs_tracking/models.py
- hs_tracking/signals.py
- hs_tracking/tests.py
- hs_tracking/utils.py
* modified hs_tracking logs to report a consistent set of fields.  This is necessary to generate more meaningful statistics in kibana.
* added unit tests for hs_tracking.utils
> 1893 consistent usage logs

- hs_access_control/migrations/0020_merge.py
@pkdash @mjstealey @hyi I managed to run `makemigrations --merge` and it generated this file, which simply merges and orders the changes made by myself and Pabitra.
> Fix merge conflict

- hs_core/tests/api/rest/test_resource_file.py
- hs_core/tests/api/rest/test_zip_folder.py
- hs_core/urls.py
- hs_core/views/resource_folder_hierarchy.py
@hyi @pkdash While I work with @mjstealey to get iRODS running locally to continue this, would either of you be able to help me complete the test?
> WIP Zip Folder - need iRODS help

- config/hydroshare-config.yaml
- hsctl
- hydroshare/settings.py
USE_SECURITY flag to enable/disable security settings and middleware 
- user level set in config/hydroshare-config.yaml - defaults to false
- settings.py - USE_SECURITY defaulted to False
- hsctl changed to update settings.py based on contents of hydroshare-config.yaml
> #1905 add USE_SECURITY flag

- hs_core/hydroshare/utils.py
- hs_core/tests/api/native/test_irods_user_zone_federation.py
@pkdash Can you give a quick review for this small PR? I have already applied hotfix to www since it is a regression issue, so it needs to go into the next release.
> 1920 rep to user zone fix

- hs_app_netCDF/templates/pages/netcdfresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
Icon:
Also contains visual improvement for header file
> [#1911] NetCDF file icon

- hs_core/templates/pages/genericresource.html
- theme/static/js/hs_file_browser.js
- theme/static/js/resourceLandingAjax.js
A message linking to help pages is shown.
> [#1917] Disable download for large files

- hs_core/autocomplete_light_registry.py
- hs_core/templates/pages/genericresource.html
- theme/templates/resource-landing-page/modals.html
In manage access panel, the autocomplete now correctly matches when typing in multiple words.
> [#1959] Manage Access Panel - Autocomplete fix

- hs_model_program/forms.py
- hs_model_program/receivers.py
- hs_model_program/templates/pages/modelprogramresource.html
@mauriel133 @pkdash could you review these front-end changes? Thanks!
> 1700 model program ui fixes

- .gitignore
Just a quick PR to clean up the local git arena.
> Adding celerybeat.pid to gitignore

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/custom.js
- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/credits.html
I implemented this as a reusable class. It can be used to make occurrences of URLs inside some element clickable.
**To initialize on page load add the class `"url-clickable"` to your item:**
`<span class="url-clickable">Some text and a URL https://github.com/hydroshare/hydroshare/issues/898</span>`
**To initialize dynamically call the `urlClickable` method:**
`$("#mySelector").urlClickable();`
> [#1895] Make extended metadata url clickable

- hs_core/templates/pages/genericresource.html
- hs_core/views/__init__.py
- theme/templates/resource-landing-page/modals.html
These are the occurrences that I consider can use this change.
> [#1929] Semantics - 'Replicate' to 'Copy'

- theme/templates/resource-landing-page/citation.html
This is the hotfix targeted at the master branch.
PR targeting develop branch at: https://github.com/hydroshare/hydroshare/pull/1980
> [HotFix][#1978] Buttons displacement fix

- hs_core/templates/400.html
- hs_core/templates/404.html
- hs_core/templates/500.html
- hs_core/templates/503.html
- theme/static/css/hydroshare_core.css
- theme/static/js/discover.js
- theme/templates/base.html
Adjusted navbar logo resolution
Old one:
New one:
> [#1996] Adjusted navbar logo resolution

- hs_app_netCDF/models.py
- hs_composite_resource/models.py
- hs_composite_resource/page_processors.py
- hs_file_types/models/base.py
- hs_file_types/models/netcdf.py
- hs_geo_raster_resource/models.py
- theme/templates/resource-landing-page/title-section.html
This needs to go in for release 1.10
> Show message for missing metadata for file types

- hs_file_types/models/netcdf.py
- hs_file_types/tests/test_netcdf_metadata.py
- hs_file_types/tests/test_raster_metadata.py
- hs_file_types/tests/test_view_functions.py
- hs_file_types/views.py
- theme/static/js/resourceLandingAjax.js
Updates resource level keywords when file level keywords are added. This needs to go in for release 1.10.
> Composite resource keywords update

- hs_core/page_processors.py
- hs_tools_resource/forms.py
- hs_tools_resource/migrations/0011_toolicon_data_url.py
- hs_tools_resource/models.py
- hs_tools_resource/page_processors.py
- hs_tools_resource/static/js/toolresource.js
- hs_tools_resource/tests/test_web_app.py
This PR retrieves image data from url provided by user, and then stores the image as a base64 string in db.
> #1933 store webapp icon in db as base64 string

- theme/tests/test_functional.py
Starting over with new state on #1951 :)
> Fix nightly Jenkins build by killing phantomjs

- hs_core/hydroshare/hs_bagit.py
- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/tasks.py
- hs_core/views/__init__.py
@hyi @pkdash Responding to comment in PR #2000 with a general fix. Now AVU isPublic tracks ResourceAccess.public in all cases.
> Make isPublic AVU track ResourceAccess.public

- hs_core/models.py
- hs_core/tests/api/rest/test_resource_file.py
- hs_core/views/__init__.py
- hs_core/views/resource_rest_api.py
@pkdash @aphelionz @hyi quick fix for URL botch in REST API. Testing now.
> Fix REST URL of file

- hs_core/management/commands/check_relations.py
- hs_core/models.py
- hs_core/tasks.py
@hyi @mjstealey @pkdash This PR addresses your unaddressed review commands on PR #2032, which I merged by mistake this morning. 
@hyi Since it was so close to merging, and I can't figure out how to reasonably unmerge it, could you approve this instead and we'll go with what we have? 
Thanks!
> Address unaddressed review comments

- hs_core/models.py
Hotfix for release-candidate 1.10.0
> HOTFIX- fix for attribute error for anonymous user

- hs_core/discovery_form.py
- hs_core/search_indexes.py
> fix issue 1998

- hs_core/models.py
@pkdash - Will defer to you whether you want to land this onto develop as well.
The hotfix has already been applied to release-candidate-1.10.0
> [#2043] fix for attribute error for anonymous user

- hs_tools_resource/static/css/toolresource.css
- theme/static/css/hydroshare_core.css
- theme/templates/resource-landing-page/title-section.html
> [#2069][Hotfix] Open With button spacing fix

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/generic-resource.js
Updated extended metadata Edit and Remove icons
> [#2067][Hotfix] Edit and Delete Icons for Extended Metadata Elements

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/generic-resource.js
- theme/static/js/group.js
- theme/templates/pages/group.html
Input now expands to fit the text
> [#2070][Hotfix] Username text overflow

- hs_core/templates/pages/create-resource.html
> [#2061][Hotfix] Fix for Create resource messages repetitive regarding iRODS

- hs_core/models.py
- theme/static/js/coverageMap.js
- theme/static/js/custom.js
- theme/static/js/hs_file_browser.js
Fixes date parsing error described in #2066
> [#2066][Hotfix] Temporal coverage parsing fix

- hs_core/templates/pages/create-resource.html
- theme/static/css/hydroshare_core.css
Proposed change as described in https://github.com/hydroshare/hydroshare/issues/2086
> [#2086][HOTFIX][WIP] Create Resource page - Resource type select order

- hs_access_control/migrations/0021_auto_20170506_1538.py
- hs_tracking/migrations/0005_auto_20170506_1538.py
Include required migrations that were left out of prior pull requests.
> 2083 [hotfix] Add necessary migrations

- hs_core/tests/api/native/test_view_utils.py
- hs_core/urls.py
- hs_core/views/resource_folder_hierarchy.py
- hs_core/views/utils.py
- theme/static/js/hs_file_browser.js
- theme/static/js/resourceLandingAjax.js
Remove limitation of 'no . in folder names' for UI paste and ensure transactional atomicity of paste. 
Rebasing to remove erronious commits. See #2108 for initial comments and review.
> 2105 unify rest and ui 2

- hs_app_netCDF/receivers.py
- hs_app_netCDF/tests/test_netcdf_metadata.py
- hs_app_netCDF/tests/test_netcdf_metadata_user_zone.py
- hs_app_netCDF/tests/views/test_create_netcdf_resource.py
- hs_file_types/models/netcdf.py
This is for release 1.11. Ready for code review.
> 2087 netcdf validation

- theme/static/css/elements.css
- theme/static/js/custom.js
- theme/templates/base.html
This is my first stab at an apporach for a more unified error / warning message system. It's a little bit of functional programming in that it returns a function that can then be used within the "error" property of a $.ajax call.
If we like this approach then we can start replacing the error code in our AJAX calls with this, which should drastically reduce lines of code and UX complexity.
> Front end piece of universal messaging block

- hs_core/__init__.py
- hs_core/apps.py
- hs_core/debug_urls.py
- hs_core/forms.py
- hs_core/models.py
- hs_core/page_processors.py
- hs_core/receivers.py
- hs_core/robots.py
- hs_core/router.py
- hs_core/search_indexes.py
- hs_core/tasks.py
- hs_core/testing.py
- hs_core/tests.py
- hs_core/xmlparser.py
> Adding comments to a lot of hs_core root files.

- hs_core/views/user_rest_api.py
- theme/static/css/elements.css
- theme/static/js/custom.js
- theme/templates/base.html
This uses the new universal messaging paradigm to display a nagging message to any user that has not filled out their title and organization fields.
A version of this is being built on https://park.hydroshare.com and should be done roughly an hour after the posting of this PR
ccing @dtarb and @ChristinaB to review
> Displaying error message when user has not filled out required fields

- hs_core/management/commands/check_django_metadata.py
- hs_core/management/commands/delete_resource.py
- hs_core/management/commands/fix_broken_resources.py
- hs_core/management/commands/ingest_irods_files.py
These are the commands utilized to clean up iRODS/Django sync. I need them merged into release 1.10.0
> Commands to fix iRODS/Django sync

- hs_swat_modelinstance/models.py
@pkdash could you please review this small PR.  Now when a new version of a SWAT Model Instance is created, it does not try to validate the value, because there is no value to validate.
> [#2092] doesn't try to validate if value is blank

- theme/management/commands/add_quota_avu.py
Add exception handling and debugging output to add_quota_avu command
> add exception handling

- hs_tracking/management/commands/stats.py
Modified user and resource logging fields to ensure logstash fingerprints are unique=, see https://github.com/hydroshare/hydroshare/issues/2082
> Modification to hs_tracking fields

- hs_modflow_modelinstance/tests/test_modflow_modelinstance_metadata_extraction.py
> [#1428] Wrote Tests for DIS File: GridDimensions, StudyArea, StressPeriod

- hs_core/hydroshare/utils.py
- hs_core/views/__init__.py
- theme/management/commands/dump_user_quota.py
- theme/management/commands/email_users.py
- theme/management/commands/update_used_storage.py
- theme/migrations/0008_auto_20170622_2141.py
- theme/models.py
- theme/static/js/create-resource.js
- theme/templates/accounts/profile.html
- theme/utils.py
- theme/views.py
@pkdash This PR includes all changes related to quota that are needed when working with @mjstealey for quota script integration as well as fixing display of validation errors on create resource page (which is a regression error that needs to be fixed). @mjstealey and I have gone through the whole workflow on alpha and it appears to work as expected, so I am creating this PR to get the code review started. I am creating this PR against develop branch for code review, but can create a corresponding PR against release 1.11 branch as needed when I get a +1. Please code review this PR when you have time. Thanks.
> 1566 quota

- hs_access_control/migrations/0022_resourceaccess_download_agreement.py
- hs_access_control/migrations/0022_resourceaccess_require_download_agreement.py
- hs_access_control/models.py
- hs_core/models.py
- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- hs_core/tests/api/native/test_set_download_agreement.py
- hs_core/views/__init__.py
- hs_core/views/resource_rest_api.py
- theme/static/js/generic-resource.js
- theme/static/js/hs_file_browser.js
- theme/static/js/modals.js
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/modals.html
This work has been deployed on riverdev for testing. 
Refer to issue: #1756 
TO DO:
> License agreement option for file/bag download

- hs_core/discovery_form.py
- hs_core/hydroshare/users.py
- hs_core/search_indexes.py
- hs_core/tests/api/rest/test_resource_list.py
> Case insensitive searching and indexing in UI and API

- hs_core/tests/api/rest/test_resource_flags.py
- hs_core/tests/api/views/test_set_resource_flag.py
- hs_core/views/__init__.py
> Adding "flag" as a possible param for the flag endpoint

- theme/static/css/hydroshare_core.css
- theme/static/js/create-resource.js
- theme/static/js/hs-file-icons.js
> [#2107] Added .shp file icon

- hs_core/hydroshare/utils.py
- hs_core/tests/api/native/test_change_quota_holder.py
- hs_core/tests/api/views/test_change_quota_holder.py
- hs_core/views/__init__.py
- quota-info.md
- theme/management/commands/dump_user_quota.py
- theme/management/commands/email_users.py
- theme/management/commands/update_used_storage.py
- theme/migrations/0008_auto_20170622_2141.py
- theme/models.py
- theme/static/js/create-resource.js
- theme/templates/accounts/profile.html
- theme/utils.py
- theme/views.py
@pkdash @mjstealey I created another PR for quota against release 1.11 branch just for convenience in case quota needs to go in release 1.11. I kept the other corresponding PR against develop open for now since it has code reviews embedded. @pkdash Feel free to code review against either PR as you like, @mjstealey I'll leave it up to you which PR you will merge and close depending on whether quota implementation can go in to release 1.11 or not.
> 1566 quota - release 1.11

- hs_app_netCDF/receivers.py
- hs_app_timeseries/receivers.py
- hs_geographic_feature_resource/receivers.py
This fixes the urgent issue @zhiyuli reported, #2248 and needs to go in as a hotfix in order for @zhiyuli 's presentation in the workshop this week to go as planned. @aphelionz Can you code review it whenever you get a chance? @mjstealey I created this PR against master for the hotfix.
> 2248 specific metadata

- hs_core/hydroshare/users.py
> Passing through malformed coverages in the list endpoing

- hs_modflow_modelinstance/receivers.py
> Bug Fix: incorrect method call

- hs_core/views/__init__.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
> Adding Coverages to Resource List View

- hs_core/models.py
- hs_core/views/__init__.py
> Fixing ability to set a public resource back to discoverable

- theme/static/js/hs_file_browser.js
- theme/static/js/resourceLandingAjax.js
Also
- Fixed a bug causing a script to fail when selector returned no matches.
> [#2255] Double click to download files

- hs_tracking/management/commands/stats.py
- hs_tracking/middleware.py
- hs_tracking/models.py
- hs_tracking/tests.py
Modifications to the logging format to resolve logstash parsing issues.
> 2267 app log format

- hs_file_types/views.py
This is a hotfix for release candidate 1.12.
> Fix for page reload on file type setting in composite resource-HOTFIX

- theme/static/js/hs_resource_table.js
Found and fixed a bug causing error when trying to delete published resources from My Resources page.
> [#2288] Fix for conditional check of published resources.

- README.md
> Update README to link to contributing.rst

- hs_core/__init__.py
- hs_core/views/resource_folder_hierarchy.py
- hs_file_types/models/base.py
@aphelionz Can you review this PR as well in conjunction with code review for django_irods submodule PR https://github.com/hydroshare/django_irods/pull/32? Once the django_irods PR is merged, I will update this PR with the new SHA reference to django_irods submodule. The code included in these two PRs are deployed on park for @horsburgh to test against. I am confident it should now work.
> 2299 create resource unicode

- hs_core/models.py
@aphelionz Can you review this small PR? I'd like to get it merged into develop now rather than waiting until Open With design and implementation is sorted out since this will invoke the server script to expose composite resources with netCDF file type to hyrax server when they are made public from private.This will get back end ready before we sort out the front end to expose hyrax service on the front end via Open With interface.
> 2250 hyrax composite

- theme/views.py
@dtarb This is the new confirmation message as you specified in issue #2333:
If you approve this message (exactly as you specified in issue #2333), and I'll merge this PR after Jenkins gives a green check since the only change to the code is the messaging.
> issue #2333 - fix email confirmation message

- hs_core/discovery_form.py
This addresses issue #2308 according to the fix formula in that PR.
> Fix search box.

- hs_modflow_modelinstance/models.py
- theme/templates/resource-landing-page/title-section.html
Small change to show MODFLOW ModelInstance warnings only to users who are either `owner` or `editor`
> 2370 modflow warning message for owners

- theme/static/css/hydroshare_core.css
- theme/static/js/custom.js
- theme/templates/accounts/profile.html
- theme/templates/resource-landing-page/top-right-buttons.html
- If the resource is not Public the Publish button is now hidden.
- If the resource is Public, but the profile is incomplete, the button is grayed out and a helpful message is shown when hovered over.
- Title field in Profile page is now a required field.
- Minor profile page style adjustments
> [#2291] Publish button update

- hs_core/discovery_form.py
This fixes several search box anomalies, notably, missing results when one searches for uncommon things like first name.
> 2308 fix missing discovery results

- hs_tools_resource/migrations/0012_auto_20171110_1559.py
- hs_tools_resource/models.py
- hs_tools_resource/patches/missing_unique_constraint.py
- hs_tools_resource/tests/test_web_app.py
This is the replacement PR for issue #2408
> 2408 add unique constraints to webapp models

- hs_core/search_indexes.py
- hs_core/views/discovery_json_view.py
- hs_core/views/discovery_view.py
@aphelionz @martinseul This is the performance improvement mentioned on the call.
> Performance improvement by avoiding hitting Django database

- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/top-right-buttons.html
- Fixes overlapping tooltips.
- Disables the button for Discoverable resources.
> [#2435][#2436] Add to My Resources button issues

- hs_core/views/discovery_json_view.py
@aphelionz @martinseul One bug fix of Zhaokun's didn't get into last PR. This corrects a problem with mapping that causes every box to show up when you click on one marker.
> Fix bug in mapping due to missing short_id field.

- theme/static/js/hs_resource_table.js
Fixes My Resources page search box not working with the new filters.
> [1.14RC] Fix for search box in My Resources page.

- hs_tools_resource/app_launch_helper.py
deployed and verified on riverdev
> [Hotfix for 1.14RC] -- 2493 public resource landing page failed to open without signing in

- hsctl
- irods/use-local-irods.sh
This removes a useless, non-functional SOLR index step inside ./hsctl rebuild
> Remove useless index step

- .gitignore
Just some additions to gitignore
> new gitignore changes

- irods/use-local-irods.sh
- theme/forms.py
- theme/templates/accounts/sign_up_form.html
Sorry, this should have been merged to master. @Maurier Please approve one more time.
@hyi We have a plan to implement the latest version of recaptcha by tomorrow
> Hotfix disable captcha 2

- theme/migrations/0012_1_15_RC_merge.py
I just manually added it, but made sure to use the same name as the hotfix so we don't get duplicate migration files
> [HOTFIX] - add the merge migration

- theme/static/css/hydroshare_core.css
> [#2474] Fix for appearing horizontal scrollbars

- hs_core/management/commands/ingest_irods_files.py
- hs_core/management/commands/repair_resource.py
- hs_core/management/utils.py
> Keep management commands from crashing unexpectedly in unusual situations.

- .github/PULL_REQUEST_TEMPLATE.md
1. Review the text of this pull request description and let me know if you think this will work. If this PR is approved, the text will be auto-inserted.
Note that I'm not I'm not necessarily writing an ISSUE template right now.
> Adding blank issue and pull request templates

- hs_core/templates/pages/create-resource.html
1. Sign in -> Click Create Resource -> Click the link in the top blue message box "When you click Create Resource, the files will be uploaded to the HydroShare server. Click here to learn more about next steps to share and formally publish your data."  Validate the link takes you to "https://help.hydroshare.org/creating-and-managing-resources/formally-publishing-data/"
> [#2653] update the create resource help page

- hs_core/models.py
1. Add a new creator to a resource with one or more identifiers. Edit the same creator and remove all the identifiers and save the changes. All the identifiers should have been deleted for that creator.
2. Repeat the above for a contributor.
> Fix for creator/contributor identifier bug

- theme/static/js/discover.js
This from @xuezhaokun : a fix for map list refresh problem on discovery map.
> Add javascript to reset map list.

- hs_core/tasks.py
> [#1867] url formatting bug fix

- hs_dictionary/migrations/0005_reimport_universities.py
1. Navigate to sign-up and type "Brigham" in the organizations field.  Validate one of the suggestions includes "Brigham Young University Idaho"
> [#2673] add migration for reimporting universities

- hs_rest_api/permissions.py
- hs_rest_api/resources/file_metadata.py
1. With this branch active, visiting /hsapi/ should no longer produce a KeyError
> 1.15 rc2 hotfix keyerror

- theme/templates/base.html
1. CUAHSI marketing should be able to see conversions upon signups that come from their adwords campaign.
> Adding adwords conversion code

- hs_core/templates/pages/metadata_terms.html
1. Changes are to a static page, just pull up the /terms page and ensure the changes are there.
> 2676 resource type terms

- theme/static/js/hs-file-icons.js
- theme/static/js/hs_file_browser.js
> 2573 agg icons composite

- hs_file_types/models/base.py
1. Edit a composite resource, select a file and add at least two key/value extended metadata.  Edit one.  Remove one.  If you're able to do all of these actions, it works.
> [#2733] - bug fix for key-value modal forms

- hs_core/tasks.py
1. When a user create a resource using files from a user zone using copy option, the user's quota will be increased to include the new added files from the user zone.
> fix the issue that quota from user zone is not accounted for

- hs_core/tasks.py
- hs_core/tests/api/native/test_folder_download_zip.py
- hs_core/tests/data/multi_sites_formatted_version1.0.refts.json
1. Create a resource with a referenced time series aggregation.  Right click the refts aggregation and select download.  Ensure the downloaded file is a zipped file that contains the refts.json file along with the resmap and meta xml files.
> 2567 download agg

- hs_core/tasks.py
When you are over-quota, in the over-quota warning email you receive, the user's full name if available will be used in the email salutation rather than the user's username.
> changed salutation

- hs_core/admin.py
- theme/templates/resource-landing-page/title-section.html
1. Find a resource with newlines in the abstract, such as https://hydroshare.org/resource/7cb87c110c074c20970a0dc3c36bbd9e/
2. View source
3. Copy the ld+json string into https://json-ld.org/playground/
4. Verify its validity
Fixes #2768 
Fixes #2770 
Fixes #2772
> Fixing JSON-LD errors and adding fields back to admin

- theme/templates/resource-landing-page/subject.html
2. Edit the resource
3. Under the text area of Abstract, verify the label is "Subject Keywords"
> Change "Subject" to "Subject Keywords"

- hs_core/tasks.py
- theme/management/commands/fix_user_quota_model.py
Added check to only further check whether user is over quota when user has a UserQuota foreign key relation; added debug logging when exception is raised from email sending or when user does not have a UserQuota foreign key relation; added a management command to fix UserQuota foreign key relation for users which can be run as needed, e.g., when we get to know some users are missing UserQuota relation from the log.
> fix issue #2778

- hs_core/templates/pages/create-resource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/create-resource.js
1. Initiate a Create a new resource action from "My Resources".
2. In the page where I create a new resource, scroll to the bottom of the page. On the opposite of the "Create Resource" button, find the "Cancel" button.
3. Click the "Cancel" button, the browser goes back to the "My Resources" page.
> Create a Cancel button to the opposite of the "Create Resource" button.

- theme/templates/resource-landing-page/title-section.html
For issue https://github.com/hydroshare/hydroshare/issues/2801
1. Choose any resource with multiple keywords and properly set box temporal coverage
2. View source
3. Look at the keywords in the JSON-LD. Are they all on one line?
4. Look at the box coverage. Is it in the format "##.####, ##.#### ##.####, ##.####" as in four four-decimal-point numbers in comma-separated pairs, separated by a space?
> Hotfix jsonld 2

- hs_app_timeseries/forms.py
- hs_app_timeseries/migrations/0003_auto_20180621_0159.py
- hs_app_timeseries/models.py
- hs_app_timeseries/tests/test_timeseries_metadata.py
- hs_core/testing.py
- hs_file_types/tests/utils.py
1. Create a TimeSeries resource by uploading a SQLite file. 
2. In the resource edit mode, update the Processing Level metadata field 'Processing level code' by entering a string value (e.g., QC-123). This update should be successful.
> TimeSeries metadata attribute data type change

- hs_core/tasks.py
Fixes #2851
1. Quota emails should go out weekly now instead of daily.
> Changing quota emailing to weekly

- theme/templates/resource-landing-page/subject.html
1. Create a new resource, check the "Subject Keywords" is displayed.
2. View an existent resource, check the "Subject Keywords" is displayed.
> Change Subject to "Subject Keywords"

- hs_file_types/models/base.py
1. Create a multi-file aggregation (e.g., NetCDF aggregation)
2. Download the aggregation folder. 
3. Unzip the downloaded file. Open the file ending with '_meta.xml' and you should find the path to aggregation xml map file (file ending with '_resmap.xml') is correct.
> Fix for aggregation file path in meta xml file - needed for composite resource phase-2

- hs_file_types/utils.py
1. add a timeseries .csv file to a resource and verify it is not auto aggregated as a timeseries.
> [#2502] no longer auto aggregating csv files

- .github/RELEASE_CHECKLIST_TEMPLATE.md
1. This is a template change, no tests are necessary.
> Add template for Release Checklist

- Dockerfile
- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/tasks.py
- hs_core/tests/api/native/test_irods_user_zone_federation.py
- hs_core/views/__init__.py
- hs_tools_resource/utils.py
- hydroshare/local_settings.py
> fix merging conflict from master to develop

- theme/views.py
> pull fix from develop to master to get ready for hotfix release

- theme/views.py
> Master to develop 2018 09 24

- django_irods/views.py
- hs_core/tasks.py
- hs_core/templates/pages/genericresource.html
- hs_core/tests/api/native/test_folder_download_zip.py
- hs_core/views/__init__.py
- hs_file_types/views.py
- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
1. Create a Composite Resource with a folder, a mutli file aggregation, a single file aggregation and a single
2. Right-click a folder, ensure there is an option to `Download Zipped` and no option for `Download`.  Click `Download Zipped` and validate the contents.
3. Right-click a multi file aggregation, ensure there is an option to `Download Zipped` and no option for `Download`.  Click `Download Zipped` and validate the contents include the aggregation metadata files
4. Right-click a single file aggregation, ensure there is an option to `Download Zipped` and anoption for `Download`.  Click `Download Zipped` and validate the contents include the aggregation metadata files.  Click `Download` and ensure the single file is downloaded unzipped.
2. Right-click a single file, ensure there is an …
> 2880 add download zipped functionality

- hs_core/receivers.py
1. Update the abstract with more than 5000 characters and validate the error message reports the character limit with the number of characters submitted.
> [#2883] - update receiver to include form errors

- theme/templates/resource-landing-page/citation.html
1. Verify the tooltip message matches the ticket description
> [#2841] - update tooltip grammar

- theme/static/js/custom.js
1. View an existent resource that has a subject keyword. 
2. Click on the text of the keyword. 
3. A search (discover) page is launched with the keyword as search content.
> Make keyword searchable in resource viewing mode.

- theme/static/js/profile.js
1. Click pencil icon to edit a user profile.
2. Make any changes, any possible changes. (DO NOT SAVE)
3. Click "Cancel" button, the profile page reload.
4. Go to step 1, observe all the changes that were made are not preserved.
> 2873 Cancel doesn't reset in profile edit

- hs_rest_api/urls.py
1. Ensure you can create/edit a referenced file using the hsapi path.
> [#2797] - add urls for restapi

- hs_core/views/resource_folder_hierarchy.py
> [#2502] - turn down logging on file browser requests for metadata files

- hs_core/templates/pages/create-resource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/create-resource.js
- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/resource-header.html
1.  My resources->Create New
2. Create resource page
2.1.  On the right side of "Create Resource" page title, you see a grey line statement appended with a light blue icon. A popover automatically is open and shown. DOI information are described.
2.2.  The first "Create Resource" button is removed.
3. Click "Create Resource", resource landing page header shows DOI. On the right there is "cite" link which brings to the citation portion.
N/A
Liza will take care of that once this is on beta.
Passed
Passed
> DOI UX change

- Dockerfile
- hs_app_netCDF/models.py
- hs_core/testing.py
- hs_core/tests/api/rest/test_create_resource.py
- hs_file_types/tests/test_netcdf_metadata.py
- hs_file_types/tests/test_view_functions.py
- hs_file_types/tests/utils.py
- scripts/templates/docker-compose.template
1. Check this branch out and run `./hsctl rebuild -db` and ensure it builds properly
> Dockerfile and Docker compose updates for 1.15.6

- hs_composite_resource/models.py
- hs_core/hydroshare/resource.py
- hs_file_types/utils.py
1. Create a folder inside a composite resource add a mutli file aggregation (geo feature will work).  Validate the aggregation uses the folder the files were placed in.  Validate you cannot upload nor move a file into the aggregation.
> [#2502] HOTFIX - fix the trailing slash on empty aggregation folders

- hs_core/templates/pages/create-resource.html
1. Run through all types of resource type, click create button, verified a resource is created.
> 2936 Create Resource button missing for two resource types

- hs_core/templates/pages/create-resource.html
- theme/templates/resource-landing-page/resource-header.html
> hotfixes for DOI issues found in 1.16 beta

- theme/static/js/hs_file_browser.js
1. add a file that ends with "zip" not ".zip".  Ensure you cannot unzip the file.  Try to unzip a real zip file, Ensure it unzips.  Do the same with aggregation files.
> [#2947] - add . to endswith check

- .github/RELEASE_CHECKLIST_TEMPLATE.md
> add maps api key check to checklist

- hs_core/tasks.py
1. Change the metadata of a file (content metadata tab).  Download the file as zipped, open the zip and verify the metadata changes are reflected in the _meta.xml file.
> [#2965] - bring back code to generate aggregation metadtata on download

- theme/static/js/generic-resource.js
1. refer to GitHub issue https://github.com/hydroshare/hydroshare/issues/2820
> 2820 metadata name field html not handled properly

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/models.py
1. unzip a file and rename the resulting folder.  Verify no error is returned and the folder is renamed.
> [#2978] - bug fix to only list files within folder

- Dockerfile
- hs_app_netCDF/admin.py
1. Rebuild the project (with existing database, don't create new database).  If it starts up then it's working.
> [#2863] unregister netCDF admin page

- hydroshare/settings.py
1. Look at the logs at startup and validate see you don't see any DEBUG level messages in django.template
> [#2863] - suppress logging for variable check in templates

- hs_script_resource/page_processors.py
1. Load a resource page with resource type ScriptResource.
> [#2863] - uplift deprecated field in scriptresource

- hs_core/forms.py
- theme/static/js/coverageMap.js
- theme/static/js/hs_file_browser.js
- theme/static/js/resourceLandingAjax.js
1. add a file aggregation with special coverage. Validate the coverage is updated at the resource level on upload. Go into edit mode, click the aggregation and look at spatial coverage under Content Metadata. Validate it is correct. Update resource level spatial coverage. Validate spatial coverage on the aggregation was not updated with the resource level coverage.
> Hotfix spatial coverage

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/views/utils.py
1. create a resource, upload one or more files.  Zip one or more of those files on your OS, then upload the zip.  Use the rest api or hs_restclient to call the unzip function with overwrite flag set to true.  Verify the files in the zip overwrite files outside of the zip.
> [#2860] - remove unnecessary and broken overwrite code in django_link

- hs_core/models.py
- hs_core/tests/api/rest/test_resource_science_meta.py
> [WIP 3027] remove if statement that prevent from updating coverage via rest api

- Dockerfile
- theme/admin.py
1. Login to the admin panel, navigate to SiteConfiguration and change the site version.  Save, navigate to the homepage and verify your change persists.
2. Login to the admin panel, navigate to HomePage and setup a Warning message.  Save, navigate to teh homepage and verify your warning shows up.
> [#3025] - enable homepage and siteconfiguration

- hs_core/forms.py
- hs_core/models.py
- hs_core/tests/api/native/test_core_metadata.py
- theme/static/js/coverageMap.js
1. Add box coverage across the dateline and verify it displays and saves to the resource.
> [#3012] - remove check on west lon > east lon

- hs_core/templates/pages/genericresource.html
- hs_tools_resource/app_launch_helper.py
- theme/static/js/hs_file_browser.js
1. Setup a webapp for a single file aggregation (.refts.json).  Add a launching pattern on both the file level and aggregation level.  for the file extension the aggregation's extension (.json)
2. Setup a webapp for a multi file aggregation (.nc).  Add a launching pattern on both the file level and aggregation level.  for the file extension, use the main file extension (.nc)
3. Add both webapps to your open with list
4. Create a composite resource with the aggregation types the two web apps were created with.
5. Right click on the multi file aggregation, verify the correct web app shows and launches correctly.  Open the multi file aggregation folder, right click on the files inside and verify the aggregation level web app doesn't show.  Verify the file extension launching pattern shows. …
> [#2980] separate file extension an daggregation matching logic

- hs_core/management/commands/delete_hanging_logical_files.py
- hs_file_types/migrations/set_aggregation_resource.py
> Hotfix logicafile migration

- irods_browser_app/views.py
Fixed issue #3030 which is a regression. With this fix, adding files from iRODS to existing resources should work. Have updated beta for testing the fix. Now adding files from iRODS to existing resources should work on beta.
> fixed the issue #3030

- hs_tools_resource/models.py
- hs_tools_resource/tests/test_web_app.py
1. Create a web app and copy it.
> [#3065] - fix metadata copy methods

- theme/static/js/profile.js
> Adding parameter "true" to reload() method to force reload on firefox

- hs_core/hydroshare/utils.py
1. After logging into HydroShare, edit your profile page and update your middle name, e.g., add a middle name or remove middle name, and save your profile. Then go create a resource, make sure the updated middle name from your profile edit is reflected in author/creator display on resource landing page and my resources page.
> fixed issue #2276

- hs_core/autocomplete_light_registry.py
- hs_core/templatetags/hydroshare_tags.py
- theme/templates/includes/profile-link.html
Further fix to issue #2276, mainly on display of owners to take into account middle name if available.
> further fix to issue #2276

- hs_app_netCDF/forms.py
- hs_app_netCDF/models.py
- hs_app_netCDF/page_processors.py
- hs_app_netCDF/templates/pages/netcdfresource.html
- hs_app_timeseries/page_processors.py
- hs_app_timeseries/templates/pages/timeseriesresource.html
- hs_core/page_processors.py
- hs_core/templates/pages/create-resource.html
- hs_core/templates/pages/genericresource.html
- hs_geo_raster_resource/page_processors.py
- hs_geo_raster_resource/templates/pages/rasterresource.html
- hs_geographic_feature_resource/page_processors.py
- hs_geographic_feature_resource/templates/pages/geographicfeatureresource.html
- hs_script_resource/forms.py
- hs_script_resource/templates/pages/scriptresource.html
- ref_ts/templates/pages/reftimeseriesresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/quota.html
> 3141 rc rebase

- hs_file_types/models/geofeature.py
> 2946 improve geofeature parsing error msg 

- hs_core/templates/pages/my-resources.html
- hs_core/views/__init__.py
- theme/static/js/hs_resource_table.js
First pass, still need to clean up JavaScript logic for calculating "Filter" counts. Also, requesting of the team that I add pytest and then write unit/functional tests in a separate PR. It's been enough years since I coded JS/frontend that I lost count, so if I did something silly, let me know!
Fixes https://github.com/hydroshare/hydroshare/issues/2870
> Add pagination to resources page

- hs_app_netCDF/forms.py
- hs_app_netCDF/models.py
- hs_app_netCDF/page_processors.py
- hs_app_netCDF/templates/pages/netcdfresource.html
- hs_app_timeseries/page_processors.py
- hs_app_timeseries/templates/pages/timeseriesresource.html
- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- hs_geo_raster_resource/page_processors.py
- hs_geo_raster_resource/templates/pages/rasterresource.html
- hs_geographic_feature_resource/page_processors.py
- hs_geographic_feature_resource/templates/pages/geographicfeatureresource.html
- hs_script_resource/forms.py
- hs_script_resource/templates/pages/scriptresource.html
- ref_ts/templates/pages/reftimeseriesresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
Bringing master back into develop after the 1.19 release.
> Master to develop

- hs_core/models.py
- theme/static/css/hydroshare_core.css
- theme/templates/resource-landing-page/readme-file.html
#3176 Sets a conditional which makes the template use an HTML `pre` tag as container to render the content of a readme.txt file.
readme.md files are still displayed as before since the `pre` tag would otherwise add unnecessary spacing between HTML elements rendered.
**Before:**
**After:**
File used to test: 
[readme.txt](https://github.com/hydroshare/hydroshare/files/2890675/readme.txt)
> [#3176] Use pre tag to properly render readme.txt files.

- hs_core/views/__init__.py
> Set default per page very high

- hs_app_netCDF/forms.py
- hs_app_netCDF/models.py
- hs_app_netCDF/page_processors.py
- hs_app_netCDF/templates/pages/netcdfresource.html
- hs_app_timeseries/page_processors.py
- hs_app_timeseries/templates/pages/timeseriesresource.html
- hs_core/page_processors.py
- hs_core/templates/pages/create-resource.html
- hs_core/templates/pages/genericresource.html
- hs_geo_raster_resource/page_processors.py
- hs_geo_raster_resource/templates/pages/rasterresource.html
- hs_geographic_feature_resource/page_processors.py
- hs_geographic_feature_resource/templates/pages/geographicfeatureresource.html
- hs_script_resource/forms.py
- hs_script_resource/templates/pages/scriptresource.html
- ref_ts/templates/pages/reftimeseriesresource.html
- theme/static/css/hydroshare_core.css
#3141 Contains layout fixes for resource specific content of deprecated resource types.
> [#3141] Fix layout issues concerning resource specific metadata cutoff

- hs_core/views/utils.py
1. The URL example shown in issue #3175 should be treated as a valid URL with this fix.
> make url validator more robust - fix issue #3175

- theme/templates/base.html
> Added heapmetrics script (code is from heapmetrics)

- hs_core/models.py
- hs_core/templates/pages/my-resources.html
- hs_core/tests/api/native/test_utils.py
- theme/templates/resource-landing-page/resource-header.html
1. Open a resource landing page, verify last updated isn't now.
> [#3206] - use modified date from metadata for last updated display

- hs_core/templates/pages/my-resources.html
- hs_core/templates/search/search.html
> [#2638] Edit to text on My Resources

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
As described in #3136:
**After:**
----------------
> [WIP][#3136] Move Copy Resource Bag button to file browser's toolbar

- hs_core/models.py
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/references.html
When adding or editing Related Resources entries:
- Update the text in the selection dropdown to user friendly strings
- Adjust spacing of input fields
**Before:**
----------------------
**After:**
----------------------
Change of text:
Spacing:
Text update:
> [#2763] Update text in Add/Edit Relation modals

- hs_app_netCDF/templates/pages/netcdfresource.html
- theme/static/css/hydroshare_extends.css
- theme/templates/generic/includes/comments.html
- theme/templatetags/comments_tags.py
Hides some items from the UI in the Comments section.
**Before:**
----------------
**After:**
----------------
> [#3183] Hide items in Comments section

- hs_core/templates/pages/genericresource.html
- theme/static/js/hs_file_browser.js
- theme/templates/resource-landing-page/modals.html
Implements enhancements described in https://github.com/hydroshare/hydroshare/issues/2813#issuecomment-450982967
* Once the user clicks Add metadata, the right-side panel should automatically open the template to fill in the metadata
* By default when an unsupported file-type has been highlighted, the Add Metadata green icon should also appear in the right side panel so it is less hidden behind a right click.
> [#2813] Add Metadata/Set content type - Enhancements

- hs_core/templates/pages/create-resource.html
- hs_core/templates/pages/my-resources.html
- hs_core/templates/search/search.html
- theme/static/css/hydroshare_core.css
#2989 Sets appropriate cursor settings for clickable elements. 
Also changes the appearance of tooltip icon in Discover page to make it consistent with the one in Create Resource page. The position of the tooltip has been changed to prevent it from being cut off. Minor alignment changes too.
**Before:**
----------------
**After:**
----------------
Update tooltip icon style for consistency
> [#2989] Update cursor settings for various elements

- theme/static/js/generic-resource.js
- theme/static/js/resourceLandingAjax.js
Updates referenced Ids in logic for populating keywords form input.
Can be tested at http://playground.hydroshare.org/
2. Add some keywords.
3. Refresh the page.
4. They keywords should persist.
> [#3204] Update referenced Id in keywords form input

- hs_app_timeseries/tests/Invalid_Date_Numeric.csv
- hs_app_timeseries/tests/Invalid_One_Data_Row.csv
- hs_file_types/models/timeseries.py
- hs_file_types/tests/data/valid_two_data_rows.csv
- hs_file_types/tests/test_timeseries_metadata.py
1. Minimum data rows test: Create a composite resource. Upload a timeseries CSV file that has at least two rows of data. Create a timeseries aggregation from this uploaded CSV file. You should see a timeseries aggregation got created. 
2. Date data format test: Upload a timeseries CSV file (to the composite resource you created above) which has none of the data values for the date/time column (1st column) in numeric format (e.g. of date in numeric format: '20180330'). Create a timeseries aggregation from this uploaded CSV file. You should see a timeseries aggregation got created.
> Additional timeseries csv file validation

- hs_core/templates/pages/my-resources.html
- hs_core/views/__init__.py
- theme/static/js/hs_resource_table.js
Per e-mail discussion, hold pagination from this release.
> Noissue revert pagination

- hs_core/models.py
- hs_core/tests/api/rest/test_custom_scimeta.py
- hs_core/tests/api/rest/test_resource_science_meta.py
- hs_core/views/__init__.py
- hs_core/views/resource_metadata_rest_api.py
1. Add funding_agencies and relations via the rest api (try using swagger!)
> [#3180] - add relations and funding_agencies updating via rest api

- theme/static/js/hs_file_browser.js
This PR fixes the use of a conditional in the front end that indicates when the download method should zip the files.
1. Create a resource and add some files.
2. Click on the various download files buttons and confirm they files get downloaded.
3. Now check the box to require license agreement before download.
4. Try to download files again.
5. Confirm that files do download through the download agreement modal window as well.
> [#3251] Fix download through license agreement

- hs_core/models.py
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/references.html
Cherry pick the missing commits
> 3185 retry

- theme/templates/includes/res_type_col.html
1. In order to test this you have to have at least one Geo Feature Resource. Go to my resources page and verify that you can see resource type icon for each of the geo feature resources.
> [HOTFIX] Fix for missing geo feature resource type icon

- theme/templates/accounts/profile.html
- theme/views.py
1. To see profile page loading time improvement locally, you need to have at least 50 resources. Using your current branch make a note of the loading time for profile page. Then checkout 3254-profile-page-optimization branch and restart hydroshare. Go to profile page and compare the loading time with the previously noted page loading time. You should see 40-50% improvement.
> Profile page optimization

- hs_core/views/utils.py
…tiple contenttype
1. Create couple of composite resources. Create couple of some other type of resources (e.g. web app).
-  To test filtering on creator (author): Add one or more creators to each of the resources. On my resources page, filter on author and verify that relevant resources are getting displayed.
- To test filtering on keywords (subject): Add one or more keywords to each of the resources. On my resources page, filter on subject and verify that relevant resources are getting displayed.
> [HOTFIX-RC-1.21] My resources filter fix

- hs_collection_resource/page_processors.py
> [HOTFIX-RC-1.21] parameter fix for collection resource

- Dockerfile-defaultworker
- Dockerfile-defaultworker.template
- Dockerfile-hydroshare.template
- local-dev-first-start-only.sh
- local-dev.yml
1. Please following this document (is being built) https://docs.google.com/document/d/1_8ClNiIBVSEI3jY4UJKOWrV6uwKilKug-69LoVizezk/edit#
2. For Windows developer, this document is also updated: https://docs.google.com/document/d/1wIQEYq3OkWmzPTHeyGyjXLZWrinEXojJPBTJq7fczL8/edit
> For new local developer environment

- hs_core/views/utils.py
- theme/templates/accounts/profile.html
- theme/views.py
1. Prefetching of metadata object as well as the needed metadata elements (e.g., creators) for listing of resources (my resources page and profile page) improves page loading. Once the RC-1.21 branch gets merged to develop, it would be possible to test this page loading improvement. At that time you can checkout the 'develop' branch. For this test you preferably need around 50 resources. When running the develop branch take a note of the page loading time for my resources and profile pages. Then checkout branch '3297-prefetch-metadata-resource-listing'. Restart Hydroshare. Go to my resources page and  profile page and compare page loading time that you got with the develop branch. You should see some improvement in page loading time over the develop branch.
> Prefetch metadata resource listing

- local-dev-first-start-only.sh
> [#3290] Fix remove bug for [PR #3921]

- .gitignore
- conf_irods/partial_build.sh
- config/hydroshare-config.yaml
- hsctl
- hydroshare/local_settings.template
- local-dev-first-start-only.sh
- local-dev.yml
- nginx/Dockerfile-nginx.template
- nginx/config-files/hydroshare-local-nginx.conf.template
- nginx/config-files/hydroshare-nginx.conf.template
- scripts/chown-root-items
- scripts/templates/init-defaultworker.template
- scripts/templates/init-hydroshare.template
- slow-start.sh
1. Please follow this link to test: https://docs.google.com/document/d/1_8ClNiIBVSEI3jY4UJKOWrV6uwKilKug-69LoVizezk/edit
> [#3290] Fix Git conflicted files error of #3307

- local-dev-first-start-only.sh
- scripts/chown-root-items
- scripts/templates/init-defaultworker.template
- scripts/templates/init-hydroshare.template
1. Please follow this link to test: https://docs.google.com/document/d/1_8ClNiIBVSEI3jY4UJKOWrV6uwKilKug-69LoVizezk/edit
> [#3290] Fix permission issue on PR #3318

- hs_core/views/__init__.py
- theme/static/css/hydroshare_core.css
- theme/static/js/generic-resource.js
- theme/static/js/hs_file_browser.js
- theme/static/js/resourceLandingAjax.js
[#3243] This PR extends the logic used to render metadata status changes of resource landing page to functionality regarding file uploads.
Note that the duration of the message has been incremented to 8 seconds (up from 3 seconds) to allow the message to be read.
A close icon ("x") has been added to the top right of this message to dismiss it.
1. Create a new resource.
2. Add a Title, Abstract and Keywords.
3. Add some content files.
4. At this point the metadata status message should appear indicating that the resource can be made Public.
> [#3243] Add response data during file upload to handle metadata status changes

- hs_core/templates/pages/collaborate.html
- hs_core/templates/pages/my-groups.html
- hs_core/templates/pages/my-resources.html
- theme/static/css/hydroshare_core.css
- theme/templates/pages/group.html
2. Fixes #2822  
Fixes #3013 
Fixes #3126
Fixes #3015  
Fixes #2826
Fixes #3054
> Fixed #2822, #3013, #3126, #3015, #2826

- hs_core/search_indexes.py
1. Create a resource with one or more authors with a non-ascii character (ì) in the name.  Make the resource public and make sure the newly public page loads.
> [#3324] specify utf-8 encoding for non-ascii characters

- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
- theme/static/js/resourceLandingAjax.js
- theme/templates/base.html
- theme/templates/resource-landing-page/modals.html
Fixes the following IE11 related issues:
#3226
#3225
#3223
#3222
#3221
#3220
#3218
#3217
These were all caused by a failure in our scripts due to the use of string literals. These are not supported in IE11.
Also fixes the issues below since they were related to IE11:
#3219 
#3216
> [#3226] IE11 Adding Contributors

- hydroshare/settings.py
1.  When deployed ensure local_settings overwrite settings.  (I tested this on beta testing HSWS_ACTIVATED)
> [#3330] - push local_settings import to bottom

- hs_core/hydroshare/users.py
- hs_core/hydroshare/utils.py
- hs_core/tests/api/native/test_create_resource.py
1. Enter a character like ì (hold alt and press 141, then release) in the middle name.  Create a new resource and verify you can create the resource!
> [#3294] - allow international characters in middle name

- hs_core/search_indexes.py
- hs_core/views/resource_rest_api.py
- theme/templates/pages/group.html
1. Open a resource, then find that resource on the discover page.  Verify the Last Modified date is not the date/time of when you opened the resource.
> [#3245] - use last_updated instead of updated

- theme/templates/resource-landing-page/references.html
Under References, the following relation types have been updated to human-friendly strings:
- "isVersionOf" now reads "This resource updates and replaces previous version"
- "isReplacedBy" now reads "This resource has been replaced by newer version"
2. Create a new version of it.
3. Check both resources' relations that were automatically created.
4. Verify that the strings used as relation types are human-friendly.
> [#3266] Update text of relation types

- hs_core/models.py
- hs_core/page_processors.py
- hs_core/templates/pages/genericresource.html
- theme/templates/resource-landing-page/abstract.html
- theme/templates/resource-landing-page/additional-metadata.html
- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/coverage.html
- theme/templates/resource-landing-page/credits.html
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/references.html
- theme/templates/resource-landing-page/resource-header.html
- theme/templates/resource-landing-page/subject.html
- theme/templates/resource-landing-page/title-section.html
1. There is no change in functionality from user perspective. The resource landing page should work as before. This is mostly code cleanup work which may give faster page load for resource landing page.
> Landing page context cleanup

- hs_core/page_processors.py
> Fixes #2777

- hs_core/page_processors.py
1. Test that dates in public and private work properly (dates before 1900 should crash)
> Revert "Fixes #2777"

- theme/static/css/hydroshare_core.css
> #fixes 3273

- hs_model_program/forms.py
- theme/templates/accounts/profile.html
Fixes https://github.com/hydroshare/hydroshare/issues/3267
Fixes https://github.com/hydroshare/hydroshare/issues/2915
1. Create Model Program Resource
2. Verify "L" is caps now
> GH Issue #3267

- theme/static/js/create-resource.js
> Fixes #2871
