hydroshare/hydroshare

- docs/DesignDocs/UserNameEmailRules.md
- ga_resources/templates/includes/ga_editable_toolbar.html
- hs_core/templates/400.html
- hs_core/templates/404.html
- hs_core/templates/500.html
- hs_core/templates/503.html
- theme/templates/accounts/account_login.html
- theme/templates/base.html
- theme/templates/pages/homepage.html
This is a relatively minor set of semantic changes done as I learn to push to github.  There is still an inconsistency in the accounts/login page where the title is "log in" and the button label inherits from the title.  I was unable to find where to change this in code and suspect it may be in the mezzanine pages.  This is issue #72 in HydroShare that came from issue #60 in HydroShare2.
> Sign in and sign out semantics

- hs_core/models.py
resource URL issue is fixed, now the resource's landing page's URL has the pattern http://hydroshare.org/resource/{id}. The fix is only one line addition, should be easily merged in automatically.
> issue [#41] fixed

- hs_docker_base/requirements.txt
- hydroshare/settings.py
- theme/templates/includes/checkbox_field.html
- theme/templates/includes/file_field.html
- theme/templates/includes/form_field.html
Update Profile on Alpha does not work.  When selecting the "Update Profile" button at the bottom of the page after updating one's profile, the page erases one's email address and requests that the issue be corrected, but it cannot be since the email field is not editable.
> Update Profile on Alpha does not work

- theme/templates/base.html
Change order of imports to work with ref_ts resource type
> [#9] change order of jquery-ui and bootstap calls in base.html

- hs_core/templates/pages/genericresource.html
- hs_core/views/__init__.py
[#217] Fixed an issue where some missing metadata elements where not listed in the alert message.
[#217] Fixed abstract field not showing up for non-generic resources
> [#217] Abstract and alert message hotfix

- hs_core/views/__init__.py
This was implemented before for the first pull request. But it seems the fix for delete_file() function was not  merged back to develop.
> [#197] fix the merge error

- hs_geo_raster_resource/forms.py
- hs_geo_raster_resource/page_processors.py
- hs_geo_raster_resource/raster_meta_extract.py
- hs_geo_raster_resource/receivers.py
Make raster metadata editing more flexible to accommodate various use cases, especially the future use case that allows users to edit metadata and update geotiff file accordingly, while fixing this issue. All changes are isolated in raster resource type app.
> fixed issue #324

- hs_app_netCDF/models.py
- hs_app_timeseries/models.py
- hs_core/models.py
- hs_core/templates/pages/create-resource.html
- hs_geo_raster_resource/models.py
- ref_ts/models.py
The names of the resource types supported in 1.5 release are changed as the following:
"Multidimensional (NetCDF)"
"Geographic Raster"
"Generic"
"Time Series"
"HIS Referenced Time Series"
> 321 change resource names

- hs_core/models.py
Resolved issue #328 - now HydroShare access control permissions are honored with this fix when downloading a resource or resource file from a URL. The change made is in django_irods submodule. I also added back the suggestion Calvin made for my last pull request, i.e., use self.owners.filter(pk=user.pk).exists() to check whether a request user is in the owners list. @ironfroggy Could you give a quick review for this pull request at your earliest conveience so that it can be merged in for the team to test on dev for release 1.5? Thanks!
> 328 download access control

- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
of system metadata summary for the requested resource.  The reason for
this was that the django-rest framework did not seem to like it when
the Accept HTTP header was set to application/zip.  Now, to get the
bag, or the science metadata, REST API users will need to fetch the
respective URL from the system metadata returned by GET
/hsapi/resource/<RESOURCE_ID>.
Addresses #345
> Refactor GET /hsapi/resource/<RESOURCE_ID> to always return a summary

- hs_core/hydroshare/hs_bagit.py
Only one parameter change to a function call. Everything works as expected now according to my testing. Should be safe to merge without code review, so set it as such hoping to get it merged ASAP since this bug needs to be fixed for NFIE release.
> fixed issue #409

- hs_core/templates/pages/my-resources.html
On the latest Dev deployment Owned by me does not work on the resources listing page.  @mjstealey pointed out that this link is http://dev.hydroshare.org/my-resources/?creator=<user>, but it should probably be http://dev.hydroshare.org/my-resources/?owner=<user>.  If I change the "creator" to "owner" in the URL it appears to work.
This may relate to filtering changes by @ironfroggy, so Calvin, please take a look.
> Owned by me link does not work

- hs_core/hydroshare/utils.py
remove old bag deletion code which caused wasteful executions when a resource is modified. It will not cause issues for NFIE release since the exception is ignored, but it will be nice to remove it. Have searched across the whole codebase and made sure it does not break any existing code including REST code. Also tested to make sure it works without causing any issues.
> remove old bag deletion code

- theme/templates/accounts/account_login.html
- theme/templates/accounts/account_password_reset.html
Since we've overloaded our own forms from Mezzanine there is some unexpected rendering when the DEBUG setting goes from True to False for some forms.
> extend from base.html instead of accounts/account_form.html

- hs_core/hydroshare/hs_bagit.py
- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/templates/pages/genericresource.html
- hs_core/views/__init__.py
- hydroshare/irods/ruleGenerateBagIt_HS.r
- irods_browser_app/static/js/irods.js
This branch is slated for NFIE hotfix release, and deployed on park for testing. Please review the code at your earliest convenience so that it can be merged into develop for the NFIE hotfix. It mainly resolves the performance issue with big resource metadata editing by doing on-demand bagging. Another two issues below are also resolved in this branch:
1. Hide the ajax spin wheel icon when irods browser gets invoked again - a minor bug fix.
2. bagit rule fix that stores generated bagit files such as bagit.txt and manifest files to HydroShare default resource rather than the default iRODS demoResc resource.
> 446 improve res mod perf

- docs/access-control.md
- docs/resource-hsaccess.txt
- hs_app_timeseries/page_processors.py
- hs_core/authorization.py
- hs_core/page_processors.py
- hs_geo_raster_resource/page_processors.py
- hs_model_program/page_processors.py
- hs_modelinstance/page_processors.py
- hs_rhessys_inst_resource/models.py
- hs_tools_resource/page_processors.py
Initially, access control was implemented inline in `hs_core/page_processor.py`. This is bad because:
1. It is not a correct implementation. For example, it does not inspect group permissions.
2. Bypassing the `ResourcePermissionsMixin` denies resources the opportunity to customize permissions.
Thus, this PR switches the implementation from an inline comparison to delegating to `ResourcePermissionsMixin`.
> Hsaccess integration

- hs_app_netCDF/page_processors.py
- hs_app_timeseries/page_processors.py
- hs_geo_raster_resource/page_processors.py
- hs_model_program/page_processors.py
- hs_modelinstance/page_processors.py
- hs_rhessys_inst_resource/models.py
- hs_swat_modelinstance/page_processors.py
- hs_tools_resource/page_processors.py
- ref_ts/views.py
This issue is indeed triggered by @ilangray's recent change to hs_core/page_processors.py, which now requires request object to be passed in when retrieving page context. The default value for request is None if nothing is passed in, hence the error. Passing in request object resolves this issue. I have made changes across the board to all specific resource apps (the only change is to pass in request object when retrieving page context, which should be risk-free). Although I think this fix is safe without risk, @pkdash, could you take a quick look to confirm? @mjstealey could you merge this pull request into develop after @pkdash give a +1 since the current develop branch raises errors when editing metadata for any specific resource type without this fix
> fixed issue #[515]

- hs_core/hydroshare/utils.py
- hs_core/views/__init__.py
- hs_core/views/utils.py
With this fix, the files loaded from iRODS file browser will be subject to file size limit (currently set to be 10GB) as files loaded from local disk. @rayi113 this means the 12GB NFIE file we have been experimenting with will trigger a file size error message when using it to create a HydroShare resource unless we increase the 10GB file size limit.
> fixed issue #510

- hs_core/templates/pages/genericresource.html
While verifying on dev, found although it works initially meaning linebreak is indeed retained after editing abstract to add linebreaks, the second time when editing the same abstract again, the additional HTML linebreak tag <br> shows in the abstract editing box. This can be further fixed by removing the Django linebreak filter being added to the abstract text displayed in the metadata editing box. This pull request includes this follow-up fix which, once merged, should fix this issue in subsequent edits to the same abstract as well.
> further fix to issue [#529]

- hs_app_timeseries/receivers.py
All 47 unit tests pass. Code coverage remains the same at 42%. Coverage report can be found at https://jenkins.renci.org/job/run-coverage-on-pull-request/Coverage_Report/
> fix for sqlite file validation to latest ODM2 schema

- theme/templates/accounts/profile.html
On the user profile page, the 'send mail to' link no longer shows email to users who are not logged in.
> [#319] Fix on 'send mail to' link

- hs_app_netCDF/page_processors.py
- hs_app_netCDF/templates/pages/netcdfresource.html
- hs_core/templates/pages/genericresource.html
@mauriel133 would you please have a look at this modification? Adding a new block in genericresource.html solves the problem that when it is editing mode, the header info text area is shown now.
> [#399] add new block in genericresource.html

- theme/templates/base.html
Sorry - the pull request I just created was wrongly against master rather than develop, so closed that one and recreating this one against develop. 
following @rayi113's suggestion with changing http to https for google api font url in base.html, I made this change on sandbox for testing. After checking following recommended security settings for my IE browser, I can reproduce this issue #563. I made sure I could see this unsecure content warning on IE before I made this change on sandbox, then after making this change, I don't see this unsecure content warning anymore on IE. So I am pretty confident this change will resolve this issue. Setting it to ready to use since it does not break anything with the only change from http to https in base.html.
> fixed issue [#563]

- hs_core/forms.py
- hs_core/templates/pages/genericresource.html
Replaced strftime() with isoformat() as @ironfroggy suggested to fix metadata update failure when the selected year is less than 1900. As a result, the start date and end date of the temporal coverage have the string representation format of YYYY-MM-DD as specified in ISO 8601 which is returned from isoformat() as opposed to the previous format of MM/DD/YYYY. I think this should be fine. With this fix, users can select year before 1900 and successfully save changes with metadata updated successfully. 
@ironfroggy @pkdash Could you review the code and raise issues if any?
> fixed issue [#592]

- hs_core/hydroshare/hs_bagit.py
- hs_core/views/__init__.py
Added resourceType and isPublic metadata to Hydroshare resources in iRODS when resource is initially created and change isPublic metadata accordingly when public/private status is changed for the resource from resource landing page. @pkdash could you review the code?
> Adding isPublic and resourceType irods metadata as outlined in [#621]

- theme/templatetags/ratings_tags.py
Follow-up fix to make ratings work. Without this fix, when anonymous users click on a public resource, a TypeError is raised. This needs to be merged for release 1.6.
> fixed the issue with anonymous users

- theme/templates/generic/includes/rating.html
Implemented presentation for ratings as suggested by @dtarb for issue [#611]. Main changes include: (1) move [+1]/[Withdraw +1] button in front of rating informational display (e.g., x others +1 this); (2) do not show +1 button for anonymous users but show rating informational display and show "You need to be logged in to rate this." as a url link that takes user to login page directly upon clicked. Since the currently rating presentation for anonymous users is broken, I'd like to target this PR for release 1.6. Would appreciate if someone can give a quick code review and feedback.
> fixed rating presentation especially for anonymous users

- Dockerfile
Set version for coverage at 3.7.1 as current default is 4.0 which breaks our jenkins workflow
> [#660] freeze version for coverage

- hs_core/templates/pages/help.html
resolved the issue [#457] to automatically populate the current release number on hydroshare help page using github api to retrieve tag_name from latest release, so that @mjstealey does not have to manually update release number after each deploy. Also updated the section "How do I comment or rate a resource" on help page since the current content does not reflect our current implementation, specifically, we do support rating a resource now. @mjstealey @rayi113 @dtarb please review the wording change I made and give me feedback if further changes are needed. @ironfroggy @pkdash it'd be great if you can give a quick code review to raise issues if any. I am targeting this PR for release 1.6 since it can be directly leveraged, at least save a little bit of work on @mjstealey's part.
> 457 update help dev status

- hs_core/serialization.py
This PR updates the ingest code so that after resource creation, we overwrite the owner's creator information for the resource with what was in the bag (back when the resource was last edited), rather than what is in the user profile (at the time of ingest).
> 655 migration override userprofile

- hs_app_netCDF/models.py
- hs_app_timeseries/models.py
- hs_geo_raster_resource/models.py
- hs_model_program/models.py
- hs_modelinstance/models.py
- hs_rhessys_inst_resource/models.py
- hs_swat_modelinstance/models.py
- ref_ts/models.py
I created a generic resource and three different model resources in my local development environment as the following figure:
After that, I tested the internal API to get the objects for each resource type with these steps:
[1] $  docker exec -ti hydroshare_hydroshare_1 python manage.py shell
[2] For Generic Resource, inside the shell I wrote the following:
In [1]: from hs_core.models import GenericResource
In [2]: GenericResource.objects.all()
Out[2]: [<GenericResource: Generic resource creation>]
The output was as expected which is the created Generic Resource: Generic resource creation.
[3] I did the same for the Model Instance resource (Figure below) and I got unexpected results. All the four created resource show up as Model instance resource.
[4] I did the same trial but this time …
> Error during using internal API for model resources

- hs_core/hydroshare/users.py
- hs_core/views/__init__.py
During migration dry-run process this morning, we found free text search for resource filtering raises AttributeError on dev, while working on www. You can reproduce this issue by typing in "error" into resource filter search box which produce 0 resources as expected on www, but generates Attribute Error on dev. Stack trace is copied below for reference:
```
Environment:
Request Method: GET
Request URL: https://dev.hydroshare.org/my-resources/?&text=rhye
Django Version: 1.7.8
Python Version: 2.7.6
Installed Applications:
(u'mezzanine.boot',
u'django.contrib.auth',
u'django.contrib.contenttypes',
u'django.contrib.redirects',
u'django.contrib.sessions',
u'django.contrib.sites',
u'django.contrib.sitemaps',
u'django.contrib.gis',
u'inplaceeditform',
u'django_nose',
u'django_irods',
u'theme', …
```
> free text search for resource filtering raises AttributeError on dev 

- hs_core/views/__init__.py
- hs_core/views/utils.py
- irods_browser_app/views.py
Fixed the issue [#615] by always terminating iRODS session process after creating one throughout irods file browsing process and monitored the irods server during irods file browsing operations through some complex workflow and made sure there is no additional iRODS process lingering around after irods file browser login and file browsing dialogs are dismissed. Also fixed an issue with iRODS Session exceptions not properly being displayed to resource creation and resource landing pages to inform users of exception errors when there is an issue with resource creation or when adding files to existing resources. This may provide more info to large 7GB file uploading issue if the issue comes from iRODS side as well as some other iRODS-related transfer failures.
> 615 irods file browser session processes

- hsctl
- nginx/config-files/hydroshare-nginx.conf
- nginx/config-files/hydroshare-ssl-nginx.conf
- nginx/maintenance_on.html
- nginx/run-nginx
Add nginx maintenance page that is displayed based on the existence of a **maintenance_on.html** file in the `hydroshare/static/` directory.
Two new command in the **hsctl** script.
```bash
$ ./hsctl --help
*** HydroShare Control script ***
usage: ./hsctl deploy      # deletes all database and container contents and deploys from scratch
usage: ./hsctl loaddb      # loads database specified in hydroshare-config.yaml into running container
usage: ./hsctl maint_off   # removes maintenance page (only if USE_NGINX = true)
usage: ./hsctl maint_on    # displays maintenance page (only if USE_NGINX = true)
usage: ./hsctl rebuild     # deletes hydroshare container contents only and deploys using exsiting database
usage: ./hsctl restart     # restarts the hydroshare container without rebuilding …
```
> [#676] nginx maintenance page

- hsctl
Changed hsctl deploy command to a hsctl rebuild --db to make deleting your database harder and less badly named.
Closes #581
> Rename database destroying "deploy" command

- hs_core/urls.py
- hs_core/views/user_rest_api.py
- hydroshare/settings.py
Enable OAuth2 support for REST API.  Also adds GET /hsapi/userInfo/ end point for use by HydroShare OAuth clients.
> [WIP] Add OAuth to REST API

- hs_core/hydroshare/resource.py
- hs_core/models.py
- hs_core/templates/pages/genericresource.html
- hs_core/views/__init__.py
In addition to required metadata elements, non-reference resource types must have content file(s) before such resource can be made public or discoverable.
> require content files for resource to be public or discoverable

- hsctl
- theme/templates/accounts/_signup_form.html
Have consulted @ironfroggy and made changes accordingly to avoid post-processing need for handling http vs https on recaptcha URLs. Tested on both local dev env and the dev.hydroshare.org VM and make sure relative URL works well in both environments. @ironfroggy Please give a quick review so that I can merge it in to get it ready for official release 1.6.2 deployment today.
> used relative recaptcha url

- hs_core/views/resource_rest_api.py
@yirugi Here is the PR for #752.  Thanks for bringing this to my attention.
> 752 Make resource type returned by /hsapi/resourceList reflect the actual type

- hs_access_control/models.py
- hs_access_control/tests/test_access_control.py
With these changes:
1. Resource non-owners can't downgrade privilege originally granted by someone else.
2. Most recent granted privilege for a resource for a given user always becomes the highest privilege for that user for that resource.
3. Inactive users can't be granted resource access permission.
> 716 access control permission fix

- config/hydroshare-config.template
- config/hydroshare-config.yaml
Without a blank line the last variable defined is never passed into the environment. In the case of USE_SSL = true it will cause the nginx container to fail with an SSL error as the required key file never gets defined.
> [#790] force blank line after final variable definition

- hs_core/templates/search/search.html
Fixed the discovery page not showing search resources issue. The issue is caused by the result table id conflicts. my-resource.html page's result table has the same id as the result table in search.html. The js for my-resource table conflicts results table in discovery search.html
> Check discovery not showing resources

- hsctl
Don't pre-designate http or https in curl statements in hsctl
> [#823] remove http:// from curl statments

- hydroshare/local_settings.py
Update to **local_settings.py** to default to console as email backend.
Since Django is running in a daemonized docker container the user will need to attach back to the container to see the output.
Example:
```bash
$ docker attach hydroshare_hydroshare_1
...
```
Fill out new user info in your local development browser and click join
```bash
...
Content-Type: multipart/alternative;
boundary="===============1573799015647134470=="
MIME-Version: 1.0
Subject: Activate your account in HydroShare
From: webmaster@localhost
To: mjstealey@gmail.com
Date: Mon, 04 Jan 2016 19:58:40 -0000
Message-ID: <20160104195840.40.17919@26223243c15c>
--===============1573799015647134470==
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Welcome to HydroShare. This email …
```
> [#606] default to console for the email backend

- theme/forms.py
Added commenter name in both subject and body as shown in the screen capture image above. @ironfroggy Could you do a quick code review (only two line changes) and see if you can give a +1?
> 852 add commenter name in email

- hs_swat_modelinstance/models.py
This is a very simple fix to a typo in one of the SWAT Model Instance resource metadata elements.
> Fixed typo related to watershedArea metadata element

- hsctl
Option to reset the working environment to a clean state.
- remove any data that was written as **root** of the hydroshare container (only fires if container is running)
- stop all running containers
- remove all containers and their associated volumes
- delete the hydroshare_* images (hydroshare, defaultworker, dockerworker)
- delete the hydroshare/static directory if found
- delete the root-items.txt file if found
> [#886] add reset_all option to hsctl script

- hs_core/templates/pages/genericresource.html
- theme/templates/base.html
- Undo block extra_js removal from base.html.
- Moved block extra_js out of main block in genericresource.html
As discussed in #869
> 869 Fix for block extra_js running twice

- hs_core/templates/pages/genericresource.html
As described in #913. This makes the google map api work again for the coverage tab in the resource landing page.
> 913 Hotfix - google map api not running

- Dockerfile
- docker-compose.template
- hsctl
- nginx/config-files/hydroshare-nginx.conf
- nginx/config-files/hydroshare-ssl-nginx.conf
- nginx/run-nginx
- uwsgi.ini
Updates to uwsgi and nginx
- accommodate up to 4 GB file download (to be increased at a later date)
- use unix socket for uWSGI server
- update nginx config files for unix socket and 4 GB file download and clean up spacing
- update hsctl restart to use docker-compose calls instead of docker call
- update docker-compose.template for unix socket use
- update Dockerfile to use docker hub tagged build ID
> 922 nginx uwsgi fix

- hs_core/templates/pages/genericresource.html
- hs_tools_resource/static/css/toolresource.css
If a web app has a title longer than 20 characters (hard-coded) then the name will be shortened with ellipses. A title attribute was added to the container to show the full title on the tool-tip.
> web app names shorted with ellipses; tooltip added

- hs_core/templates/pages/my-resources.html
Fixed minor scroll bar behavior for my resources table in Firefox.
Note: I had to do this fix in JQuery and not css because this styling issue is caused by DataTables pluggin script rendering.
> [#1008] My Resources table horizontal scroll bar fix for Firefox

- hs_model_program/forms.py
- hs_model_program/page_processors.py
Fixed a bug that was causing Model Program to fail during resource creation, in `page_processors.py`.  The code which was causing the problem was previously used for displaying field help_text as hover popup dialogs.  This feature is no longer being used so the offending code was removed from the following files:
* hs_model_program/forms.py
* hs_model_program/page_processors.py
> 1026 mp pageprocessors bug

- hs_core/hydroshare/resource.py
- hs_core/tests/api/native/test_create_new_version_resource.py
- hs_core/views/__init__.py
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/title-section.html
- theme/templates/resource-landing-page/top-right-buttons.html
Addressed further cosmetic code review comments from @horsburgh and fixed one bug discovered along the way when creating a new version for a resource that is the latest version of a resource already. @pkdash Could you give a quick review and see if you can give +1? I want this to be included in the next deployment since without the bug fix included in this PR, an error will be raised which breaks versioning chain when creating a version chain including more than 2 resources.
> Fixes to resource versioning

- theme/forms.py
This fixes the issue with commenting after upgrading to django 1.8. @mjstealey please review and merge it if it looks good. In a nutshell, we can directly use the function clean_comment() provided by django-contrib-comments 1.6.2 module without customizing that function in our code base, so the fix was just remove the customized version. I have tested it out in my local dev env and everything works after removal of this customized function, so I am positive it will just work.
> fixed commenting issue with django 1.8 upgrade

- hs_core/views/__init__.py
- hs_core/views/utils.py
- hydroshare/local_settings.py
- theme/templates/resource-landing-page/citation.html
This resolves on-demand netCDF resource update feed to Hyrax server when private netCDF resources are made public so that links of data services provided by Hyrax server on resource landing page are instantaneously valid and available once the netCDF resource is made public. The cron job that runs the update script every midnight will still be scheduled to clean up synlinked netCDF resources as needed for cases when a public netCDF resource is made private or deleted. I have tested it out in my local development environment and made sure it all works as expected. @pkdash @gantian127 Could you give a quick code review and see if you can give a +1?
> 1059 netcdf hyrax ondemand update

- hs_core/views/resource_rest_api.py
This PR contains a work around for a bug in django-rest-framework that caused two failing unit tests, one in hs_core.tests.api.rest.test_resource_file and one in hs_core.tests.api.rest.test_create_resource.  See #1069 for more details.
> 1069 fail test after base refactor

- hs_core/templates/pages/metadata_terms.html
Pretty self-explanatory. A description was added for the Script Resource by copying the format used on all other resource types.
> added Script resource mdescription to metadata_terms.html

- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
The title for the resource that the user edits on resource landing page or though metadata extraction is stored as metadata title element. This is different than the mezzanine Page title attribute which is used in the <title> tag of the resource landing page. This code change is to set the Page title based on the metadata title to ensure both these titles have the same value.
> Sync resource title with metadata title

- hs_core/templates/pages/metadata_terms.html
- hs_tools_resource/forms.py
@Castronova 
We will address issue #1093 in two PRs. 
This PR is to address your first question"1) Parameters that can be in the URL value need to be specified somewhere on the App resource instance editing page. These are currently only available by digging through the source code."
We added a link above the App URL text box, this link redirects user to the "WebApp" section of the "Terms" page (www.hydroshare.org/terms) which describes what are "predefined terms" and how to use them.
> [#1093] WebApp - describle how to use predefined terms

- hs_model_program/forms.py
Fixes a bug where metadata for uploaded content is saved incorrectly due to space characters in the file path.
> fixes [#1098] added quotes to the droplist option values

- hs_core/templates/pages/genericresource.html
This should fix the problem causing the map not to load correctly. After consulting with @jcaraballo17, we determined that loading the script asynchronously was causing the problem.
> [#997] Removed async and defer attributes from google maps script call

- theme/templates/resource-landing-page/top-right-buttons.html
just one line changed, removing the "not" in this logic statement.
@pkdash @hyi please review, thanks
> [#1122] hotfix for collection: publish btn shows up when contained res are not published

- hs_core/templates/search/search.html
@mjstealey @mauriel133 Google has moved the `svn` utility libraries to `GitHub`. It seems we can only browse the libraries source code from `svn`, but cannot make reference to them as we had. Since the libraries can be changed/moved/removed from git/svn any time, I think it is good practice to include the libraries from the CDN server.
> fix google map utility libraries reference issue

- hs_core/hydroshare/hs_bagit.py
This PR is to fix a bug discovered during @mjstealey's investigation to issue [#1092]. Specifically, we should only reset bag_modified to false when on-demand bagging operation succeeds, so when there is an issue when bagging operation, bag_modified AVU metadata should remain unchanged. @mjstealey @pkdash Can you take a quick look and see if you can give a +1 to this PR? download() function needs to be changed in django_irods which I have already pushed to the repo, that checks return status to only set bag_modified to false when return status is true.
> only reset bag_modified to false when on-demand bagging succeeds

- ref_ts/templates/pages/create-ref-time-series.html
- ref_ts/ts_utils.py
- ref_ts/views.py
We found the existing RefTS code already has the ability to accept any urls that can return wml content. The failing on some urls was because those urls are served via HTTPS.  The Requests module we are using by default blocks all https connections if no certificate file are provided. 
The changes we made to the backend are very simply. We simply set "verify=False" to let Requests lib ignore verifying ssl certificate, so it will accept both http urls and https urls. 
But we are not sure will this simply change leave any serious security issues?thanks @hyi @pkdash @mjstealey 
The other changes are all UI improvements, 
@jsadler2 can you please review the frontend? thanks
> 1207 refts allow to reference any wml url

- hs_core/templates/pages/genericresource.html
This pr is to address 1) #1254, and 2) broken popup message when extended metadata is saved
> hide extended metadata tab when there is no data in view mode

- Dockerfile
- hydroshare/settings.py
- hydroshare/urls.py
Implement simple heartbeat monitor for deployed sites.
Reference: [https://github.com/pbs/django-heartbeat](https://github.com/pbs/django-heartbeat)
**Jenkins**
Follow on job would be configured in Jenkins to poll the status of the /heartbeat/ results every 5 mins.
- Attempt a restart on failure
- Email admin team on failure and on successful restart
> [#1283] add django-heartbeat

- hs_app_netCDF/receivers.py
- hs_app_timeseries/receivers.py
- hs_core/hydroshare/hs_bagit.py
- hs_core/hydroshare/utils.py
- hs_geo_raster_resource/receivers.py
- hs_geographic_feature_resource/receivers.py
This PR fixed the issue of temp files or empty directories lingering around in /tmp directory as @mjstealey @pkdash and I found in the beta pre-deploy session together. Now /tmp/hydroshare directory will be cleaned up every time as well as all files retrieved from a federated zone for metadata extraction. Have tested all scenarios and made sure no temp files lingering around after resource is created or after a file is added to the resource. I will have to work on iRODS environment session JSON temp file clean up after I return from my vacation, but want to get this fix in first before I leave for vacation since files retrieve from a federated zone may be very big which will cause us disk space issues. This PR also fixed potential name clash issue. @pkdash Can you do a code review when …
> clean up temp files for bag and files retrieved from federation zone

- hs_geographic_feature_resource/templates/pages/geographicfeatureresource.html
this hotfix addressed #1330 
bug reason: a javascript logic written specifically for feature res type in Edit mode got executed in View mode and failed, causing a “Butterfly Effect” which somehow affected the auto-complete functionality in the access management popup.
> [#1330] hot fix: access management for feature res in view mode

- hs_core/forms.py
- hs_core/hydroshare/utils.py
- hs_core/models.py
- hs_core/receivers.py
- hs_core/tests/api/rest/test_create_resource.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
- hs_core/views/utils.py
- setup.cfg
Using the new ```metadata``` parameter, resource creation REST API endpoint can now be passed data for any number of valid metadata elements supported by the specified resource type in json format.
> REST API metadata support for resource creation

- hs_access_control/models.py
- hs_access_control/tests/test_user_delete.py
@mjstealey Handles issue #1274. **Answer is yes, deleting a user deletes the access control information for that user.** 
User.delete() correctly cascades to deleting UserAccess records in access control. This test proves that. 
The fact that UserAccess deletion cascades to delete UserAccess records from Groups and Resources is tested elsewhere.
> 1274 test user cascade delete

- hs_core/views/resource_rest_api.py
@pkdash 
I am not sure this is the best way to do it, but based on my testing it works. Also, the hs_restclient does not need to change anything.
hs_restclient users can download a refts bag in the same way as other res types
refts_res_id = "719034bf610b40cc97fea7033c5d7fd3"
hs.getResource(refts_res_id, destination="/tmp", unzip=True)
> Download refts bag via rest api

- hs_core/tests/api/rest/test_create_resource.py
- ref_ts/page_processors.py
- ref_ts/receivers.py
- ref_ts/ts_utils.py
- ref_ts/views.py
This pr works with @pkdash 's latest updates to rest api and its python client, allowing users to programmatically create a RefTS resource.
An example:
ref_url = "https://appsdev.hydroshare.org/apps/snow-inspector/waterml/?start=2016-01-30&end=2016-05-09&lat=44.957390&lon=-119.965527"
rtype = 'RefTimeSeriesResource'
title = 'My Test RefTimeSeriesResource 1'
metadata = []
ref_type = "rest"
metadata.append({"referenceurl": {"value": ref_url, "type": ref_type}})
res_id = hs.createResource(
rtype,
title,
resource_file=None,
keywords=["kw1", "kw2"],
abstract="my abstract",
metadata=json.dumps(metadata))
> 1238 rest api and ref time series

- hydroshare/local_settings.py
Only sets user zone session variables if REMOTE_USE_IRODS is set to True
- fixes breaking builds in non-federated environments (local dev)
> check if using irods user zone

- hs_access_control/models.py
- hs_app_netCDF/models.py
- hs_app_netCDF/receivers.py
- hs_app_timeseries/receivers.py
- hs_core/hydroshare/utils.py
- hs_core/page_processors.py
- hs_core/templates/pages/metadata_terms.html
- hs_tools_resource/forms.py
- hs_tools_resource/migrations/0008_auto_20160729_1811.py
- hs_tools_resource/models.py
- hs_tools_resource/page_processors.py
- hs_tools_resource/receivers.py
- hs_tools_resource/static/js/toolresource.js
- hs_tools_resource/templates/pages/toolresource.html
This PR is to address #1365:
1) a new url pattern term "HS_NETCDF_FILE_NAME" is added, which represents the full filename of the .nc file in a NetCDF res.
2) A new metadata term is added into WebApp called "SupportedSharingStatus", which is a new criteria to associate a webapp with certain res types in certain sharing status. Example: if a webapp supports NetCDF res type and its "SupportedSharingStatus" value is set to "Public", this webapp will only show up on Public NetCDF res landing page.  
3) some minor UI changes and bug fixes (see #1371 )
A live instance is deployed on https://riverdev.hydroshare.org/
> 1365 webapp changes for netcdf res

- Dockerfile
- gunicorn_start
- hsctl
- hydroshare.conf
- init
Reference issue #1384 
- use supervisord to manage the running of gunicorn
- gets gunicorn_start off of process id 1 (previously killed container if PID 1 went down)
- workers get restarted even if master process is killed (should minimize the offline events we've observed recently)
> supervisord for gunicorn

- hs_core/templates/pages/collaborate.html
- hs_core/templates/pages/my-resources.html
- theme/static/css/hydroshare_core.css
- theme/static/js/hs_resource_table.js
- theme/templates/pages/group.html
Also contains minor layout fixes for default 'no items found' labels.
> [#1350] Allow text formatting for text area inputs in group pages

- ref_ts/tests/test_ref_ts.py
- ref_ts/ts_utils.py
- ref_ts/views.py
@mjstealey @pkdash 
We found the excessively long log was output by library "suds" -- a third party lib used in RefTS code.  Its default log level is "Debug". We explicitly raised it to "INFO" level. A quick test showed this change could fix it. 
We also changed all statements in RefTS code that initialize the logger to 
"logger = logging.getLogger(____name____)", as is recommended in doc  https://docs.python.org/2/library/logging.html#module-logging
> [#1395] refts outputs excessively long log

- ref_ts/views.py
@zhiyuli @pkdash Please review this PR in conjunction with django_irods PR https://github.com/hydroshare/django_irods/pull/13. I have tested it out locally and the sync bag download for ref_ts resource works as expected. However, I have issues in my local dev env to test async bag download for other resources. It appears there is an issue in local dev env with async celery task execution although it works fine on dev.hydroshare.org with the same code base. @mjstealey and I are trying to figure out this issue, but in the meantime, want to get this ref_ts bag download fix in.
> fixed refts bag download issue

- hs_core/tasks.py
- hydroshare/irods/ruleGenerateBagIt_HS.r
- setup.cfg
This PR fixed bagit checksum compliance issues detailed in issue [#1418]. After this PR is merged, before deployment, bag_modified AVU metadata needs to be set to false for all bags so that all bags can be regenerated when being downloaded. In addition, all old manifest-md5.txt and tagmanifest-md5.txt files under all existing resource collections need to be deleted so that they will not be included in the newly generated bags. @mjstealey I think you can get this done pretty easily on iRODS side after this is merged before next deployment, and we can discuss any issues offline if needed. @pkdash Can you do code review for this PR? I also removed hs_core/tasks.py from config.cfg file to subject it for style check, so 99% of changes in hs_core/tasks.py are for code styling.
> fixed bagit compliance issues

- setup.cfg
- theme/forms.py
This PR addresses issue #1214 - just add ```[HydroShare Support]``` to the email subject for comments. Although the fix to this issue just takes one line of change to modify email subject, I removed affected file from setup.cfg to subject it to pylint check, hence majority of changes are just for style changes to pass pylint check. @pkdash Can you do a quick code review and see if you can give a +1?
> 1214 comment subject improvement

- gunicorn_start
- hsctl
- hydroshare/local_settings.py
- hydroshare/settings.py
- manage.py
- nginx/config-files/hydroshare-nginx.conf
- nginx/config-files/hydroshare-ssl-nginx.conf
- scripts/templates/docker-compose.template
- scripts/templates/init-hydroshare.template
Changes all occurrences of /hs_tmp back to /tmp
- Seemed to cause issues wrt iRODS authorization files
- /tmp is shared between certain containers in the way it is defined
Update hsctl to include SSL certs if USE_SSL is set to true
@hyi - this is what we discussed in HipChat. Please review once Jenkins completes it's build/test run.
> Reset tmp dir

- gunicorn_start
- hsctl
- hydroshare/local_settings.py
- nginx/config-files/hydroshare-nginx.conf
- nginx/config-files/hydroshare-ssl-nginx.conf
- scripts/templates/docker-compose.template
- scripts/templates/init-hydroshare.template
@hyi - This should cleanup the permissions around /tmp and allow proper bag downloading again.
Also added a restart_hs call at the end of rebuild as this seems to clear up any issues with not being able to create resources due to iRODS communication errors.
Will push this branch to beta for testing.
> fix access permissions

- theme/templates/resource-landing-page/abstract.html
@mjstealey there is essentially only one line change to "urlize" the abstract text so that urls included in the abstract are clickable. This is at request of @rayi113 who wants this feature quick (the earlier, the better), and I have tested it out locally and it worked well with this one line change. Can you test it out and if it works, get it merged and deployed? @rayi113 if you want this one line change to be a hotfix on www, @mjstealey can apply it on www easily. Just let us know.
> make url in abstract clickable

- hs_core/hydroshare/hs_bagit.py
- hs_core/models.py
- hs_core/resourcemap_urls.py
- hs_core/templates/pages/genericresource.html
@alvacouch @pkdash This PR needs to be reviewed together with the corresponding PR for django_irods submodule here: https://github.com/hydroshare/django_irods/pull/17. After this PR is merged, federation zone name will be removed from all urls used in HydroShare. So resourcemap.xml download url will be www.hydroshare.org/resource/id/data/resourcemap.xml regardless of which iRODS zone the resource resides. Thanks @alvacouch for pushing forward with this url issue and I am glad I have this issue worked out before federation zone really comes into full use. I am hoping this PR can be merged sooner rather than later since resourcemap.xml file needs to be regenerated for resources that reside in a federated zone. We only have very few such resources as of now, so it'd be good to have this url …
> 1425 url pattern improvement

- hs_tracking/migrations/0004_auto_20161010_1402.py
- hs_tracking/models.py
@mjstealey Can you code review this? The only change is to increase max_length from 130 to 500 for value field in hs_tracking/models.py with corresponding migration file. Have tested in my local environment and bag with long file names (over 230 characters) can be downloaded without issues with this fix.
> fixed issue #1474

- hs_core/templates/pages/metadata_terms.html
This is a minor fix to add isCopiedFrom and isHostedBy to the terms page
> [#1407] added isCopiedFrom and isHostedBy to the terms page

- hs_collection_resource/utils.py
This pr is to fix the following bug in collection list text file. Only one pair of quote is required to wrap multiple owner names.
> fix-multiple-owner-names-bug-in-collection-list-text

- hsctl
- hydroshare/local_settings.py
- irods/.gitignore
- irods/README.md
- irods/config-hsctl-compose.sh
- irods/config-local-settings.sh
- irods/create_user.sh
- irods/delete_user.sh
- irods/env-files/use-local-irods.env
- irods/use-local-irods.sh
- scripts/templates/docker-compose-local-irods.template
- scripts/templates/docker-compose.template
Implement federated iRODS servers in Docker space for HydroShare
- replicates hydroshareZone and hydroshareuserZone
- follows the same workflow as found in production
- enabled by running one additional script prior to using `hsctl`
- see [README.md](https://github.com/hydroshare/hydroshare/tree/1501-docker-irods/irods) for usage details
> 1501 Docker implementation of federated iRODS zones for HydroShare

- hs_core/views/__init__.py
- hs_core/views/utils.py
@gantian127 @dtarb This PR is to address the slow response with exposing the netCDF resources to OpeNDAP service when making a netCDF resource from private to public. I have changed the script that takes an extra optional parameter with resource id now which will expose the specified resource to hyrax server without looping through all resources to detect the newly made public netCDF resource. Since this can only be tested on www and the change is small on HydroShare side, just add an optional parameter with resource id, I took the liberty of updating the www with the updated code just for testing purposes. My test reveals everything works as expected and now when you make a private netCDF resource public, it is almost instantaneous without much delay to see the OpeNDAP services exposed …
> fixed the issue [#1512]

- irods/README.md
- irods/use-local-irods.sh
Addition of a `--persist` flag when using local iRODS.
- persists iRODS data for **data** and **users** instances on local disk so that subsequent runs can reuse it
- creates two new directories on the host at `/home/${USER}/icat1` and `/home/${USER}/icat2`
- flag must be present during initial standup of environment for files to be persisted locally.
- documentation updated in README.md
> Add persist option to using local iRODS

- hs_core/templates/pages/genericresource.html
- theme/static/js/hs_file_browser.js
While fixing this issue for Firefox I found out that it also occurs for IE in a worse way. Download wasn't working at all for IE. I have made it work completely for Firefox and single files download for IE in the meantime. I will be addressing IE multiple file download in another issue.
> [#1529] Download files Firefox and IE workaround

- hs_tools_resource/forms.py
- hs_tools_resource/page_processors.py
- hs_tools_resource/utils.py
This pr was to fix issue #1583 .
We removed the hard-coded "supported resource type" options. The revised webapp res type is able to dynamically harvest all existing resource types from system and use them to build "supported resource type" options.
> fix missing supported res type in webapp

- theme/templates/resource-landing-page/modals.html
This is purely wording change for resource versioning and addition of another dialog for resource publishing, which has been tested by @horsburgh as good to go. So I will merge it in without further code review once I see a green check from Jenkins.
> 1625 1608 version publish wording changes

- hs_core/views/__init__.py
- theme/static/js/resourceLandingAjax.js
The PR includes the following changes:
The green alert message that comes up when any metadata gets updated will appear only if all the  following conditions are met:
- Resource has the required content files
- Resource has the required metadata
- Resource is currently not set to public
The alert message has been changed and it would now say:
**Resource Status:** This resource can be published or made public
____________________________________________
**Note:** This PR needs to go in for AGU release.
> Changes to resource status message upon metadata element update

- hs_core/templates/pages/genericresource.html
- hs_core/views/__init__.py
- theme/templates/resource-landing-page/citation.html
- theme/views.py
This PR allows the resource to stay in edit mode when the resource sharing status (public, private, discoverable) are changed or if any comments/ratings related edits are made. With this change the resource should stay in edit mode always until the user selects the view mode.
> Keep resource in edit mode

- hs_core/tasks.py
@mjstealey Can you review this small PR? This PR is to address the warning issue with crossref when publishing a resource with the same title as an already published resource. For details, see the email thread regarding this.
> Crossref response check change to accommodate warning for resource publication 

- hs_tools_resource/migrations/0010_auto_20161203_1913.py
- theme/templates/resource-landing-page/title-section.html
This pr addressed the missing metadata issue in webapp res introduced by a newly merged migration file. 
That migration file was supposed to rename an existing db field, but actually it removed that existing data field then recreated a new field with the new name. So value stored in the old field were gone.
As suggested by @mjstealey, in this pr we manually modified that troublesome migration file to make it perform a renaming action instead of deletion and creation.
This pr has been deployed on riverdev and looks it has fixed said issue.
Also, this pr fixed #1635 in one line change: add a white space between "Web" and "App"
@mjstealey or @pkdash 
will you please review this pr? thanks
> hotfix -- fix migration issue in webapp res

- hydroshare/settings.py
- nginx/config-files/hydroshare-ssl-nginx.conf
This PR is to address #1711. 
New settings have been added to nginx conf and django settings.py (see https://docs.djangoproject.com/en/1.10/ref/settings/#secure-proxy-ssl-header).
This pr has been deployed on playground. We tried logging in appsdev server though playground-hydroshare oauth. The "301 redirect" observed on www as described in #1711 did not happen on playground.
> 1711 ssl settings

- hs_core/models.py
extended the exception handling for calculating resource file size to fix a bug when calculating the size of collection resources that was causing the `stats --resources-details` command to fail.
> Bug fix to hs_core resource size calculation

- theme/templates/resource-landing-page/modals.html
See #1739 
I tested that the message popup behaves appropriately with this change. 
@mjstealey, after reviewed I suggest adding this as a hot-fix since it is very simple.
> [#1739] Made remove access message hidden initially

- hs_core/templates/pages/genericresource.html
- hs_core/views/__init__.py
View function now removes any duplicate keywords and trims the length of any keyword to the maximum length allowed.  This should minimize the chance of keyword update/editing failure.
> Check duplicate keywords

- hs_geo_raster_resource/receivers.py
- hs_geo_raster_resource/tests/test_raster_metadata_user_zone.py
This fixes both the failing unit tests as well as creation of raster resource using federated files from user zone.
> hotfix for federated unit tests for raster resource

- hs_core/hydroshare/resource.py
@pkdash Can you give a quick review for this very small PR? Just one line change. I have verified in my local environment that it fixed the issue. I have also manually applied the fix to www since it is a regression error and resource publication no longer works without this fix. Not sure how this happened. My speculation is that ```can_be_published``` used to be a method but somehow was changed to a property in some recent PR merges without changing the calling method, hence causing an TypeError, which prevents resource publication to work.
> fix resource publication issue - has applied hot fix for it on www

- hs_core/templates/pages/genericresource.html
- theme/static/js/hs_file_browser.js
This enables cut and paste of any file that are part of the "GenericLogicalFile" type so that they can be moved around. Applies to Composite Resource type.
> Allow cut and paste for generic file type

- hs_core/templates/pages/genericresource.html
@pkdash Can you give a quick review on this PR? Only one conditional statement is added on template page so that edit and remove icon buttons will not be displayed for isVersionOf relation since it should not be editable by owners but can only be created programmatically by the system.
> removed edit and remove icons for isVersionOf relation

- hs_core/models.py
- hs_core/tests/api/native/test_irods_user_zone_federation.py
@pkdash Can you code review this small PR when you have a chance? I believe it is a regression issue that used to work but does not work now. I have also added relevant unit tests to cover this specific scenario in which an empty resource is created first in hydroshare zone and then files from federated user zone is added into this resource in hydroshare zone. The added unit tests have passed in my local test environment. It'd be great if this PR can be merged to make into the next deploy if not earlier as a hot fix. Thanks.
> Fixed the issue [#1824] - resource deletion issue

- Dockerfile
- README.md
- add initial requires.io linkage by requirements.txt file only (no automated updates at this time)
- requirements.txt file created from a `pip freeze` call to the completed image.
- update reference to hs_docker_base to be current
- Reference: [hs\_docker\_base:1.9.5](https://github.com/hydroshare/hs_docker_base) 
- badge linkage to [requires.io](https://requires.io/github/hydroshare/hs_docker_base/requirements/?branch=master)
> 1807 requires io integrations - badge only

- theme/forms.py
- theme/templates/accounts/profile.html
- theme/templates/accounts/sign_up_form.html
This PR is to disable username change from user profile page in preparation for quota management implementation. This decision was made during developer coordination meeting. A username validation rule is also added in user signup page to ensure "+" is not allowed as a valid character in username since "+" is treated as a valid character in username in Django but treated as an invalid username in iRODS and we need to keep username validation rule between Django and iRODS in sync so that each username created in Django can create a corresponding username in iRODS user zone. @pkdash Can you code review this PR?
> Disable username change from profile page in preparation for quota management

- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/views/utils.py
This PR addresses the issue #1858 @dtarb raised. With the fix in this PR, any files users select from any irods zone will not be subject to 1GB size limit including nfie zone which is federated with hydroshare zone, but does not have the localHydroProxy account created to hold hydroshare resources created from a federated zone, in which case nfie zone will be treated as a non-federated zone so that users still can browse files from it to create hydroshare resources without being subject to 1GB file size limit. I removed use of any UploadedFile instance for this case so that all file transfers are done by iRODS icommands for non-federated case with parallel transfer capability, so it should have capability to handle large files without 1GB size limit. I have deployed it to playground for …
> 1858 irods file size

- hs_core/hydroshare/hs_bagit.py
- hs_core/hydroshare/utils.py
- hs_core/tasks.py
- hs_model_program/tests/test_model_program_metadata.py
- hs_modelinstance/tests/test_modelinstance_metadata.py
- hs_modflow_modelinstance/tests/test_modflow_modelinstance_metadata.py
- hs_swat_modelinstance/tests/test_swat_modelinstance_metadata.py
@pkdash @hyi Quick fix to make HydroShare code compliant with new django_irods.
1. Remove duplicate files from tests. 
2. Remove redundant argument from all calls to create_bag_files.
Testing now.
> 1657 update tests for django irods

- .gitignore
- config/hydroshare-config.yaml
- nginx/Dockerfile
- nginx/README.md
- nginx/config-files/hydroshare-nginx.conf
- nginx/config-files/hydroshare-ssl-nginx.conf
- nginx/docker-entrypoint.sh
- nginx/generate_htpasswd.exp
- nginx/run-nginx
Add simple http auth to HydroShare for deployment on public VMs
- enforced by nginx configuration using .htpasswd file set by user
- USE_HTTP_AUTH variable added to hydroshare-config.yml (true/false)
- requires **expect** package to generate .htpasswd file
> simple http auth

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/copyToClipboard.js
- theme/static/js/custom.js
- theme/templates/resource-landing-page/citation.html
- theme/templates/resource-landing-page/modals.html
- theme/templates/resource-landing-page/top-right-buttons.html
- theme/tests/test_functional.py
- The full citation is now displayed. The container resizes appropriately.
- URL is again clickable
Also:
- Updated 'Copy Resource' and 'Create New Resource Version' button icons
> [#1941] Display full citation

- hs_app_timeseries/forms.py
- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/coordinates-picker.js
- theme/templates/resource-landing-page/coordinates_picker.html
`{% include "resource-landing-page/coordinates_picker.html" %}`
This container should have:
- The class `"hs-coordinates-picker"` if the elements are to be instantiated on page load. Otherwise see below for how to instantiate dynamically.
- The attribute `"data-coordinates-type"` which can be `"point"` or `"rectangle"`
- The input elements contained within (no matter how nested).
The input elements should have:
- The attribute `"data-map-item"` which can be:
-- for a point: `"longitude"` and `"latitude"`
-- for a rectangle: `"northlimit"`,` "eastlimit"`, `"southlimit"` and `"westlimit"`
Elements can be instantiated when the page loads. The script will search for the elements with the class "hs-coordinates-picker" and initiate them. Example:
```
<div class="hs-coordinates-picker" …
```
> [#1966] Widget for selecting coordinates

- theme/templates/resource-landing-page/citation.html
> [#1978][Hotfix] Fix for message displacing buttons

- hs_core/templates/pages/genericresource.html
- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
@pkdash, would this work as the icon? 
Also contains:
- Fix for help message when downloading large files not being shown on view mode.
- Fix for html error in Extended Metadata tab
> [#1988][WIP] Ref Timeseries File Icon

- hs_core/hydroshare/utils.py
- hs_core/models.py
@hyi @dtarb This is a preliminary PR to correct problems described by @pkdash in issue #1999. 
The main problem so far is that the iRODS attributes are being attached to the wrong level of the resource during a copy. This affects both copy and version for all resource types, not just composite resource. 
It also seems to mess up the creation of an appropriate bag for the resource.
This is work in progress. What I've fixed so far is definitely wrong and needs to be fixed, but I have not yet fully investigated the scope of this problem. There may be other errors.
> 1999 resource file api bugs

- hs_collection_resource/tests/test_collection.py
- hs_core/hydroshare/resource.py
- hs_core/tests/api/native/test_update_metadata.py
- hs_core/views/resource_metadata_rest_api.py
This hotfix needs to be applied to master. Once I get +1 I will ask @mjstealey to do this merge.
> HOTFIX-Set flag to regenerate metadata xml on bulk metadata update

- hs_core/management/commands/check_irods_files.py
- hs_core/management/commands/check_relations.py
- hs_core/models.py
- hs_core/tasks.py
- hs_core/tests/api/native/test_check_files.py
@pkdash @hyi @mjstealey 
Here is the first version of the integrity checker. If you call:
```resource.check_irods_files()```
for a specific resource, then integrity will be checked and the system log will report errors.
If you instead call:
```resource.check_irods_files(stop_on_error=True)```
for a resource, it will raise an exception and stop on first error with ValidationError
See `hs_core/tests/api/native/test_check_files.py` for examples.
> 2031 Django-iRODS integrity checker

- hs_core/management/commands/check_irods_files.py
- hs_core/management/commands/fix_irods_user_paths.py
- hs_core/models.py
- hydroshare/local_settings.py
New PR for same branch,  targeted at 1.10.0 rather than develop
@mjstealey @hyi @pkdash @dtarb 
This PR implements the management command
```./hsctl managepy fix_irods_user_paths```
which fixes the user paths in any test environment.
* It does nothing in a production environment. 
* It uses a setting `HS_USER_ZONE_PRODUCTION_PATH` to detect which resources to move.  
* After this test, user zone resources test as clean using `check_irods_files`. 
I propose this as a hotfix because this option allows tests to refer to user paths without failing. **This is a temporary measure until I change the handling of user-zone files in 1.11.0.**
This PR also implements the option 
```./hsctl managepy check_irods_files --repair```
that first does the fix above, and then checks all files for existence. …
> 2040 PROPOSED 1.10.0 HOTFIX: repair user file problems during testing

- theme/static/css/hydroshare_core.css
Fix for text overflow in Spatial Reference table of File Metadata
> [#2063][Hotfix] Spatial reference - string wrap fix

- hs_file_types/models/netcdf.py
This is to make sure that when a creator is an organization, the organization name will be added in the netCDF file.
> [#1924] hotfix for checking the creator name

- hs_core/models.py
- theme/static/js/hs_file_browser.js
Fixed it by removing use of formatDate() for file type temporal data.
> [HOTFIX] File type metadata form display issues

- hs_core/hydroshare/resource.py
- hs_core/models.py
- hs_core/tasks.py
- hs_core/tests/api/native/test_set_public.py
- hs_core/views/__init__.py
- hs_core/views/resource_rest_api.py
- hs_core/views/utils.py
- hs_file_types/models/netcdf.py
- hs_file_types/models/raster.py
- setup.cfg
New routines: 
* `resource.set_public(value, user)`: sets the public flag and potentially the discoverable flag. 
* `resource.set_discoverable(value, user)`: sets the discoverable flag and potentially the public flag. 
* `resource.update_public_and_discoverable()`: sets discoverable/private to False if metadata constraints are now violated. 
* `resource.setAVU('isPublic', True)`: automatically locates resource root and converts Boolean to string. 
* `resource.getAVU('isPublic')`: returns the value of the AVU, automatically locating the resource root. 
These are used as follows: 
* `resource.set_public` and `resource.set_discoverable` are called when the user requests a setting via the UI or REST API.  This includes when publishing data. 
* `resource.update_public_and_discoverable` are …
> 2071 [hotfix] fix isPublic

- hs_core/debug_urls.py
- hs_core/templates/debug/debug_resource.html
- hs_core/urls.py
- hs_core/views/__init__.py
- hs_core/views/debug_resource_view.py
- hydroshare/urls.py
@dtarb @pkdash @mauriel133 @aphelionz @martinseul @hyi 
As mentioned in #2095, we need more insight into what is going on in the running system. This implements a simple debugging page for a resource. 
* with URL `/resource/{shortkey}/debug/`
* accessible to anyone with VIEW privilege
* not accessible via a link (must type URL manually). 
This page runs `check_irods_files` and prints the result. This will be very valuable in debugging synchronization errors. If at all possible I want to get this into 1.10.0. 
Please comment on access permission required and choice of URL.
> 2095 [hotfix] resource debugging page

- hs_core/tasks.py
@hyi @mjstealey @pkdash @aphelionz This fixes the issue with bag download crashing  #2111 
The reason for the error: 
1. Hong's scripts check for "true" in AVUs. 
2. Michael's setup scripts set iRODS AVUs to "True" instead. 
3. I used lower() to make the tests always work properly. (I originally modified the offending line of code) 
4. `metadata_dirty` for older resources is `None`, not `'True'`
5. Thus the task to generate a bag tries to do a `lower()` of `None`. 
I simply checked for `None` in that procedure.
Long term, we should also: 
1. Initialize bag_modified to 'true' --  and not 'True' -- in build script. 
2. add the `lower()` qualifiers and None test in `django_irods/views/`, which make the same mistake as was being made in `hs_core/tasks.py`. 
Will submit a related PR to repair …
> Fix bag download problem

- hs_app_netCDF/templates/pages/netcdfresource.html
- hs_core/management/commands/fix_broken_resources.py
- hs_core/models.py
The updated script `fix_broken_resources` repairs files as discussed on today's call, including the files discovered by the first check_irods_files run, NetCDF resources with erroneous header_info.txt, and isPublic flags. 
This script has been manually copied to beta.hydroshare.org and is running now.
> Enhanced resource repair including NetCDF and isPublic AVU

- theme/admin.py
@pkdash @aphelionz Can one or both of you review this small PR when you get a chance? It should be a quick review. The issue being addressed in this PR is that the foreign key field (i.e., User in this case) does not show up in the default Django admin implementation when adding a new UserQuota object which prevented admin user to add a new UserQuota object for an existing user for a different zone for example. What I did to work around this issue is to override the get_form() method from Django ModelAdmin to use a customized model form for adding UserQuota object so that the foreign key User field can show up for selection, and use the default form in Django when changing an existing UserQuota object. I have tested various scenarios locally and everything works well as expected. This …
> 2131 add users quota

- hs_core/hydroshare/users.py
- hs_core/tests/api/rest/test_resource_list.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
@pkdash Can you review this small PR? I added an optional "include_obsolete" parameter that allows callers to set it to True if they want to get obsoleted resources in the returned resource list from REST API, and the default is False, meaning the obsoleted resources will be filtered out and thus not included in the returned resource list. Tests are also added and all tests have passed.
> Address issue #2045: added include_obsolete parameter to get resource list REST API

- hs_core/models.py
- hs_core/views/utils.py
@alvacouch @pkdash @dtarb @mjstealey I have made the following changes and did the timing using the zip file in this resource https://www.hydroshare.org/resource/37594b5bba544e14905dc0f8257c874f/ as the test case. This zip file include many folders and a large set of files. Note that ibun unzip call only took 4 seconds for this test case, which can be ignored compared to the link_irods_folder_to_django() call which takes 102 seconds as is now.
1. removed the deprecated istorage.size() call. This reduced the link call from 102 seconds to 82 seconds.
2. removed duplicate ```istorage = resource.get_irods_storage()``` call by adding the if condition to only call it when pass in istorage is None. Since we already pass in an istorage object, this call is not needed. This reduced the link call …
> 2153 unzip performance

- hs_core/hydroshare/resource.py
Hotfix for #2191 
As described in #2182
> HOTFIX: remove second resource_modified call

- hs_rest_api/urls.py
Tiny request from that fixes #2259 
Alva had requested that we rename userInfo/ to simply user/. I kept userInfo around for backwards compatibility
> Creating user/ endpoint

- hs_core/hydroshare/hs_bagit.py
- hs_core/hydroshare/utils.py
@aphelionz Can you review this small change? This fixed the issue with iUTAH datasets that have unicode characters in the filenames. I have tested using their test data sets, and verified with this fix, resource can be created successfully with their test data sets.
> fixed unicode issue #2299

- theme/templates/resource-landing-page/abstract.html
This prevents the error from occurring again, but the resources affected need to be manually fixed by editing their abstracts. 
This bug occurred because the URL strings were being parsed and converted to links every time the abstract was changed. Solved it by converting only when rendering in view mode and not in the form input.
> [#2536] Fix for URLs in abstract

- theme/tests/functional.py
- theme/tests/multiplatform.py
Work to get selenium tests working in FF as well as phantomjs now that the new Firefox API geckodriver has been released.
There are remaining issues with access control on resource pages and mezzanine that I am unsure how to handle. It seems like the templates are still using page permissions rather than newer hs_access control permissions.
> 2013 firefox test fixes

- hs_core/templates/pages/create-resource.html
- hs_core/views/utils.py
- theme/static/css/hydroshare_core.css
- theme/static/js/create-resource.js
Defines and implements constraints for resource creation.
Example Screenshot:
Currently defined constraints:
```
// Resource type constraint definitions
constraints = {
GeographicFeatureResource: {
requiredFiles: ['.DBF', '.SHP', '.SHX'],    // File extensions in uppercase
canBeEmpty: true,                           // Optional. Defaults to true
singleFileFormat: '.ZIP',                   // File format when uploading a single file
sameFileNames: true,                        // The files must share the same file name
sameFileNamesExcep: ['SHP.XML']                 // Additional file extensions to check for
}
};
```
@dtarb, @pkdash, @horsburgh 
I have added business logic to implement constraints in resource creation. The resource creation process is allowed if all defined constraints …
> [#2106][WIP] Resource creation constraints

- hs_core/discovery_form.py
- hs_core/templates/search/search.html
- theme/static/css/hydroshare_core.css
- theme/static/js/discover.js
Temporarily fixes #2397 
This simply disables the sorting functionality as it is confusing. This is temporary for this week's discovery hotfix deploy.
Also fixes #2396 - removed the SOLR popup
> Temporary disabling of discovery sorting

- hs_core/templates/pages/genericresource.html
- theme/static/js/custom.js
- theme/templates/resource-landing-page/citation.html
Simple change. Fixes some URL parsing errors for Relations, Sources as well as content in Extended Metadata tab.
Note: still keeping old method to use on dynamically generated items for now.
> [#2479] Changing URL parsing method.

- hs_core/templates/pages/genericresource.html
As discussed in #2480, now shows similar style to that of the page in edit mode.
> [#2480] Visual separator for Sources and Relations

- hs_core/management/commands/debug_resource.py
- hs_core/models.py
- hs_core/views/resource_folder_hierarchy.py
@pkdash @aphelionz @martinseul Brute-force to fixing missing logical files creates missing generic logical files as needed. 
This is not finished but is provided for reference for others who might be working on the problem. 
* The game plan is to use `ResourceFile.get_or_create_logical_file` in any place that `ResourceFile.logical_file `fails to work due to a missing logical file. This includes templates. 
* Behavior of `get_or_create_logical_file` is identical to behavior of `./hsctl managepy fix_missing_logical_files`.
> 2431 HOTFIX dynamically create missing logical files

- hs_composite_resource/tests/test_composite_resource.py
- hs_composite_resource/tests/test_composite_resource_user_zone.py
- hs_core/hydroshare/utils.py
- hs_file_types/models/geofeature.py
- hs_file_types/models/netcdf.py
- hs_file_types/models/raster.py
- hs_file_types/models/reftimeseries.py
- hs_file_types/models/timeseries.py
If multiple files are added to the composite and one of the files does not get added for some reason (e.g., duplicate file name) then the system was failing to create a generic file for each of the files that got added. This may be one of the reasons why we have seen missing logical files that lead to no files being listed on the UI.
> HOTFIX-Ensures generic logical file is created when a file gets added

- irods/use-local-irods.sh
This fixes federation-related test failures when using local iRODS docker containers. Let's see whether Jenkins builds this PR successfully with a green check.
> doing apt-get update before doing apt-get install

- hs_core/admin.py
Fixes #2549, a minor bug where you can't create users via the admin panel. Required for internal QA
1. Check out the branch, rebuild
2. Go to /admin
3. Click on the + Add button in the Users section
4. Note the new field: Email
5. Fill out the form and submit
6. New User should be created
> Updating admin.py to add email field

- hs_composite_resource/models.py
Fixes #2537 
To test you can run this script where hs = hs_restclient:
```
from hs_restclient import HydroShare, HydroShareAuthBasic
auth = HydroShareAuthBasic(username='YOUR_USER', password='YOUR_PASS')
hs = HydroShare(hostname="dev-hs-2.cuahsi.org", auth=auth, verify=False)
resource = hs.createResource(
'CompositeResource',
"This is a test title",
abstract="This is a test abstract",
keywords=('mmw', 'model-my-watershed')
)
aoi_folder = 'area-of-interest'
hs.createResourceFolder(resource, pathname=aoi_folder)
```
> Allowing supports_folders for CompositeResource

- hs_core/views/resource_rest_api.py
- hs_core/views/resource_ticket_rest_api.py
- hs_core/views/serializers.py
Fixes #2562 
To test:
1. Checkout this branch and `./hsctl restart`
2. Simply visit /hsapi/resource and ensure that the "abstract" field appears in the results.
> 2562 add abstract to resource list

- theme/forms.py
- theme/templates/accounts/sign_up_form.html
Follow the instructions to test. You may have to register at https://www.google.com/recaptcha/admin to get your site key and secret. These are NOT checked in to Git (or at least shouldn't be).
1. Check out this branch and add the following to local_settings.py:
```
RECAPTCHA_VERIFY_URL='https://www.google.com/recaptcha/api/siteverify'
RECAPTCHA_SITE_KEY="enter site key here"
RECAPTCHA_SECRET_KEY="enter secret key here"
```
2. On line 48 of `theme/templates/accounts/sign_up_form.html` add the site key in the `data-sitekey` attribute
3. `./hsctl restart`
4. Test the signup flow with the new captcha. If all goes well it should create a new account for you with no problems.
> Adding recaptcha2 back to signup

- hs_core/views/__init__.py
- hydroshare/settings.py
https://github.com/hydroshare/hydroshare/issues/2590
There was no suggested time period so I used 7 days.  A side effect of this is everything using django's authorization tokens will be increased to 7 days as well.  
I haven't really been able to test this, because it requires 7 days to test, so if another programmer could do a sanity check on this setting, that'd be great.
> [#2590] - increase time for group email links expirary

- theme/static/js/profile.js
1. Sign in and navigate to profile page.  Append the edit query params `?edit=true` to the url and press enter.  Validate the profile is opened in edit mode and the query params are no longer in the url.  Press Save Changes and Validate you're taken to the profile view page.
> [#1867] strip out edit query params so edit mode is not reopened on save

- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
1. Check out `add-doi-to-resource-api` and restart 
2. Visit the /hsapi/resource page and ensure that doi is null for non-published resources, and filled in for published resources
> Adding DOI to resource listing API

- hydroshare/local_settings.py
1. Deploy hydroshare locally and navigate to the signup page. Validate that captcha works. There will also be little red text that says "This reCAPTCHA is for testing purposes only. Please report to the site admin if you are seeing this"
> [#2696] add default reCAPTCHA test keys and site url

- hs_core/hydroshare/users.py
- hs_core/hydroshare/utils.py
- hs_core/tests/api/rest/base.py
- hs_core/tests/api/rest/test_resource_list.py
- hs_core/views/serializers.py
- hs_core/views/utils.py
1. Using hs_restclient, query resources by owner, creator and user by username and user email.  Validate username and email return the same resources.
2. Using hs_restclient  query resources by group name and group id.  Validate group id and name return the same resources.
> 2713 res query bugs

- hs_core/hydroshare/utils.py
- hs_core/tests/api/native/test_irods_user_zone_federation.py
- hs_core/views/__init__.py
- irods_browser_app/static/js/irods.js
This fixes the bag_modified AVU on a resource being wrongly set to False when the resource bag does not even exist, which results in resource bag not being able to be copied to the user zone, as detailed in the issue #2724. To replicate this, one has to manually set bag_modified flag on a resource to be False when the resource bag does not exist yet. I augmented the test to cover this scenario. I also used local irods containers to replicate this scenario and made sure the updated code is able to handle this and successfully recreate the resource bag and copy the created bag to user zone as expected.
> 2724 create bag user zone

- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/models.py
- hs_core/tests/api/native/test_irods_user_zone_federation.py
- hs_core/views/__init__.py
1. Copy a resource, wait for 30 seconds, you should see your quota usage increased by the size of the newly copied resource from your profile page.
2. Create a new version of a resource, wait for 30 seconds, you should see your quota usage increased by the size of the newly copied resource from your profile page.
3. Copy a resource bag to your iRODS user zone, wait for 30 seconds, you should see your quota usage increased by the size of the newly copied resource from your profile page.
> 2759 quota issues

- config/hydroshare-config.yaml
- nginx/config-files/hydroshare-nginx.conf.template
- nginx/config-files/hydroshare-ssl-nginx.conf.template
@aphelionz This is a maintenance PR: 
1. Specify reasonable defaults for NGINX configuration in hydroshare-config.yaml 
2. Remove trailing slash from NGINX configuration in hydroshare-config.yaml
3. Modify nginx templates not to require trailing slash. 
> Minor tuning of SENDFILE configuration

- theme/views.py
Have applied the fix on beta.hydroshare.org. When a corresponding user already exists on iRODS user zone, but Django thinks the corresponding user does not exist on iRODS (as the flag in Django database indicates so), and a user can go to their profile and click on create iRODS user account button. Without this fix, an error propagates from iRODS to Django indicating the account already exists, and user gets an error message notification. With this fix, the error is filtered and if the error indicates the iRODS account already exists, Django updates the flag to be in sync with iRODS user account status and indicate success, and only report error otherwise when it is not the error that account already exists.
> fix iRODS user account out-of-sync issue between Django and iRODS

- hs_rest_api/resources/file_metadata.py
- hs_rest_api/tests/http/file_metadata.py
This covers a use case that is needed by a hydroshare user to write file specific box spatial coverage.  I talked to Dave about getting this into 1.15.5, which he approved.  The user needs the functionality for a demo at the end of the month.
1. Write file specific metadata using `/resource/(?P<pk>[0-9a-f-]+)/files/(?P<file_id>[0-9]+)/metadata/$`
> [#2899] allow box coverage for file metadta

- theme/static/css/hydroshare_core.css
https://github.com/hydroshare/hydroshare/issues/2828
1. Go to any page that has the page tip banner where you can close it with a "x".
2. Resize the browser width to anywhere between 767px and 991px, there is no text cut off.
> 2828 pagetip cut-off when resizing into a range of width

- hs_core/management/commands/solr_recover.py
Here is a management command to reindex SOLR while online. 
usage: `./hsctl managepy solr_recover`
or `./hsctl managepy solr_recover {resource-id}`
Tested on cuahsi-dev-1 and led to complete recovery of SOLR function. 
After running the scripts, all resources appear in discovery page.
> 3029 command to recover SOLR index while online

- hs_core/forms.py
- hs_core/tests/api/native/test_core_metadata.py
- theme/static/js/coverageMap.js
- theme/templates/resource-landing-page/coverage.html
1. update a spatial coverage limit to zero.  View the resource in view mode and verify the bounds box shows up correctly
> [#3012] - handle display of zero in spatial coverage

- theme/static/js/composite-resource.js
- theme/static/js/resourceLandingAjax.js
A method to update temporal coverage in resource landing page meant to run only in edit mode was causing the script to halt in view mode since it fails to get the DOM elements it needs. Fixed by adding conditionals so it only runs in edit mode.
> [#2808] Add conditionals for methods that only need to run in edit mode

- theme/static/js/resourceLandingAjax.js
1. Have a resource without a keyword. Everything else are setup including abstract etc.
2. Going to edit mode, add a new keyword. 
3. Right after the keywrod is added, a pop up message has the accurate saying.
> 2955 inform accurately the status of resource

- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/quota.html
This issue was caused by an error in a jquery selector introduced recently with the UI changes. 
Also disables the Quota change button after a request is triggered to prevent duplicate requests.
> [#3138] Correctly trigger removing self access in Manage Access panel

- theme/static/js/hs_file_browser.js
Fixes an issue where the text input when trying to zip a folder was not automatically selected.
> [#2765] Fix for text input auto select on Zip Folder dialog

- theme/static/css/hydroshare_core.css
- theme/static/js/generic-resource.js
- theme/static/js/resourceLandingAjax.js
- Makes metadata alert persist until all required metadata is filled in
- Also adjusts positioning to correctly center the alert window.
> [#3130] Make metadata alert persist until all required metadata is filled in

- hs_core/hydroshare/hs_bagit.py
- hs_core/management/commands/migrate_generic_resources.py
1. Testing locally:
- Deploy the branch '3100-migrate-generic-resources'. 
- Edit the 'hs_core/templates/pages/create-resource.html' file to enable creating generic resource.
- Create couple of generic resource with/without file uploads using the local hydroshare website. Edit any metadata for each of these resources.
- Run the management command 'migrate_generic_resources'. Output of the command should indicate the number of generic resources that were converted to composite resources and that there are 0 number of generic resources after the conversion. 
- Click 'MY  RESOURCES' link on the webpage. You should see all resources are of type composite resource.
- Go to the landing page of one of the composite resources. You should see all the resource metadata that you entered exist.
- …
> Migrate generic resources to composite resource

- hydroshare/settings.py
Just setting a default value of off to hsws so it doesn't break hydroshare if the setting is missing in local_settings.py
> [#3045] - turn off hsws by default in settings.py

- theme/templates/resource-landing-page/references.html
This PR disables users from editing system-generated ```isVersionOf``` relation type from resource landing page to fix issue #3276 . I am trying to get this PR into RC 1.21 since without it, users would be able to manually edit this which would result in orphaned resources as detailed in issue #3276, which would be hard to track and fix, so it'd be good to prevent this in the first place.
> disable isVersionOf editing

- theme/static/js/hs_file_browser.js
Same work from https://github.com/hydroshare/hydroshare/pull/3275 targettng RC 1.21
> This PR fixes the logic of navigation buttons in the resource landing page file browser. The error was caused by an outdated value predating work done recently which changed how we construct the file paths in the front end.
> [RC-1.21 hotfix][#3264] Update logic to handle file browser's navigation state

- theme/templates/pages/group.html
This is necessary to start sharing code/UI component across Resource Views, instead of copy/pasting code and repeating/maintaining in 3-5 separate areas and/or having identical UI components have slightly different formatting.
Fixes https://github.com/hydroshare/hydroshare/issues/3313
1. Share a Resource with a Group
2. View Resources for the group in the Resources tab
> Remove dead code for table readability and sharing across resource views

- hs_core/discovery_parser.py
- hs_core/tests/api/native/test_discovery_parser.py
This code modifies the discovery command parser in three ways: 
1. Eliminate error messages for invalid fields in `foo:bar` kinds of queries. Parse invalid keyword entries, e.g., `foo:bar` as literals to be searched for. 
3. Eliminate parsing of `-` and `+` synonyms for `NOT` and include. 
Note that the special keywords `AND`, `OR`, `NOT` are still present and the expressive power of the query engine has not been reduced. Only shorthand syntaxes have been eliminated. 
This makes the strange long names in the CZO use case more easily discoverable. 
1. Type discovery request with colons and invalid keyword, e.g., `foo:bar`. Error is not returned. Instead, this is searched for literally. 
2. Type a discovery request `-couch` or `+couch`. This should be interpreted literally, and not as `NOT …
> 3292 colon in discover

- hs_core/tests/api/rest/test_folders.py
- hs_core/views/utils.py
- theme/static/js/resourceLandingAjax.js
1. Create a folder (e.g. folder-1) in any resource. Try to create another folder (at same directory path) with the same folder name (e.g. folder-1), you should see a message 'Folder already exists' and the 2nd folder won't be created.
> Folder create - show folder exists message

- theme/static/js/generic-resource.js
- theme/static/js/modals.js
- theme/templates/resource-landing-page/modals.html
#2756 
Deleting a pair of extra metadata requires a confirmation dialog. The fix provides the same behavior as deleting a file metadata. 
The existent code design was to just combine Add and Edit into one dialog. Method signatures reflects this. `showAddEditExtraMetaPopup(edit:false, ''");` The button to commit is always “Save Changes”. 
I don’t want to pollute the original design with the new delete dialog as it might introduce regression for this minor fix. So the bug fix is separated from the existent Add/Edit modal dialog. 
1. Add new key/value pairs of extra metadata.
2. Click on the trash can.
3. Delete confirmation dialog pops up, the same look and feel as file metadata deletion.
4. Click the red "Delete" button.
5. The meta data row is deleted.
> [2756] delete metadata confirm

- theme/static/js/generic-resource.js
- theme/static/js/resourceLandingAjax.js
IE11 does not behave well with default parameter values in JavaScript functions. A workaround has been implemented to prevent the script from crashing.
This PR also updates the selectors of autocomplete inputs. This way their placeholder values will now properly read "Search by name or user name" or "Search by group name".
2. Use the Manage Access window to add access to some user.
3. Verify that autocomplete inputs respond correctly to user input.
> [#3226] IE11 Workaround for default function parameter values

- hs_access_control/models/community.py
- hs_access_control/models/group.py
This is an expedient modification of `public_resources` -- for both communities and groups -- that eliminates the anomaly described in #3382. More than this is probably necessary, eventually. I expect that we'll need to institute an `exhibit` flag that indicates which resources to show in group and community public listings. This expedient change will satisfy the purposes of the CZOs, however. 
1. List community resources. They contain only resources owned by community members.
> Limit exposed public resources to be owned by a group member.

- theme/static/js/custom.js
Addresses https://github.com/hydroshare/hydroshare/issues/3434#issuecomment-501670986
In Firefox, when using User Autocomplete widget, the modal window would get dismissed if clicking on autocomplete items hovering outside the modal window. This occurred for modal windows used in Add Author, Add Contributor, Manage Access, and Send Group Invitation.
This PR fixes this behavior for all instances described above.
1. In Firefox, navigate to a Group page for which you can invite users.
2. In the Members tab, click on Invite People.
3. Start typing a name in the autocomplete.
4. Try selecting a name which hovers outside the area of the modal window.
5. Verify that the modal window does not get dismissed upon selection.
6. Repeat steps 3 to 5 for the following actions in resource landing page: …
> [#3434] Prevent clicking on list items dismissing the modal window

- hs_core/templates/pages/genericresource.html
- hs_core/templates/pages/my-resources.html
- hs_core/templatetags/hydroshare_tags.py
- theme/templates/pages/group.html
As deployed on beta, there is an extra column in the dashboard table shifting the rest of the columns to the right. This PR fixes this issue.
1. Verify that the columns in the dashboard table are aligned properly and contain the correct information.
> [RC-1.24] Remove extra column in dashboard table

- hs_core/templatetags/hydroshare_tags.py
Discovered a template rendering issue when verifying a bug fix on beta for RC 1.24. Have verified on inactive worker on beta that this PR would fix the resource landing page rendering issue for this resource: https://beta.hydroshare.org/resource/1bb3210918414e13b077e87798d4a696/
> [RC 1.24][#3439] fixed rendering issue when first author is an organization

- hs_access_control/models/community.py
- hs_access_control/models/user.py
@sblack-usu @pkdash @phuongdm @martinseul 
HOTFIX This is a performance upgrade for the access control system. 
Unbeknownst to me, the syntax `foo in queryset` is no longer converted automatically to `queryset.filter(id=foo.id).exists()`. This made all of access control run slower. 
This PR converts all slow syntaxes to their fast equivalents, across all of access control. This does not change function at all. 
This completely addresses #3481 . Gain in performance is so substantive that it is proposed as a HOTFIX. This is a rebasing of PR #3483.
Many thanks to @pkdash and @sblack-usu for their help in finding this. 
1. [Enter positive test case here] Nothing changes, but each resource landing page requires at least 7 seconds less to load. Pages that took 10 seconds take 3-4 seconds.
> HOTFIX issue 3481 speed up access control by 3x.

- hydroshare/defaults.py
- theme/templates/base.html
This addresses #3478 by exposing `settings.DEBUG` in mezzanine templates and then 
generating a `noindex` meta-tag whenever in `DEBUG` mode.
* `hydroshare/defaults.py` adds `DEBUG` to mezzanine `TEMPLATE_ACCESSIBLE_SETTINGS`.
* `theme/templates/base.html` generates a `noindex` directive if `settings.DEBUG` is `True`
* This inserts the tag into every page in HydroShare on a dev server. 
1. In production (`DEBUG=False`), all page sources appear as usual. 
2. In dev mode (`DEBUG=True`), all page headers contain
```<meta name="robots" content="noindex">```
to prevent google and other indexing of the pages. This is site wide.
> 3478 Expose settings.DEBUG in templates and insert noindex in DEBUG

- theme/static/js/hs_file_browser.js
Minor script modification to correctly bind select event in resource view mode.
1. Create a Composite Resource with a timeseries aggregation that has multiple sites. 
2. Verify that the dropdown listing the timeseries can be used to view metadata for each dropdown item.
> [#3569] Allow switching timeseries to view metadata in view mode

- theme/templates/resource-landing-page/subject.html
[#3592 ] Adds a reference attribute to the keywords input to fix an issue where comma separated keywords would not render until page reload.
2. Try to add comma separated keywords. I.e: "one, two, three".
3. Verify that all keywords are rendered correctly upon submit and that all subsequent operations work as expected (add, delete)
> [#3592] Fix rendering issue for comma separated keywords input

- hs_core/management/commands/solr_prepare.py
- hs_core/management/commands/solr_update.py
- hs_core/search_indexes.py
There are three major bugs fixed by this PR: 
1. Currently Composite Resources with no logical files are associated with no content types at all in discovery. If you search by content type they do not appear at all. This fix makes them all appear as "Generic Data". More than 1000 resources containing .csv files are affected.
2. Malformed start and end dates formerly crashed ingestion and caused the resource not to appear in discovery. Now malformed dates are simply ignored and the resource remains discoverable, but those dates remain blank and unsearchable. 
3. Debugging shows that the SOLR command `rebuild_index` does not work properly for a SOLR stack of our large size. The management command `solr_update` fixes any initial problems in `rebuild_index` and prints what it does. It is …
> POSSIBLE HOTFIX: Serious discovery shortcomings "discovered" and addressed. 

- hs_core/views/__init__.py
This fixes a bug in the CZO code. Somehow the group object wasn't being passed to the template when the user was unauthenticated. This means things couldn't be fetched from the user profile. 
1. Browse to group with an image in unauthenticated mode. Image should appear. Browse in authenticated mode. Image should be the same.
> Add group object to unauthenticated output.

- Dockerfile
- config/hydroshare-config.yaml
- hsctl
- hydroshare/settings.py
- scripts/templates/docker-compose.template
- scripts/templates/init-defaultworker.template
You can see an example of flower running on hydroshare (I like to call it hydro flower) at http://dev-hs-1.cuahsi.org:8080/
Flower runs on port 5555 and will only be accessible via vpn.  For testing, @phuongdm added a firewall rule for dev-hs-1 to map 5555 with the port 8080, allowing us to browse without being on the vpn.  This rule will not and should not be added to the production environment.  Developers may choose to expose flower on there dev machines.
This PR also starts celery with a concurrency of 4.
> Hydro flower

- hs_core/management/commands/solr_update.py
- hs_core/models.py
- hs_core/search_indexes.py
- hs_core/tests/api/native/test_content_types.py
- hydroshare/settings.py
1. Don't mangle names of organzations, e.g., "CZO Luquillo" stays as it is when used as an owner. 
2. Arrange for solr_update to refresh all records, not just non-existent ones.
3. Categorize the contained content type of composite resources containing files that correspond to common MIME file types -- and are otherwise undocumented by aggregations -- as higher-level characterizations `Document`, `Spreadsheet`, or `Presentation`, respectively. 
1. In names of users, organizations -- e.g., "CZO Luquillo" -- are not mangled by discover page after re-indexing. Owners show up as "First Last" rather than "Last, First".
2. Create a resource containing a `.csv`. Discovery by content type lists it as containing a`Spreadsheet`.
3, Create a resource with a `.doc` or `.pdf` file. Discover by content …
> 3623 discovery improvements

- hs_core/management/commands/add_owner.py
New management command `add_owner`
```
python manage.py add_owner dtarb 5d53e61cb25f4b89a7a28bd38ec01f6b
```
makes David an owner of one of my test resources. 'admin' is listed as the grantor. 
```
python manage.py add_owner --owned_by=alvacouch dtarb
```
makes *all* resources owned by `alvacouch` also owned by `dtarb`.
1. This command works even with resources that have no owner, and can be used to fix ownership botches. 
2. The command is idempotent: adding an owner who is already an owner does nothing. 
3. option --set_quota_holder sets the quota holder to the new owner. 
1. Run management command `python manage.py add_owner {username} {resource}`, display resource, verify that new owner has been added. 
2. Repeat management command exactly. Should do nothing. 
3. Add …
> 3625 bulk add owner

- Dockerfile-postgis
- local-dev.yml
9.5.0 has been removed and was only used by the local dev setup... This change updates local dev configuration to use 9.4.7
> update local dev to use 9.4.7 postgres image

- hs_core/management/commands/add_owner.py
The add_owner script previously trashed the PostgreSQL server due to a PostgreSQL misconfiguration. 
This fixes that, by serializing the updates and prohibiting the fast parallel updates that swamped the server. 
1. add owner of czo_national to czo_boulder resources doesn't crash PostgreSQL. :)
> Serialize add_owner database updates with transactions.

- theme/static/js/hs_file_browser.js
https://github.com/hydroshare/hydroshare/issues/3676 Fixes a regression issue preventing file browser to refresh automatically after an aggregation is created.
2. Create an aggregation on this resource.
3. Undo this aggregation by right-clicking on the file and selecting "Remove content type".
4. Restore the file's content type by right-clicking it and selecting an option under "Setcontent type".
5. At this point verify that your changes were applied automatically without the need to refresh the page.
> [#3676] Fix regression issue preventing file browser refresh.

- hs_core/management/commands/solr_update.py
- [NA] Automated Testing
- [NA] Sufficient User and Developer Documentation
1. Run the solr_update management command against a recent production data copy.  Confirm the command runs successfully and the "skipping <resource_id> resource in Django, metadata is None" message shows for 2 or 3 resources.
> add check in solr_update for None metadata

- hs_communities/views/communities.py
This simple PR adds the "admin" tab to the community page of any community owner. Additionally, it allows users who are not logged in to browse community data. 
Login as community owner. Admin tab should be shown. 
Go to community page without login. Tab should not be shown. 
Go to community page as non-owner. Tab should not be shown.
> Community landing page for owner and unauthenticated user

- hs_core/hydroshare/hs_bagit.py
When deleting a resource, this protects against crashes that leave Django in an inconsistent state, by logging and then ignoring iRODS errors. The Django record is reliably deleted even if iRODS fails. 
1. This is terribly difficult to test, in the sense that it only kicks in when iRODS fails for some reason.
> 3713 irods delete trap

- hs_core/hydroshare/hs_bagit.py
HOTFIX to deal with iRODS errors during delete. 
1. Hard to test. If iRODS fails, resources can still be deleted.
> HotFix to delete a resource during an iRODS failure.

- hs_core/management/commands/solr_update.py
Same as hotfix, for develop. Solr_update should not crash when a SOLR resource is no longer in Django. 
1. solr_update deletes the SOLR entry for any resource no longer in Django.
> Fix solr_update crash when SOLR resource is not in Django

- hs_communities/management/commands/check_czo_groups.output.txt
- hs_communities/management/commands/check_czo_groups.py
- hs_communities/management/commands/check_czo_groups_test.output.txt
- hs_communities/management/commands/check_czo_groups_test.py.txt
- hs_communities/management/commands/fix_czo_groups.py
This includes two management commands that both fixed existing CZO problems and found new ones -- and fixed them. 
* `fix_czo_groups`: no parameters, ensures that things that should not be a part of the CZO national group are not. 
* `check_czo_groups`: no parameters, enforces the following constraints: 
1. Each resource owned by a CZO owner is in the corresponding CZO group.  
2. Each resource in a CZO group is owned by the corresponding CZO owner. 
3. Each resource in a CZO group is shared with exactly one CZO group.
Note that this does not check that all resources are published, just that they are shared with the group.  
These were filed in hs_communities/management/commands to separate them from the standard management commands. 
After running these commands: 
1. Each CZO community …
> Management commands to check on and repair CZO groups.

- hs_core/management/commands/list_resources.py
There are a number of operations that need to be done on CZO resources. Notably, they aren't being discovered properly. This allows one to list them for use in other commands. For example
```
python manage.py list_resources --brief --owned_by czo_national
```
creates a list of resource ids that can be fed into another command to accomplish things like: 
```
python manage.py repair_solr `python manage.py list_resources --brief --owned_by czo_national`
```
which will try to repair all of them in SOLR. Additionally, 
```
python manage.py prepare_solr `python manage.py list_resources --brief --owned_by czo_national`
```
reports bugs in SOLR preparation code that are not reported by the script above. 
After running the commands above, CZO resources are …
> Add --owned_by option to list_resources to debug CZO resources

- hs_communities/templates/hs_communities/community.html
A redundant total resource display was created for migration debugging. Now that Production migration is complete, this can be removed, as the filters display a resource count per Group.
Fixes https://github.com/hydroshare/hydroshare/issues/3738
1. Log in as czo_sierra czone123
2. Create resource, make public, share with CZO Sierra Group
3. View resource in Community page and note there is no total resource count at bottom of page
> Remove debugging display

- hs_core/models.py
- hs_core/tests/api/native/test_get_resource_file.py
- hs_core/tests/api/rest/test_resource_file.py
- hs_core/views/resource_rest_api.py
- hs_core/views/serializers.py
1. Query /hsapi/resource/{id}/file_list/ and verify modified_time is included in the results
> [#3766] - stand up modified_time in api

- theme/static/js/hs-vue/manage-access-app.js
- theme/templates/includes/access-row.html
- theme/templates/resource-landing-page/manage-access.html
[#3534] This fixes a bug where users who are quota holders for a resource cannot change access of a group that has their same Id for the resource.
1. I tested this locally and it seemed to work correctly, but @dtarb will need to verify this fix by reproducing the steps outlined in #3534
> [#3534] Improve conditional to prevent comparing group ids against user ids

- hs_core/templates/pages/groups-authenticated.html
- hs_core/templates/pages/groups-unauthenticated.html
- theme/static/css/hydroshare_core.css
- theme/static/js/collaborate.js
- theme/templates/pages/group.html
#3629 Makes use of CSS flex to correctly display group cards at all times in Collaborate page.
1. Go to the Find Groups page
2. Clear your browser's cache so that group images get loaded upon next refresh.
3. Refresh the page and confirm that while it's loading all group cards are displayed correctly and their content does not overlap.
> [#3629] Improve Collaborate page layout

- nginx/config-files/hydroshare-local-nginx.conf.template
- nginx/config-files/hydroshare-nginx.conf.template
- nginx/config-files/hydroshare-ssl-nginx-ingress.conf.template
- nginx/config-files/hydroshare-ssl-nginx.conf.template
Set Nginx to avoid reverse proxy overhead for everything except download. 
This lessens the effect of (incompetent) denial-of-service attempts. 
This PR also implements request frequency limits on /tracking/applaunch on the switch instance of Nginx that chooses the active hydroshare instance to use. The configuration of that server is now archived as `hydroshare/nginx/config-files/hydroshare-ssl-nginx-ingress.conf.template` for documentation purposes. 
1. Do a download. Check logs for "proxying" entry. Check that download worked. 
2. Check all other functions. Function should be unchanged. 
3. Check /admin and /mezzanine functions, which should still work.
> Update Nginx to avoid needless reverse proxy

- theme/static/js/hs_file_browser.js
[#3741] Extends logic to allow UI metadata update after auto extracting metadata from single file upload.
2. Upload a .nc file.
3. Verify that the extracted metadata is correctly rendered in the rest of the page (title, abstract, etc) upon file upload without refreshing the page.
> [#3741] Allow metadata UI update after single file upload

- hs_composite_resource/page_processors.py
https://github.com/hydroshare/hydroshare/issues/3564 Adds conditionals to prevent out of sync messages from being shown to anonymous users or users who do not have Edit permission on the resource.
1. Create a Composite resource and add a .nc file to it so an aggregation is created.
2. Edit the resource and change the NetCDF aggregation metadata to make it out of sync. For example, you can edit the spatial coverage.
3. Refresh the page, and verify that the out of sync message shows up at the top of the page.
4. Verify that this message doesn't show up for anonymous users or users with no Edit permission on the resource.
> [#3564] Show out of sync messages only to users who can edit the resource

- theme/templates/base.html
1. When settings.DEBUG is True, `<meta name="robots" content="noindex">` should show on each page,  When DEBUG is false, it should not show.
2. When Settings.DEBUG is True, heap analytics should not be included on each page.  When DEBUG is false heap analytics should be referenced in a script tag on each page.
> turn off bot indexing and heap analytics when DEBUG is set to TRUE

- hs_collection_resource/page_processors.py
- hs_collection_resource/tests/test_utils.py
- hs_collection_resource/utils.py
- theme/templates/resource-landing-page/manage-access.html
1. Share/unshare a resource, refresh the page between and check to make sure the shareable checkbox is correct.
2. Create a composite resource with user1, make it public and shareable.  Create a collection resource with user1, validate the composite resource is available to add to the collection.  Create a collection resource with user2, add user1's composite resource to user2's my-resource, validate user1's composite resource is availabe to add to user2's collection resource.  Uncheck shareable on user1's composite resource.  Validate user1 can add the composite resource to it's collection.  Validate user2 can not add the composite resource to it's collection.
> Collection optimize bugfix

- gunicorn_start
- nginx/config-files/hydroshare-local-nginx.conf.template
- nginx/config-files/hydroshare-nginx.conf.template
- nginx/config-files/hydroshare-ssl-nginx.conf.template
This simple change modifies the Guincorn and NGINX configurations to turn off NGINX-based Django response buffering and replace this with gunicorn Django response buffering.  It utilizes 1000 pseudo-threads per worker to manage TCP connections from Django to the outside world. 
This enables a number of things, including streaming download from Django, and is recommended for I/o intensive applications like ours. 
See issue #3953 
> Turn on pseudo threads in gevent

- theme/templates/pages/dashboard.html
This pull request fixes an issue caused by launching the CUAHSI JupyterHub using the legacy url (i.e. jupyter.cuahsi.org). I believe the error occurs because the OAuth handshake begins before redirecting to the new url (jupyterhub.cuahsi.org) resulting in missing state cookies. This PR contains one simple change to the dashboard page to change the CUAHSI JupyterHub target url from jupyter.cuahsi.org to jupyterhub.cuahsi.org.
1. Go to HydroShare.org/home
2. Click CUAHSI JupyterHub
3. Verify that you are redirected to jupyterhub.cuahsi.org
4. Agree to the terms of use and login
5. Verify that a 400 error does not occur.
> #3959 Change JH app target URL to jupyterhub.cuahsi.org

- hs_core/models.py
- hs_file_types/models/reftimeseries.py
- hs_tools_resource/app_launch_helper.py
- hs_tools_resource/forms.py
- hs_tools_resource/tests/test_web_app.py
- hs_tools_resource/tests/test_web_app_validation.py
- hs_tools_resource/utils.py
1. Add a custom key to a web app url.  Mark all sharing permissions and Composite Resource type.  Add the web app to your open with list.  Go to a composite resource, validate the web app does not show.  Add additional metadata with the same key as the custom key provided in the web app and anything you'd like as the value.  Refresh the resource page and validate the web app appears.  Click the web app from the list and validate the url replaces the custom key with the value provided in your reosurce.
> include resource additional metadata as web app keys

- hs_core/search_indexes.py
Some new resources have blank start or end times, which crashes SOLR ingestion. This fixes that. 
1. [Enter positive test case here] SOLR ingests all current resources.
> Fix bug with blank start or end times in SOLR ingestion

- hs_collection_resource/tests/test_collection.py
- hs_collection_resource/tests/test_utils.py
- hs_collection_resource/utils.py
- hs_collection_resource/views.py
1. Create a collection resource.
2. Create a composite resource for which the owner is different from the collection resource. Set the composite resource to 'public'.
3. Edit the collection resource to add the composite resource to that collection. Verify that you are able to add the public composite resource to the collection.
4. Create another composite resource for which the owner is different from the collection resource. Set the composite resource to 'discoverable'.
5. Edit the collection resource to add the composite resource that you created in step#4 to that collection. Verify that you are able to add the discoverable composite resource to the collection.
> Allow public/discoverable resource to be part of collection resource

- hs_discover/src/components/Resources.vue
- hs_discover/views.py
QA has identified situations, where the UI can become usable, when filtering with no matches, then taking an action, such as opening the map. After further investigation, all checkbox filter and freetext search, map activation and date filtering have been changed back to mirror production HydroShare.
Functional review has been performed by Martin and Mark:
http://dev-hs-7.cuahsi.org/search/
- Select checkbox filters until no results are returned
- Search in the freetext area, note everything is reset and a new search started
> Fix overfiltering

- hs_app_timeseries/models.py
- hs_core/models.py
- hs_core/tests/api/native/test_bag_ingestion.py
- hs_file_types/models/timeseries.py
An amendement to the bag ingestion branch which includes rdf/xml for timeseries.  It also adds a citations entry for the resource rdf/xml.
Timeseries breaks all the normal conventions for storing the metadata, so I had to overwrite the hs_rdf methods.  Each timeseries metadata element has a series id.  That series id is used to tie the element to a timeseriesresult.  In the rdf/xml, instead of using a series id, it just includes each of the corresponding elements within the timeseriesresult.  For ingestion, this process has to be reversed.  A test was added to test_bag_ingestion.py for timeseries.
Citations are mostly straightforward, but needed some custom code to account for custom vs default citations.  I talked to @horsburgh about how to identify a custom citation vs a default …
> Bag ingestion timeseries citations

- nginx/config-files/hydroshare-ssl-nginx.conf.template
- nginx/hs_proxy/nginx/config-files/hydroshare-ssl-nginx.conf.template
This adds the following URLS to the NGINX proxies:
* `http://nginx-outer/whatszupdoc-outer`: status report on outer server. 
* `http://nginx-outer/whatszupdoc-inner`: status report on inner server. 
* `http://nginx-inner/whatzupdoc-inner`: status report on inner server. 
Each of these URLs servers as an NGINX heartbeat for the outer and/or inner servers. http is used rather than https to allow the inner server to be queried directly. These heartbeats are only available in the RENCI domain. 
The purpose of this change is to incorporate queries of this kind in the Jenkins watchdog scripts. These URLS report number of NGINX connections and activities, so we should be able to determine why the site is crashing from this input. 
URLS respond with appropriate …
> Add watchdog URLs in http mode to outer and inner nginx proxies

- django_irods/views.py
- hs_core/task_utils.py
Found a side effect with async tasks and enabling api downloads through the same entry point as web downloads.  An api download with credentials will create a tasknotification for the credentials used, which can then trigger a download if the user is logged in on the website.  This fix distinguishes api vs browser requests by looking for the csrf token in the header.  The csrf token will only exist on browser requests.
1. Trigger a bag and zip download via the api.  Login to hydroshare with the same credentials and ensure a download doesn't trigger when the zip is ready.
> turn off TaskNotification creation for api downloads

- hs_core/hs_rdf.py
- hs_core/hydroshare/hs_bagit.py
- hs_core/hydroshare/utils.py
- hs_core/tests/utils/test_utils.py
When regenerating the bag resourcemap.xml files, we noticed a lot of warnings from rdflib for unencoded urls.  This PR addresses the issue and also includes url encoding for resource and aggregation metadata files.
1. Create a resource with a space in a file and folder name.  Download the bag and check the resourcemap.url to ensure the file url is properly encoded with the `space` replaced with `%20`.
> url encode resourcemap urls

- hs_core/tests/data/test_resource_metadata_files/ODM2_Multi_Site_One_Variable_meta.xml
- hs_file_types/models/timeseries.py
I noticed abstract went missing from the rdf/xml for timeseries aggregation.  After looking into why it was getting picked up with the other fields, I noticed it's by itself and not part of the rest of the timeseries metadata.  This PR accounts for that difference with a test for rdf/xml creation and ingestion.
1. Download the timeseries aggregation rdf/xml with an abstract and verify it's present with predicate DC.abstract.
> add missing abstract to timeseries rdf/xml

- hs_file_types/models/base.py
Aggregation map rdf/xml urls are not currently url encoded.  This PR encodes all urls in these files for all aggregation types.
1. Create a singlefile aggregtion on a file with spaces in the name.  Download the aggregations _map.xml file and ensure the urls to your file have the spaces url encoded.
> encode urls in aggregation map rdf/xml file

- django_irods/views.py
- hs_core/tasks.py
- hs_file_types/utils.py
- hydroshare/settings.py
This is a minor update for the bagit file downloads.  I found out that the metadata-dirty flag isn't always reliable and a check for the file on irods is needed.
1. Download one of the bagit files in a newly created resource, ensure the bagit file downloads.
> check for bagit file exists before download

- .gitignore
> Allow dev deployments to survive network interruption

- hs_core/hydro_realtime_signal_processor.py
- hs_core/hydroshare/resource.py
- hs_core/management/commands/solr_update.py
This is a simple fix to the "discovered" problem that deleting a discoverable resource corrupts SOLR. There are three parts: 
1. Make a resource undiscoverable before any deletion. 
2. Correct solr_update so that it doesn't crash under these conditions. 
3. Remove the useless handle_delete function by making it non-operative. 
This will fix the problem, but there are other changes to be made later: 
To the best of my knowledge, this still allows the REST API to delete a published resource. This is bad. 
1. Create a resource. Make it discoverable. Delete it. It should disappear from the Discovery page.
> Fix for SOLR corruption problem.

- theme/templates/includes/navbar.html
- theme/templates/newbase.html
Navbar has too many dependencies squirreled away in various depths of code includes, assumptions about global scope and Django extends. Bring csrf functions into navbar code (for resource creation), collecting first then will dedupe over time and sub out css, script files.
- Ensure create resource works
- Review basic functionality/layout of Discover as presumably stale scripts have been removed
> Remove stale code make navbar more independent

- hs_access_control/models/user.py
Address issue #4134 by not returning Permission Denied for calls to can_undo_* concerning inactive users or groups. Just return False. 
This fixes an issue reported by @horsburgh that resources become inaccessible with shared with inactive users. 
1. If a user is set to inactive, this no longer hides access to resources the user can view.
> No exception when checking for undo involving inactive user or group 

- hs_core/debug_urls.py
- hs_core/management/commands/check_irods_files.py
The check for the metadata XML files works fine in the debug URL but it was not working in the management command. Turns out the management command is running off a BaseResource object instead of a CompositeResource object. The BaseResource implementation of is_aggregation_xml_file always returns false. The implementation of is_aggregation_xml_file in CompositeResource has an implementation to check if it's a logical file metadata XML file. The solution is to use a CompositeResource object instead of a BaseResource object in the management command when the resource is a Composite type.
I also included an update to the resource debug URL because of a change to downloads that caused the previous debug URL to route to a download which will always fail.
1. Run the check_irods_files management …
> 4191 meta xml file check fix for check_irods_files

- hs_discover/views.py
Looks like we missed one more updated index name.  This change fixes author sorting.  I also search hs_discover/views.py to ensure there were no more remaining _exact indexes within the view.
> fix author sorting in discover

- hs_core/hydro_realtime_signal_processor.py
Found logs showing an error with the signal processor when handling metadata on logical files.  This patch fixes the error.
> add support for metadata on logical files

- hydroshare/urls.py
The token parameter on new_password_for_reset was removed from reverse calls but the urls.py entry was not updated.
> [#4219] - remove unused token parameter for new_password_for_reset

- hs_core/tests/api/rest/test_resource_science_meta.py
- hs_core/views/__init__.py
fixes #4309 
1.  GET `/hsapi/resource/{id}/scimeta/custom/` without authentication on a public resource
> [#4309] - use view authorization for extra_metadata GET

- theme/static/js/resourceLandingAjax.js
There is a deeper issue with form validation feedback on the backend.  I spent some time looking into the backend issue.  Basically, there is some[ validation in the coverage clean() method ](https://github.com/hydroshare/hydroshare/blame/develop/hs_core/forms.py#L1021-L1022) that removes the invalid data before returning the cleaned_data.  That modified form data is then passed to the Coverage metadata element which fails to create because the fields are missing.  There is some error messaging done in the clean_data method that I don't recognize, I'm not sure if I remove it if I'll break coverage in another area, so I left it alone. 
If someone has insight on the backend issue, I'm open to talking about it and implementing a solution.  The PR as it is, however, fixes the user experience …
> [#4272] - handle non-json responses

- hs_discover/public/index.html
- hs_discover/src/components/Search.vue
- hs_discover/src/main.js
This is a survey that will run temporarily.  The survey tab is shown to all users on the discover page.  The survey pops-out 60 seconds after initial search.  After a user has completed the survey, a cookie is created and the next time the user loads the discover page, the survey tab will not show up.
**This merge will be reverted once the survey is complete.**
1. Navigate to Discover, verify the survey tab shows on the right side.  
2. Look at the source of the Discover page, verify the div with attribute `data-tf-hidden` has a value containing the email if you're logged in and the session cookie.
3. Do a search via the textbox or facet, wait 60 seconds and verify the survey tab pops-out.  
4. Complete the survey and reload the discover page, verify the survey tab does not show.
> [#4322] - add popout with cookie support and delay after first search

- theme/templatetags/dashboard_tags.py
I missed the title in the recently visited section
1. Put an HTML snippet in a resource title and navigate to home.  Verify the title doesn't render in the recently visited section.
> [#3683] - escape resource title in recently visited

- hs_core/templates/pages/genericresource.html
1. Create a resource. Upload a file to the resource.
2. Add needed metadata to make the resource discoverable
3. Make the resource discoverable
4. Logout. Then try to access the resource. On the resource landing page check that you see the following message under the "**Content**' section:
You do not have permission to see these content files. Please contact an Owner if you wish to obtain access.
> 4434 message text change for accessing content files

- hs_tools_resource/forms.py
- hs_tools_resource/models.py
1. Create a new web app connector
2. Reduce your screen size until the bootstrap "sm" styles kick in
3. Scroll down to the Icon URL/FILE section
4. The preview no longer hangs off the side of the page
This PR resolves #4493 
This PR fixes merged issues from PR #4479 
##After
> tool icon preview responsive margins Resolves #4493 

- hs_core/management/commands/solr_count.py
This provides data to debug issue 4264 -- discrepancies in counts between django and solr. 
A single management command `solr_count.py` computes counts of what is in Django, what is in Solr, and the versions that are omitted from SOLR but present in Django.  
> Debugging tool for counting SOLR records.

- hs_core/management/commands/migrate_ispartof_not_collection_related.py
- hs_core/tests/api/native/test_ispartof_to_isreferencedby_update_command.py
- theme/templates/resource-landing-page/references.html
1.  The migration command to update the relation type 'isPartOf' (which were originally created by users) to relation type 'isReferencedBy'  needs to be tested as part of beta deployment. 
2. Create a resource (composite).
3. Create a collection resource and make the composite resource as part of the collection.
4. View the composite resource both in view and edit mode. Verify that the 'isPartOf' relation is not displayed in the 'Related Resources' section.
> 4495 Fix 'is part of' relations

- theme/static/js/hs_file_browser.js
1. Right click a file or files in the content browser
2. Left click outside the content browser
3. Observe the right click context menu goes away
Resolves #4140
___
> dismiss context menu when click outside of it

- theme/static/css/hydroshare_core.css
- theme/static/js/hs-vue/manage-access-app.js
- theme/static/js/resourceLandingAjax.js
- theme/templates/resource-landing-page/manage-access.html
1. Go to a resource that you do not own, that is private and that you have edit permission on.
2. Add information to the resource such as a keyword or file that makes its metadata sufficient for it to be made public.
3. Message prompting you to publish will not appear
4. Now "Manage who has access"
5. The sharing status "public/discoverable" buttons are inactivated
Resolves #4374 
Resolves #4375
> Only prompt to publish if user has auth to publish resource

- theme/static/js/resourceLandingAjax.js
2. Edit temporal coverage dates
3. You will not be able to "Save Changes" until you have completed both dates
Resolves #3451
> Prevent temporal coverage submit unless dates are completed

- hs_access_control/models/user.py
- hs_core/page_processors.py
- hs_core/views/utils.py
1. Create a resource. Upload a file to the resource. Enable private link sharing using the Manage Access panel. Make sure the resource status is private. Copy the url of the resource.
2. Create a new user account
3. Use another browser
3.1 Login to hydroshare as the user account you created in step 2.
3.2 Paste the url of the resource in the browser for the hydroshare site.
3.3 You should see the landing page for the resource in view mode only. The resource file should be listed.
> 4541 Fix for private resource access authorization

- theme/static/css/hydroshare_core.css
- theme/templates/includes/access-row.html
1. Manage who has access on a resource that you own
2. "Give Access" to a different user and a different group. Importantly, the user id must match the group id. To ensure this, I checked the "auth_user" and "auth_user_groups" tables in the db. You could of course python model query or use browser console and USERS_JSON to find a set of group+user whose ids match.
3. After adding the user and group, you will notice that the "undo share" and "remove" actions are still available (whereas before this PR, they were missing).
Resolves #3534
***
BEFORE:
***
AFTER:
> fix actions in "who has access" table

- hs_core/templates/pages/apps.html
- theme/static/css/apps_page.css
Resolves #4559
1. Navigate to the Apps Library (if on dev machine, make sure to type `[hostname]/apps/ ` in the URL because clicking on "apps" navigation will take you to production www.hydroshare.org)
2. Reduce your screen width to between 768px-1000px
3. There are now 2 columns of apps instead of 1
***
> responsive breakpoints for app tiles

- hs_communities/templates/hs_communities/find-communities.html
- hs_core/templates/pages/groups-authenticated.html
- hs_core/templates/pages/groups-unauthenticated.html
- theme/static/css/hydroshare_core.css
Resolves #4552 
1. Navigate to Communities (if on dev machine, make sure to type [hostname]/communities/ in the URL because "Collaborate"->"Communities" navigation will take you to production [www.hydroshare.org](http://www.hydroshare.org/))
2. Reduce your screen width to between 768px-1000px
3. Community containers are now a consistent width
4. Same is true for Group containers
***
> group-containers bootstrap breakpoint

- hs_core/hydroshare/users.py
- hs_core/tests/api/rest/test_resource_list.py
1. Create 3 or more composite resources. Add coverage metadata to all resources except one. 
2. Use the following REST endpoint format in the browser (in another tab) to list resources by coverage (change the value for query parameters for coverage bounding box (north, south, east, and west) as necessary:
`http://localhost:8000/hsapi/resource/?resource_type=CompositeResource&coverage_type=box&north=41.8671&south=41.8639&east=-111.5059&west=-111.5114`
4. Verify that the resource with no coverage is not listed when you use the above endpoint.
> 2280 Fix for resource listing by coverage

- hs_communities/templates/hs_communities/find-communities.html
- hs_core/templates/pages/groups-authenticated.html
- hs_core/templates/pages/groups-unauthenticated.html
- theme/static/css/hydroshare_core.css
Resolves #4590 
1. With a user you don't mind deactivating, create a new group
2. Add a long (>1000char) group description and make sure the group is PUBLIC
3. Deactivate the user account (using the profile -> deactivate)
4. navigate to `/groups`
5. See that the description can now flex-grow to take up more space since the "members" section is blank
NOTE: this PR also increases (just slightly) the `group-container` gap and the grid column width on the /groups page, so that the groups page more closely resembles the 3-columns that were used historically
> less whitespace for groups without members [#4590]

- hs_core/templates/pages/groups-authenticated.html
- hs_core/templates/pages/my-groups.html
- theme/templates/pages/group.html
1. Create a group. In the create group modal page, verify the text change as per the issue #4656 
2. Edit the group and verify the text change in the group edit modal page.
> [#4656] fixing wording in group related pages

- theme/static/js/custom.js
Resolves #4660 
This is difficult to test until beta staging. The following **sed** command is run as part of deployment
```
sed -i s,\"https\:\/\/appsdev\.hydroshare\.org\/apps\",\"https\:\/\/www\.hydroshare\.org\/apps\",g theme/static/js/custom.js || exit 1
```
That is why "Apps" was opening a new tab in spite of the target seemingly being "_self":
https://github.com/hydroshare/hydroshare/blob/develop/theme/templates/includes/navbar.html#L294
> [#4660] target self for APPS nav

- hs_core/views/utils.py
1. Create new resource
2. Add a file
3. Download as zipped bagit
4. Upload the zip that you just downloaded back into the resource
5. Unzip in place withing the File browser
6. The directory created now contains the original files
Fixes #4759
> [#4759] fix emply zip when nested directory name contains res_id

- theme/static/js/coverageMap.js
#4784 There is a bug in google maps where calling `fitBounds` while the map is using the `restriction` option, will cause the method to set incorrect bounds. The only reliable workaround is to call the method twice.
https://stackoverflow.com/questions/54712021/map-fitbounds-works-weird-when-map-has-restriction-option-set
This change will fix this issue and allow the map to correctly zoom/center into the drawn coverage.
2. Add a box spatial coverage.
3. Reload the page in both view and edit mode and verify that the map is initially centered/zoomed in correctly.
> 4784- Workaround for `fitBounce` and `restriction` option

- theme/static/js/coordinates-picker.js
- theme/static/js/coverageMap.js
Fixes #4821 
1. Create a resource and zoom the coverage map in as far as it can go
2. Add a small BOX spatial coverage
3. Refresh the page
4. The zoom is no longer limited to level "7" -- it will zoom in as far as possible on your spatial coverage, limited by zoom level 18 which is the limit for the map tiles.
> [#4821] coverage map zoom

- theme/static/js/coordinates-picker.js
- theme/static/js/coverageMap.js
Resolves #4826. Intended release as a hotfix 1.60.1
1. Add point spatial coverage to a resource
2. Refresh the page
3. The map no longer zooms in so far that you can't tell where the point is
> [#4826] dont zoom max for point coverage

- theme/static/js/coordinates-picker.js
Resolves #4824. Intended release as a hotfix 1.60.1
1. Create resource and add box resource level coverage
2. Create aggregation and add box coverage to its metadata. Click out of the FB so that the metadata inputs are hidden.
3. Modify the resource level coverage to be a POINT and save it
4. Expected input boxes (for either box OR point but not both) are shown. No error in js console
> 4824 aggregation spatial coverage inputs

- hs_core/tasks.py
- hydroshare/local_settings.cutover
- hydroshare/local_settings.template
- hydroshare/settings.py
Resolves #4811 
1. Toggle `DISABLE_TASK_EMAILS` in your local_settings.py
2. `True` should prevent celery tasks from sending emails
> [#4811] prevent pub date warnings from beta

- theme/static/js/custom.js
Resolves #4215 
1. Login as a user whose profile is not complete
2. Create a new resource
3. The blue alert indicating profile incomplete is now dismissable
> [#4215] profile alert dismissable

- nginx/config-files/hydroshare-local-nginx.conf.template
- nginx/config-files/hydroshare-nginx.conf.template
- nginx/config-files/hydroshare-ssl-nginx.conf.template
Resolves #4873 by partially reverting PR https://github.com/hydroshare/hydroshare/pull/4687
1. Deploy to beta
2. After deploy, run `hsctl maint_on` (note this is different than running the maintenance on Jenkins job)
3. You will see the maintenance page instead of broken redirect
> [#4873] maint redirect within nginx container

- hs_core/tasks.py
hotfix = 2.0.2
resolves #4878 which was introduced in 2.0 release by https://github.com/hydroshare/hydroshare/pull/4803
To test this, I deployed the following branch to beta inactive worker:
https://github.com/hydroshare/hydroshare/tree/no-merge-demo-tasks
This branch includes this hotfix plus the following commit:
https://github.com/hydroshare/hydroshare/commit/21ad7c935c54ceb88d39955eb0f73f8e8d92716a
in order to demonstrate that periodic tasks start running (and in this case, intentionally failing) again
Check the result:
beta inactive flower
> [#4878] celery 2.0.2 hotfix

- hs_core/tasks.py
Resolves #4630 (this is a patch so that celery job doesn't fail)
The actual issue is that hs_data_services needs to return content:
https://github.com/hydroshare/hs_data_services/issues/1
This PR is difficult to test locally. To do so, you would need to run a local version of hs_data_services and geoserver, or add the API key for one of our existing servers into your local_setttings.py in your dev env (not recommended). So I suggest we:
1. Deploy to beta
2. Check Flower to see that update_web_services async task no longer fails attempting to parse nonexistent json
3. Check that Geoserver mapping service links still work as expected.
> [#4630] check response in update_web_services async task

- Dockerfile
- hs_core/apps.py
- hs_core/tasks.py
- hsctl
- hydroshare/health_check.py
- hydroshare/settings.py
- hydroshare/urls.py
Resolves #4888 
In addition, I created a Jenkins job that checks for 200 from /ht (the endpoint for system status) and checks the Flower api to see if there have been any recent failures:
https://new-hs-ci.hydroshare.org/view/04-Monitors/job/celery-periodic-task-monitor/
This job needs to be updated so that it targets prod instead of beta when this PR gets released
1. This PR is best tested by deployment to Beta
2. We can check that the new [periodic task](https://github.com/hydroshare/hydroshare/blob/4888-celery-heartbeat/hs_core/tasks.py#L143) exports a date string as expected.
3. We can check that the new health check page is operational at beta.hydroshare.org/ht
4. We can ensure that the new Jenkins job fails/passes as expected
> 4888 celery health check

- theme/templates/resource-landing-page/resource-header.html
Resolves #4862 
1. Make a discoverable resource
2. In EDIT mode, the "i" info icon for Author Sorting is visible
3. In VIEW mode, the icon is not visible
5. Make the resource public
6. Submit a resource for metadata review / publication
7. The "i" info icon for Author Sorting is not visible in edit or view mode of the resource
> [#4862] Conditional showing of Author sort icon

- hs_core/hydroshare/resource.py
- hs_core/tasks.py
Resolves #4957
by adding some additional logging and notification so that we can catch this issue when it happens again.
1. Because we don't know why resources are getting into a "pending" publication state and staying there (without XML being sent to Crossref), testing this locally is a bit convoluted.
2. Create a resource
3. Using python shell or directly editing the db, set `resource.doi="pending"`
4. Call [tasks.manage_task_hourly()](https://github.com/hydroshare/hydroshare/blob/4957-pending-publication/hs_core/tasks.py#L150) and ensure that it sends an email (to the logs for local dev) notifying that the resource is in a broken state. Or Enable celery tasks to run locally by setting `DISABLE_PERIODIC_TASKS = False` and wait for the celery job to run.
> [#4957] log/notify for unpublished pending res

- hs_core/views/__init__.py
- theme/templates/resource-landing-page/manage-access.html
Resolves #4958
Resolves #4946 
1. Create a resource and add metadata to make public
2. Click the PUBLISH button and accept in the modals to put the res in "review_pending"
3. See that, once in "review pending" the resource can no longer be made discoverable/private
> [#4946] Sharing status shouldn't be modifiable during metadata review

- hs_core/management/commands/prevent_web_crawling.py
- hs_core/templates/pages/baseresource.html
- hsctl
- local-dev-first-start-only.sh
- theme/templates/pages/homepage.html
Resolves #4984
1. Rebuild your local containers
2. Visit http://localhost/admin/robots/rule and see that a Rule has been created to prevent webcrawlers to `/`
3. Visit http://localhost/robots.txt to see the dissallow rules
This PR has changes to hsctl that will need update on beta and other test/dev systems
We also will update the ROBOTS_SITEMAP_URLS
https://github.com/hydroshare/hydroshare/blob/4948-robots/hydroshare/settings.py#L183
on production and beta local_settings.py. Currently they map to localhost:8000
> [#4948] expose schema.org on dev, prevent robots

- hs_core/templatetags/hydroshare_tags.py
Resolves #4987 
by fixing a regression that I introduced in 
https://github.com/hydroshare/hydroshare/pull/4717
2. Add an Organization as an author
3. Delete the original first author so that the Org is the sole author of the resource
4. Go to My Resources
5. My Resources now lists the ORG name instead of "None"
> [#4987] Display org as first author on My Resources list

- theme/static/js/hs-vue/geoconnex.js
- theme/templates/resource-landing-page/geoconnex.html
Resolves #4994 by allowing custom text to be entered on Geoconnex Relations
2. Attempt to add a Geospatial Relation with custom text (by typing in the second box) 
3. No longer errors messages in UI/console
> handle custom text in geospatial relations

- theme/static/js/hs-vue/geoconnex.js
Resolves #5019 
1. On a resource, open browser console and select a Geoconnex collection to search
2. Note that there are at most 3 requests sent to the Geoconnex API, instead of a separate request for every single feature in the collection
> [#5019] don't query nameField for every feature

- hs_core/tasks.py
- hs_file_types/views.py
- hs_rest_api/tests/http/test_aggregation.py
1. Locally create a resource. Create a folder in that resource. Create a raster or netcdf aggregation at the root of the resource.
2. Access the REST API swagger UI at localhost:8000/hsapi
3. Use the endpoint (`/resource/{resource_id}/{hs_file_type}/{file_path}/functions/move-file-type/{tgt_path}`) to move the aggregation to the folder. Verify the endpoint post request response status code is 200. 
4. Using the resource landing page verify that the aggregation exists inside the folder.
> [#5028] Move aggregation endpoint fix

- hs_core/hydroshare/utils.py
Resolves #5032
The [update_from_geoconnex_task](https://github.com/hydroshare/hydroshare/blob/5032_geoconnex_isurl/hs_core/tasks.py#L250) was making calls to the Geoconnex API even when the [GeospatialRelation](https://github.com/hydroshare/hydroshare/blob/5032_geoconnex_isurl/hs_core/models.py#L1138) was a "custom" relation (in which case the feature is not included in the API).
This PR modifies the task so that API calls are only made for GeospatialRelations that have a valid Geoconnex URL
1. Create a resource and add a CUSTOM geospatial relation by typing it in and hitting enter: 
2. Open a shell and run the [update_from_geoconnex_task](https://github.com/hydroshare/hydroshare/blob/5032_geoconnex_isurl/hs_core/tasks.py#L250)
3. The task no longer fails with `  File …
> [#5032] add url validator for geoconnex task

- hs_tracking/middleware.py
- hs_tracking/tests/test_tracking.py
- hs_tracking/utils.py
Resolves #5089
1. Interact with a resource (say download it)
2. Run some SQL `SELECT * FROM "public"."hs_tracking_variable" ORDER BY "timestamp" DESC LIMIT 100 OFFSET 0;`
3. See that the `user_email_domain_full` is recorded (not for every visit, just for begin_session, delete, create, download)
> add full email domain for metrics

- hs_tracking/tests/test_tracking.py
- hs_tracking/utils.py
Resolves #5082
1. Interact with a resource (say download it)
2. Run some SQL `SELECT * FROM "public"."hs_tracking_variable" ORDER BY "timestamp" DESC LIMIT 100 OFFSET 0;`
3. See that the user_agent is recorded (not for every visit, just for begin_session, delete, create, download)
> [#5082] add user agent for metrics

- hs_core/tests/api/rest/test_model_aggregations.py
- hs_file_types/views.py
1. Locally create a composite resource. Create a model instance aggregation.
2. Access the UI for Hydroshare REST API at /hsapi
3. Use this endpoint (/resource/{resource_id}/modelinstance/meta/{aggregation_path}) to retrieve metadata for the model instance aggregation you created in step 1.
4. Verify that you are as an owner of the resource able to retrieve aggregation metadata for this private resource.
5. Logout. Use the same endpoint (as in step 3) to access the metadata for the model instance aggregation. Verify that you are not able to retrieve metadata when the resource is private.
6. Login and make the resource discoverable.
7. Logout. Use the same endpoint (as in step 3) to access the metadata for the model instance aggregation. Verify that you are able to retrieve metadata when …
> 5093-aggregation rest api permission issue

- hs_core/views/resource_rest_api.py
1. In order to test locally, you have to create a resource and add around 300 files to that resource. 
2. Then access the Swagger UI at localhost:8000/resource/hsapi
3. Using the Swagger UI, access the endpoint for file list (**GET /resource/{id}/files**)
4. For id, enter the resource id and then click the Execute button. 
5. Verify, that you don't see a 504 timeout error when the server sends the response. You should see a list of 100 files in the response. Note down the response time.
6. In order to list only 10 files, enter 10 in the count field. Then execute the endpoint. You should see 10 files in the response. Verify the response time to list 10 files is much less than for 100 files.
Alternatively, test using beta. 
1. Use this resource id (**b7b75f28536a4bc79af80a51763f05b7**) to …
> [#5111] Fix for resource file list endpoint timeout error

- hs_rest_api/discovery.py
Resolves #5092
As part of this work, I tried to update discovery tests
https://github.com/hydroshare/hydroshare/blob/5092-haystack-endpoint/hs_rest_api/tests/http/test_discover.py#L18
but was unable to get them to run. Seems like for some reason these tests don't use the test database? The assertions around resource numbers are wrong because it finds existing resources in my database.
I'm not sure if the testing issues are related to https://github.com/hydroshare/hydroshare/issues/5099
2. GET [http://localhost:8000/hsapi/resource/search](http://localhost:8000/hsapi/resource/search) now returns the `short_id` for the discovered resource
> [#5092] Discover search return short_id

- theme/static/js/resourceLandingAjax.js
Resolves #5117 
1. Create an aggregation within a resource
2. Delete it
3. Cursor returns to default after deletion completes
> [#5117] reset cursor after aggregation delete

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/hydroshare/resource.py
- hs_core/models.py
1. Create a resource. Upload a readme.md or readme.txt file to the root of the resource. Upload few other files.
2. Create an external web reference aggregation, by right clicking inside the file list area of the UI and selecting the option "Add content from the web"
3. Access the resource landing page. Verify that the contents of the readme file are displayed as well as the aggregation that you created is displayed.
> [#5126] optimize search for readme file

- django_irods/views.py
- hs_core/hydroshare/resource.py
- hs_core/hydroshare/utils.py
- hs_core/tasks.py
- hs_core/tests/api/native/test_add_resource_files.py
- hs_core/tests/api/native/test_bagit.py
This PR is a replica of https://github.com/hydroshare/hydroshare/pull/5136 but uses a rebase to avoid other issues merged to Develop branch.
Intent is to release this as hotfix 2.7.1
Resolves #5135 
I think it will also resolve #5128
2. Add a file to the resource
3. Download the resourcemap.xml using for example: http://localhost:8000/resource/RESID/data/resourcemap.xml
4. Use the File Browser UI to download the resource as a zip
5. See that the zip data/contents/ contains the file that you added to the resource
> [#5135] bag_modified->False after create zip

- hs_core/middleware.py
- hydroshare/settings.py
- theme/templates/accounts/account_login.html
Partially resolves #5157 by 
- adding sunset headers for requests made with basic auth
- adding notification of impending CUAHSI SSO migration on the sign-in page
Intent is that this PR be released as 2.9.2 minor release ASAP to be followed by https://github.com/hydroshare/hydroshare/pull/5152 a couple weeks later as 2.10
In addition to deploying this PR, we would add banner notification:
“Attention: HydroShare login will soon transition to CUAHSI single sign on. Click here to learn more.”
1. Make a request with basic auth to any hsapi endpoint.
2. Response headers should contain the sunset header
``` allow: GET,HEAD,OPTIONS  content-language: en  content-length: 112  content-type: application/json  date: Thu,14 Sep 2023 15:22:15 GMT  link: <https://help.hydroshare.org>; rel="sunset"; …
```
> [#5157] Add CUAHSI SSO messaging

- hs_tracking/management/commands/stats.py
Will require updating Jenkins job with proper headers and same for docker-elk logstash ingestion
resolves #5216
2. run `./hsctl managepy stats --resources-details`
3. See that the resource id is included on the stdout
> include resource id in stats command

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/models.py
- hs_core/templates/pages/my-resources.html
- hs_core/views/__init__.py
- hs_core/views/utils.py
- theme/templates/includes/my-resources-trows.html
1. The query optimization implemented in this PR, will be noticeable in terms of page load time for the 'my-resources' page by users who have large number of owned resources (~200).
2. For the purpose of testing page load improvement, you have to create at least 100 resources. Then compare the page load time for the 'my-resources' page between this branch and develop branch. You should see better page load time with this branch compared to the develop branch.
> [#4091] my resources optimization

- hs_core/tests/api/rest/test_resource_list.py
- hs_core/views/resource_rest_api.py
Right now spatial queries of any kind on `/hsapi/resource` endpoint will timeout.
This causes one of our gunicorn workers to remain at 100% CPU for ~300sec.
If multiple such requests are made in a short period of time, all of our gunicorn workers get tied and HS stops responding to any other requests.
1. try a hsapi spatial query like the following `/hsapi/resource/?coverage_type=box`
2. see a validation error
> [#5240] disable spatial query in hsapi

- hs_composite_resource/tests/test_composite_resource.py
- hs_core/admin.py
- hs_core/models.py
- hs_core/tasks.py
Resolves #5275 
Prevents delete of a user account from the admin panel if the user is a creator on a published resource.
Also allows resource copy/version to succeed even if one of the creators on the resource has been deleted.
1. Add a user "User1" as an author on a resource "Res1"
2. Use the admin panel to delete User1
3. Version "Res1"
4. See that versioning succeeds
5. Create a copy of "Res1"
6. See that copy succeeds
7. Create add "User2" as an author on a resource "Res2"
8. Publish Res2
9. Using the admin panel, attempt to delete User2
10. See that you cannot delete User2 because they are a Creator on a published resource
> [#5275] non-existent user for res copy/version

- hs_core/management/commands/repair_resource.py
- hs_core/management/utils.py
1. Create a resource and add some files
2. Use the database or shell to remove some of the files from django to put the resource in  a "broken" state
3. Publish the resource
4. Run the `repair_resource --published --admin` management command and see that the published resource can now be fixed by the management script
> add ability to repair_resource as admin user

- hs_core/tasks.py
Related to #5265 we have some tasks that are failing (in that case due to iRods recursion)
Rather than emailing HELP on task failure, here we send email to `DEFAULT_FROM_EMAIL`
Also small change to make sure that tasks get marked FAILED.
> [#5265] failed celery task -- change notification email

- theme/templates/base.html
Resolves #5291 by pinning version of Vue that we fetch from CDN
The last version of Vue2 is 2.7.16. It was released last week. This caused issues with our bootstrap-typeahead implementation.
1. Start typing a Subject Keyword
2. See that the existing keywords no longer disappear
> [#5291] pin vue version @2.7.15

- Dockerfile
- hs_core/models.py
- hs_core/tests/api/native/test_publish_resource.py
Resolves #5321 by changing the `timestamp` in the XML deposited with Crossref
1. Use the Crossref test API to submit a resource for publication
2. Then use the `update_crossref_metadata_deposit` management command to re-submit the XML for the resource (without any changes to the metadata)
3. See that the record in Crossref does not have a failure due to timestamp duplication
> [#5321] Update timestamp in XML generation

- hs_core/management/commands/repair_resource.py
Resolves #5335 by adding ability to ignore recently repaired resources
1. Create a resource and add some files
2. Use the database or shell to remove some of the files from django to put the resource in  a "broken" state
3. Publish the resource
4. Run the `hsctl managepy repair_resource --published --admin --ignore_repaired_since 7` management command and see that the published resource is repaired
5. Use the database or shell to remove some of the files from django to put the resource in  a "broken" state
6. Run the `hsctl managepy repair_resource --published --admin --ignore_repaired_since 7` management command and see that the resource is not repaired because you chose to `--ignore_repaired_since`
> [ #5335] Filter to ignored_repaired_since when repairing resource

- hs_core/models.py
- hs_core/views/__init__.py
- theme/templates/includes/navbar.html
Resolves #5339
1. Checkout 2.13.4 or earlier hs
2. Create a user with an ORCID identifier that is invalid
3. Checkout this PR
4. Now attempt to create a resource
5. See that resource creation fails but now provides a more informative message about what action needs to be taken
> [#5339] Improve Party validation messaging during resource creation

- django_irods/views.py
- hs_core/tasks.py
- hsctl
- hydroshare/hydrocelery.py
- local-dev-first-start-only.sh
- scripts/templates/init-defaultworker.template
Resolves #5562 by creating a separate celery queue for periodic tasks and setting time limits for task duration
> [#5562] cpu constraints for celery workers

- .dockerignore
- local-dev-first-start-only.sh
Resolves #5587
The local-dev-first-start-only.sh script has been updated to remove the unnecessary "chown-root-items" command. This change aims to streamline the setup process and improve efficiency.
> Update local-dev-first-start-only.sh script

- local-dev-first-start-only.sh
We removed recursive chown in https://github.com/hydroshare/hydroshare/pull/5568 because it was very slow and appeared unnecessary.
However it seems that chown of `/tmp` should be retained. Starting with a fresh clone of `develop` looks like it results in permissions issues. This pr adds that back in.
> Fix file ownership during local development setup

- local-dev.yml
Resolves a regression for local dev introduced in https://github.com/hydroshare/hydroshare/pull/5662
1. Checkout `develop` branch at commit https://github.com/hydroshare/hydroshare/commit/22e3d8c78ed5b793bb0a2fbecc122f6ee42f8f7c
2. Build the whole project with `local-dev-first-start-only` and choose to rebuild all images
3. Attempt to create a resource version (or any other async task)
4. See that the task never gets processed (this is because the defaultworker service fails to run)
5. Now checkout this PR
6. Rebuild the project
7. See that the defaultworker service is now up and running: `docker ps | grep defaultworker`
8. In the UI at https://localhost, login
9. See that resource versioning is now succdesful
> Update defaultworker PostGIS configuration in local-dev.yml to use pgbouncer and disable server-side cursors

- theme/static/js/hs_file_browser.js
- theme/templates/resource-landing-page/funding-agency.html
> fixed the file and folder on hover issues

- .github/workflows/hydroshare-resouce-to-beta.yml
GH Action to copy resource contents from prod to beta, if bucket exists
> Copy resource contents from Prod to Beta

- hs_rest_api2/serializers.py
- hs_rest_api2/tests/test_resource_sharing_status.py
- hs_rest_api2/urls.py
- hs_rest_api2/views/metadata.py
1. Locally run this branch. 
2. Create a resource. Keep the resource in private sharing status (default status)
3. Navigate to API UI page at: `localhost:8000/hsapi2/`
4. Look for the endpoint: `/resource/{id}/sharing_status/json`
5. Use this endpoint to get the sharing status for the resource you created. You should see the response from the api call as: {"sharing_status": "private"}
6. Upload a file and add necessary metadata to make the resource discoverable. Again use the above endpoint and verify the api response.
7. Make the resource public. Use the above endpoint to check the sharing status.
> [#5825] Endpoint for retrieving resource sharing status

- theme/static/css/hydroshare_core.css
- theme/static/js/hs_file_browser.js
- theme/templates/resource-landing-page/top-right-buttons.html
[#5221] Adds a download button to the top right toolbar of the resource landing page. The button behaves exactly as the BagIt download button in the file explorer, and is subject to the same conditionals.
1. Go to the resource landing page.
2. Notice new button in the top right. 
3. Click the new button to download the resource content.
4. Go to the resource edit mode. Scroll to the bottom of the edit form and toggle the option to require agreement before download.
5. Go back to view mode and click the download button again.
6. Verify that the confirm dialog is hidden or shown as appropriate.
> [#5221] Add download button to top right toolbar in resource landing page

- hs_access_control/models/utilities.py
- hs_rest_api2/serializers.py
- hs_rest_api2/tests/test_resource_permission.py
- hs_rest_api2/urls.py
- hs_rest_api2/views/metadata.py
1. Run this branch locally.
2. Create a resource
3. Access the OpenAPI site by navigating to: `/hsapi2`
4. Look for the endpoint `/resource/{id}/permission/json`
5. Test this endpoint using the id of the resource. Verify the json response is `{"permission": "owner"}`.
6. Logout from the site. Test again the endpoint using the same resource id. Verify the json response is `{"permission": "none"}`
7.  For testing edit permission on a resource, you need to use another user account to create a new resource. Then give edit permission to the 1st user account. Then login using the 1st account. Now when you test the same endpoint using the id of the 2nd resource, you should get response as `{"permission": "edit"}`.
8. For testing view permission, change the permission for 1st user on 2nd resource …
> 5908 endpoint for user permission on resource

- hs_core/tests/api/native/test_add_resource_files.py
- theme/models.py
> [#5950] add default quota size when no resources are held

- hs_core/management/commands/check_published_bags.py
- hs_core/tasks.py
This fixes #5967 in 2 ways. First, the management command ensures all published resources have a bag generated and that the checksum is set. We should have a bag for published resources because it is used in the json-ld from the landing page.
The backup solution will set the bag modified flag to False before reading the checksum for a newly created bag. The user will still experience a problem for large published resources without an existing bag for the first download attempt, but all following download attempts will succeed. 
I'm open to suggestions to better ensure published resources have bags generated and avoid the possibility of an initial download failure on the first attempt.
1. Run the management command and ensure all published resources have a bag and checksum.
> 5967 published zips

- django_s3/storage.py
- hs_composite_resource/tests/test_composite_resource.py
- hs_core/tests/test_update_quota_usage.py
1. Download a zip on a windows machine and verify it unzips correctly. If you don't have a windows machine, you can download the zip and use zipinfo to ensure there is not a `/` at the beginning of the file content filenames.
> [#5964] - strip / in zip file contents filenames
